import PartiteConstruction.Structure.GeneratedWeakHomImage
import PartiteConstruction.Functional.ClosedLocalTreeCompletion

/-! # Generator-size bookkeeping for functional sparsening

The closure-aware iterated partite construction is naturally indexed by the
size of a generating set, rather than by the raw number of vertices.  For a
closed finite substructure this is no larger than its number of vertices, so
an n-step generator-size theorem implies the survey's desired statement for
all closed substructures on at most n vertices.

The main lemma below is the function-language form of the published
observation that closure size cannot increase under the part projection:
preimages of closed sets under weak homomorphisms are closed.
-/

namespace StructuralRamsey.Structure

universe u v
variable {L : Language.{u}} {U V : Type v}

/-- A set generates the whole structure under all set-valued functions. -/
def GeneratedBy (A : Structure L U) (S : Set U) : Prop :=
  A.functionClosure S = Set.univ

/-- A finite structure is generated by at most n named vertices. -/
def GeneratedByAtMost (A : Structure L U) (n : ℕ) : Prop :=
  ∃ S : Finset U, S.card ≤ n ∧ A.GeneratedBy (↑S : Set U)

namespace GeneratedByAtMost

theorem mono {A : Structure L U} {m n : ℕ}
    (h : A.GeneratedByAtMost m) (hmn : m ≤ n) :
    A.GeneratedByAtMost n := by
  rcases h with ⟨S, hS, hgen⟩
  exact ⟨S, hS.trans hmn, hgen⟩

theorem of_fintype (A : Structure L U) [Fintype U] :
    A.GeneratedByAtMost (Fintype.card U) := by
  refine ⟨Finset.univ, by simp, ?_⟩
  ext x
  constructor
  · intro _
    simp
  · intro _
    exact A.subset_functionClosure
      (↑(Finset.univ : Finset U) : Set U) (by simp)

end GeneratedByAtMost

/-- The closed hull of the image of a generated structure is already
generated by the image of the same generators.  Only weak preservation of
function incidences is needed. -/
theorem functionClosure_image_generators
    {A : Structure L U} {B : Structure L V}
    {f : U → V} (hf : A.IsWeakHomomorphism B f)
    (S : Set U) (hS : A.GeneratedBy S) :
    B.functionClosure (f '' S) =
      B.functionClosure (Set.range f) := by
  apply Set.Subset.antisymm
  · intro y hy
    apply hy
    · exact B.functionClosure_isClosed (Set.range f)
    · rintro _ ⟨x, hx, rfl⟩
      exact B.subset_functionClosure (Set.range f) ⟨x, rfl⟩
  · intro y hy
    let T : Set V := B.functionClosure (f '' S)
    have hT : B.IsClosed T :=
      B.functionClosure_isClosed (f '' S)
    have hpre : A.IsClosed {x | f x ∈ T} :=
      hf.preimage_isClosed T hT
    have hSpre : S ⊆ {x | f x ∈ T} := by
      intro x hx
      exact B.subset_functionClosure (f '' S) ⟨x, hx, rfl⟩
    have hall : ∀ x : U, f x ∈ T := by
      intro x
      have hx : x ∈ A.functionClosure S := by
        rw [hS]
        simp
      exact hx {a | f a ∈ T} hpre hSpre
    apply hy
    · exact hT
    · rintro _ ⟨x, rfl⟩
      exact hall x

/-- Finite generator sets do not grow when passing to the closed hull of a
weak homomorphic image. -/
theorem closureImage_generatedByAtMost
    {A : Structure L U} {B : Structure L V}
    {f : U → V} (hf : A.IsWeakHomomorphism B f)
    {n : ℕ} (hgen : A.GeneratedByAtMost n) :
    let H := B.functionClosure (Set.range f)
    (B.induce H (B.functionClosure_isClosed (Set.range f))).GeneratedByAtMost n := by
  classical
  rcases hgen with ⟨S, hScard, hSgen⟩
  let H := B.functionClosure (Set.range f)
  let C := B.induce H (B.functionClosure_isClosed (Set.range f))
  let lift : U → H := closureLift B f
  let G : Finset H := S.image (fun x => lift x)
  refine ⟨G, ?_, ?_⟩
  · exact (Finset.card_image_le).trans hScard
  · ext z
    constructor
    · intro _
      simp
    · intro _
      -- It is enough to prove that every closed set containing the lifted
      -- generators contains all lifted source points; those generate H.
      intro T hT hGT
      have hlift : ∀ x : U, lift x ∈ T := by
        let T0 : Set V := {b | ∃ hb : b ∈ H, (⟨b, hb⟩ : H) ∈ T}
        have hT0 : B.IsClosed T0 := by
          intro F x hx y hy
          let xs : Fin (L.funcArity F) → H :=
            fun i => ⟨x i, (hx i).choose⟩
          have hxs : ∀ i, xs i ∈ T :=
            fun i => (hx i).choose_spec
          have hyH :
              y ∈ H :=
            (B.functionClosure_isClosed (Set.range f))
              F x (fun i => (hx i).choose) hy
          have hyT : (⟨y, hyH⟩ : H) ∈ T :=
            hT F xs hxs hy
          exact ⟨hyH, hyT⟩
        have hpre : A.IsClosed {x | f x ∈ T0} :=
          hf.preimage_isClosed T0 hT0
        have hSpre : (↑S : Set U) ⊆ {x | f x ∈ T0} := by
          intro x hx
          have hxG : lift x ∈ G := by
            exact Finset.mem_image.mpr ⟨x, hx, rfl⟩
          have hxT : lift x ∈ T := hGT hxG
          exact ⟨(lift x).2, hxT⟩
        intro x
        have hxcl : x ∈ A.functionClosure (↑S : Set U) := by
          rw [hSgen]
          simp
        have hxpre := hxcl {a | f a ∈ T0} hpre hSpre
        exact hxpre.2
      have hclosedAll : C.Generates lift :=
        closureLift_generates B f
      exact hclosedAll T hT hlift z

/-- Any finite full structure is generated by all of its vertices. -/
theorem generatedByAtMost_card
    (A : Structure L U) [Fintype U] :
    A.GeneratedByAtMost (Fintype.card U) :=
  GeneratedByAtMost.of_fintype A

end StructuralRamsey.Structure
