import PartiteConstruction.Structure.GeneratedWeakHomImage
import PartiteConstruction.Functional.ClosedLocalTreeCompletion

/-! # Generator-size bookkeeping for functional sparsening

The closure-aware iterated partite construction is naturally indexed by the
size of a generating set, rather than by the raw number of vertices.  For a
closed finite substructure this is no larger than its number of vertices, so
an n-step generator-size theorem implies the survey's desired statement for
all closed substructures on at most n vertices.

The main lemma below is the function-language form of the published
observation that closure size cannot increase under the part projection:
preimages of closed sets under weak homomorphisms are closed.
-/

namespace StructuralRamsey.Structure

universe u v
variable {L : Language.{u}} {U V : Type v}

/-- A set generates the whole structure under all set-valued functions. -/
def GeneratedBy (A : Structure L U) (S : Set U) : Prop :=
  A.functionClosure S = Set.univ

/-- A finite structure is generated by at most n named vertices. -/
def GeneratedByAtMost (A : Structure L U) (n : ℕ) : Prop :=
  ∃ S : Finset U, S.card ≤ n ∧ A.GeneratedBy (↑S : Set U)

namespace GeneratedByAtMost

theorem mono {A : Structure L U} {m n : ℕ}
    (h : A.GeneratedByAtMost m) (hmn : m ≤ n) :
    A.GeneratedByAtMost n := by
  rcases h with ⟨S, hS, hgen⟩
  exact ⟨S, hS.trans hmn, hgen⟩

theorem of_fintype (A : Structure L U) [Fintype U] :
    A.GeneratedByAtMost (Fintype.card U) := by
  refine ⟨Finset.univ, by simp, ?_⟩
  ext x
  constructor
  · intro _
    simp
  · intro _
    exact A.subset_functionClosure
      (↑(Finset.univ : Finset U) : Set U) (by simp)

end GeneratedByAtMost

/-- The closed hull of a finite set is generated by at most the
number of vertices in that set. -/
theorem functionClosure_finset_generatedByAtMost
    (B : Structure L V) (S : Finset V) :
    let H := B.functionClosure (↑S : Set V)
    GeneratedByAtMost
      (B.induce H (B.functionClosure_isClosed (↑S : Set V))) S.card := by
  classical
  let H := B.functionClosure (↑S : Set V)
  let C := B.induce H (B.functionClosure_isClosed (↑S : Set V))
  let lift : ↥(↑S : Set V) → H :=
    fun x => ⟨x.1, B.subset_functionClosure (↑S : Set V) x.2⟩
  let G : Finset H := Finset.univ.image lift
  refine ⟨G, ?_, ?_⟩
  · calc
      G.card ≤ (Finset.univ : Finset ↥(↑S : Set V)).card :=
        Finset.card_image_le
      _ = S.card := by simp
  · ext z
    constructor
    · intro _
      simp
    · intro _
      intro T hT hGT
      let T0 : Set V := {b | ∃ hb : b ∈ H, (⟨b, hb⟩ : H) ∈ T}
      have hT0 : B.IsClosed T0 := by
        intro F x hx y hy
        let xs : Fin (L.funcArity F) → H :=
          fun i => ⟨x i, (hx i).choose⟩
        have hxs : ∀ i, xs i ∈ T :=
          fun i => (hx i).choose_spec
        have hyH : y ∈ H :=
          (B.functionClosure_isClosed (↑S : Set V))
            F x (fun i => (hx i).choose) hy
        have hyT : (⟨y, hyH⟩ : H) ∈ T :=
          hT F xs hxs hy
        exact ⟨hyH, hyT⟩
      have hST0 : (↑S : Set V) ⊆ T0 := by
        intro x hx
        let xs : ↥(↑S : Set V) := ⟨x, hx⟩
        have hxG : lift xs ∈ G := by
          exact Finset.mem_image.mpr ⟨xs, by simp, rfl⟩
        exact ⟨(lift xs).2, hGT hxG⟩
      have hzT0 : z.1 ∈ T0 :=
        z.2 T0 hT0 hST0
      exact hzT0.2

/-- The closed hull of the image of a generated structure is already
generated by the image of the same generators.  Only weak preservation of
function incidences is needed. -/
theorem functionClosure_image_generators
    {A : Structure L U} {B : Structure L V}
    {f : U → V} (hf : A.IsWeakHomomorphism B f)
    (S : Set U) (hS : A.GeneratedBy S) :
    B.functionClosure (f '' S) =
      B.functionClosure (Set.range f) := by
  apply Set.Subset.antisymm
  · intro y hy
    apply hy
    · exact B.functionClosure_isClosed (Set.range f)
    · rintro _ ⟨x, hx, rfl⟩
      exact B.subset_functionClosure (Set.range f) ⟨x, rfl⟩
  · intro y hy
    let T : Set V := B.functionClosure (f '' S)
    have hT : B.IsClosed T :=
      B.functionClosure_isClosed (f '' S)
    have hpre : A.IsClosed {x | f x ∈ T} :=
      hf.preimage_isClosed T hT
    have hSpre : S ⊆ {x | f x ∈ T} := by
      intro x hx
      exact B.subset_functionClosure (f '' S) ⟨x, hx, rfl⟩
    have hall : ∀ x : U, f x ∈ T := by
      intro x
      have hx : x ∈ A.functionClosure S := by
        rw [hS]
        simp
      exact hx {a | f a ∈ T} hpre hSpre
    apply hy
    · exact hT
    · rintro _ ⟨x, rfl⟩
      exact hall x

/-- Finite generator sets do not grow when passing to the closed hull of a
weak homomorphic image. -/
theorem closureImage_generatedByAtMost
    {A : Structure L U} {B : Structure L V}
    {f : U → V} (hf : A.IsWeakHomomorphism B f)
    {n : ℕ} (hgen : A.GeneratedByAtMost n) :
    let H := B.functionClosure (Set.range f)
    (B.induce H (B.functionClosure_isClosed (Set.range f))).GeneratedByAtMost n := by
  classical
  rcases hgen with ⟨S, hScard, hSgen⟩
  let H := B.functionClosure (Set.range f)
  let C := B.induce H (B.functionClosure_isClosed (Set.range f))
  let lift : U → H := closureLift B f
  let G : Finset H := S.image (fun x => lift x)
  refine ⟨G, ?_, ?_⟩
  · exact (Finset.card_image_le).trans hScard
  · ext z
    constructor
    · intro _
      simp
    · intro _
      -- It is enough to prove that every closed set containing the lifted
      -- generators contains all lifted source points; those generate H.
      intro T hT hGT
      have hlift : ∀ x : U, lift x ∈ T := by
        let T0 : Set V := {b | ∃ hb : b ∈ H, (⟨b, hb⟩ : H) ∈ T}
        have hT0 : B.IsClosed T0 := by
          intro F x hx y hy
          let xs : Fin (L.funcArity F) → H :=
            fun i => ⟨x i, (hx i).choose⟩
          have hxs : ∀ i, xs i ∈ T :=
            fun i => (hx i).choose_spec
          have hyH :
              y ∈ H :=
            (B.functionClosure_isClosed (Set.range f))
              F x (fun i => (hx i).choose) hy
          have hyT : (⟨y, hyH⟩ : H) ∈ T :=
            hT F xs hxs hy
          exact ⟨hyH, hyT⟩
        have hpre : A.IsClosed {x | f x ∈ T0} :=
          hf.preimage_isClosed T0 hT0
        have hSpre : (↑S : Set U) ⊆ {x | f x ∈ T0} := by
          intro x hx
          have hxG : lift x ∈ G := by
            exact Finset.mem_image.mpr ⟨x, hx, rfl⟩
          have hxT : lift x ∈ T := hGT hxG
          exact ⟨(lift x).2, hxT⟩
        intro x
        have hxcl : x ∈ A.functionClosure (↑S : Set U) := by
          rw [hSgen]
          simp
        have hxpre := hxcl {a | f a ∈ T0} hpre hSpre
        exact hxpre.2
      have hclosedAll : C.Generates lift :=
        closureLift_generates B f
      exact hclosedAll T hT hlift z


/-- The (closed) range of a full homomorphism is generated by the images of
any generating set of the source, so full homomorphic images do not increase
generator size. -/
theorem homRange_generatedByAtMost
    {A : Structure L U} {B : Structure L V}
    {f : U → V} (hf : A.IsHomomorphism B f)
    {n : ℕ} (hgen : A.GeneratedByAtMost n) :
    (B.induce (Set.range f) hf.range_isClosed).GeneratedByAtMost n := by
  classical
  rcases hgen with ⟨S, hScard, hSgen⟩
  let R := Set.range f
  let C := B.induce R hf.range_isClosed
  let lift : U → R := fun x => ⟨f x, ⟨x, rfl⟩⟩
  let G : Finset R := S.image lift
  refine ⟨G, Finset.card_image_le.trans hScard, ?_⟩
  ext z
  constructor
  · intro _
    simp
  · intro _
    intro T hT hGT
    have hpre : A.IsClosed {x | lift x ∈ T} := by
      intro F x hx y hy
      have hfy : f y ∈ B.func F (f ∘ x) := by
        have himg : f y ∈ imageSet f (A.func F x) := ⟨y, hy, rfl⟩
        rw [hf.2 F x] at himg
        exact himg
      have hyR : f y ∈ R := ⟨y, rfl⟩
      exact hT F (lift ∘ x) hx hfy
    have hSpre : (↑S : Set U) ⊆ {x | lift x ∈ T} := by
      intro x hx
      apply hGT
      exact Finset.mem_image.mpr ⟨x, hx, rfl⟩
    have hall : ∀ x : U, lift x ∈ T := by
      intro x
      have hx : x ∈ A.functionClosure (↑S : Set U) := by
        rw [hSgen]
        simp
      exact hx {a | lift a ∈ T} hpre hSpre
    rcases z.2 with ⟨x, hx⟩
    have hz : z = lift x := by
      apply Subtype.ext
      exact hx.symm
    rw [hz]
    exact hall x

/-- A surjective full embedding preserves a finite generator bound. -/
theorem GeneratedByAtMost.of_surjective_embedding
    {A : Structure L U} {B : Structure L V}
    {n : ℕ} (hgen : A.GeneratedByAtMost n)
    (e : Embedding A B) (hsurj : Function.Surjective e) :
    B.GeneratedByAtMost n := by
  classical
  rcases hgen with ⟨S, hScard, hSgen⟩
  let G : Finset V := S.image e
  refine ⟨G, (Finset.card_image_le).trans hScard, ?_⟩
  ext b
  constructor
  · intro _
    simp
  · intro _
    intro T hT hGT
    obtain ⟨a, rfl⟩ := hsurj b
    have hpre : A.IsClosed {x | e x ∈ T} :=
      e.isHomomorphism.preimage_isClosed T hT
    have hSpre : (↑S : Set U) ⊆ {x | e x ∈ T} := by
      intro x hx
      apply hGT
      exact Finset.mem_image.mpr ⟨x, hx, rfl⟩
    have hx : a ∈ A.functionClosure (↑S : Set U) := by
      rw [hSgen]
      simp
    exact hx {x | e x ∈ T} hpre hSpre

/-- Any finite full structure is generated by all of its vertices. -/
theorem generatedByAtMost_card
    (A : Structure L U) [Fintype U] :
    A.GeneratedByAtMost (Fintype.card U) :=
  GeneratedByAtMost.of_fintype A

end StructuralRamsey.Structure
