import PartiteConstruction.Functional.FibreExactness

/-! # EHN fibre bijectivity on every defined input

An EHN projection is globally weak, but its restrictions to full
irreducible substructures are full embeddings. If a source function fibre
F(x) is nonempty, the closed hull generated by the input tuple x is
irreducible. It contains every output of this fibre.

Hence the projection is not only surjective on that fibre
(`IsEHNHomomorphismEmbedding.map_func_of_nonempty`), but also injective.
The only possible failure of exact fibre preservation is an *empty*
source fibre whose target fibre is nonempty: a domain-reflection failure.

No function-closed hull of an arbitrary weak test or projected image is
used in the vertex-size induction. The hull here belongs exclusively to
the proof of this local fibre lemma. -/

namespace StructuralRamsey.Structure

universe u v

variable {L : Language.{u}}
variable {U V : Type v}

/-- An EHN projection is injective on every nonempty function fibre.
This is stronger than the already-checked surjectivity of its image. -/
theorem IsEHNHomomorphismEmbedding.injOn_func_of_nonempty
    {C : Structure L U} {D : Structure L V} {p : U → V}
    (hp : C.IsEHNHomomorphismEmbedding D p)
    (F : L.FuncSymbol) (x : Fin (L.funcArity F) → U)
    (hne : (C.func F x).Nonempty) :
    Set.InjOn p (C.func F x) := by
  classical
  obtain ⟨y₀, hy₀⟩ := hne
  let Hset : Set U := C.functionClosure (Set.range x)
  have hClosed : C.IsClosed Hset :=
    C.functionClosure_isClosed (Set.range x)
  let H : Structure L Hset := C.induce Hset hClosed
  have hIrr : H.Irreducible := by
    change (C.induce
        (C.functionClosure (Set.range x))
        (C.functionClosure_isClosed (Set.range x))).Irreducible
    exact functionClosure_inputs_irreducible_of_value C F x hy₀
  let inc : Embedding H C := inclusion C Hset hClosed
  obtain ⟨g, hg⟩ := hp.2 H hIrr inc
  have hInputs : ∀ i : Fin (L.funcArity F), x i ∈ Hset := by
    intro i
    exact C.subset_functionClosure (Set.range x) ⟨i, rfl⟩
  intro y hy z hz heq
  have hyH : y ∈ Hset := hClosed F x hInputs hy
  have hzH : z ∈ Hset := hClosed F x hInputs hz
  have hgeq :
      g (⟨y, hyH⟩ : Hset) = g (⟨z, hzH⟩ : Hset) := by
    calc
      g (⟨y, hyH⟩ : Hset) = p y := hg _
      _ = p z := heq
      _ = g (⟨z, hzH⟩ : Hset) := (hg _).symm
  exact congrArg Subtype.val (g.injective hgeq)

/-- For a defined input, an EHN projection maps the entire function fibre
bijectively onto the target fibre. In particular there is no independent
multiplicity-of-outputs obstruction. -/
theorem IsEHNHomomorphismEmbedding.bijOn_func_of_nonempty
    {C : Structure L U} {D : Structure L V} {p : U → V}
    (hp : C.IsEHNHomomorphismEmbedding D p)
    (F : L.FuncSymbol) (x : Fin (L.funcArity F) → U)
    (hne : (C.func F x).Nonempty) :
    Set.BijOn p (C.func F x) (D.func F (p ∘ x)) := by
  refine ⟨?_, hp.injOn_func_of_nonempty F x hne, ?_⟩
  · intro y hy
    exact hp.1.2 F x y hy
  · intro y hy
    have himg : y ∈ imageSet p (C.func F x) := by
      rw [hp.map_func_of_nonempty F x hne]
      exact hy
    exact himg

end StructuralRamsey.Structure
