import PartiteConstruction.Functional.WeakInvariant
import PartiteConstruction.Structure.GeneratedWeakHomImage

/-! # Fibre exactness of EHN projections on defined inputs

For a full relation/function structure, if one function fibre over an input
tuple is nonempty, then the closed hull generated by that input tuple is
irreducible.  Indeed, in any free decomposition the witnessed function
incidence comes wholly from one side, so all input generators lie on that
side; since the side is closed and the inputs generate the hull, the whole
hull lies there.

Consequently an EHN projection (weak globally, full on irreducibles) is already
fibre-surjective on every input where the source function is defined.  The
only possible failure of full fibre-surjectivity is therefore domain
reflection: an input with empty source fibre whose projected target fibre is
nonempty.
-/

namespace StructuralRamsey.Structure

universe u v

variable {L : Language.{u}}
variable {U V : Type v}

/-- The closed hull generated by the inputs of one realized function
incidence is irreducible. -/
theorem functionClosure_inputs_irreducible_of_value
    (A : Structure L U)
    (F : L.FuncSymbol)
    (x : Fin (L.funcArity F) → U)
    {y : U} (hy : y ∈ A.func F x) :
    let Hset := A.functionClosure (Set.range x)
    (A.induce Hset
      (A.functionClosure_isClosed (Set.range x))).Irreducible := by
  classical
  let Hset := A.functionClosure (Set.range x)
  have hHclosed : A.IsClosed Hset :=
    A.functionClosure_isClosed (Set.range x)
  let H : Structure L Hset := A.induce Hset hHclosed
  let q : Fin (L.funcArity F) → Hset :=
    fun i => ⟨x i,
      A.subset_functionClosure (Set.range x) ⟨i, rfl⟩⟩
  have hqgen :
      Generates (U := Fin (L.funcArity F)) H q := by
    simpa [H, Hset, q, closureLift] using
      (closureLift_generates A x)
  have hyH : y ∈ Hset := by
    apply hHclosed F x
    · intro i
      exact A.subset_functionClosure (Set.range x) ⟨i, rfl⟩
    · exact hy
  let yH : Hset := ⟨y, hyH⟩
  have hfunc : yH ∈ H.func F q := by
    change y ∈ A.func F (Subtype.val ∘ q)
    have hqx : Subtype.val ∘ q = x := by rfl
    rw [hqx]
    exact hy
  rw [irreducible_iff_noProperFreeDecomposition]
  rintro ⟨d⟩
  rcases (d.free.func_iff F q yH).mp hfunc with hleft | hright
  · rcases hleft with ⟨args, out, hout, hargs, _⟩
    apply d.leftProper
    intro z
    have hzRange : z ∈ Set.range d.leftIn := by
      apply hqgen (Set.range d.leftIn) d.leftIn.range_isClosed
      intro i
      refine ⟨args i, ?_⟩
      exact (congrFun hargs i).symm
    exact hzRange
  · rcases hright with ⟨args, out, hout, hargs, _⟩
    apply d.rightProper
    intro z
    have hzRange : z ∈ Set.range d.rightIn := by
      apply hqgen (Set.range d.rightIn) d.rightIn.range_isClosed
      intro i
      refine ⟨args i, ?_⟩
      exact (congrFun hargs i).symm
    exact hzRange

/-- On every input with a nonempty source fibre, an EHN projection maps the
complete source fibre onto the complete target fibre. -/
theorem IsEHNHomomorphismEmbedding.map_func_of_nonempty
    {A : Structure L U} {B : Structure L V}
    {p : U → V}
    (hp : A.IsEHNHomomorphismEmbedding B p)
    (F : L.FuncSymbol)
    (x : Fin (L.funcArity F) → U)
    (hne : (A.func F x).Nonempty) :
    imageSet p (A.func F x) = B.func F (p ∘ x) := by
  classical
  ext y
  constructor
  · rintro ⟨z, hz, rfl⟩
    exact hp.1.2 F x z hz
  · intro hy
    let Hset := A.functionClosure (Set.range x)
    have hHclosed : A.IsClosed Hset :=
      A.functionClosure_isClosed (Set.range x)
    let H : Structure L Hset := A.induce Hset hHclosed
    obtain ⟨y0, hy0⟩ := hne
    have hHirr : H.Irreducible := by
      change
        (A.induce Hset
          (A.functionClosure_isClosed (Set.range x))).Irreducible
      exact functionClosure_inputs_irreducible_of_value A F x hy0
    let inc : Embedding H A := inclusion A Hset hHclosed
    obtain ⟨g, hg⟩ := hp.2 H hHirr inc
    let q : Fin (L.funcArity F) → Hset :=
      fun i => ⟨x i,
        A.subset_functionClosure (Set.range x) ⟨i, rfl⟩⟩
    have hqA : Subtype.val ∘ q = x := by rfl
    have hgargs : g ∘ q = p ∘ x := by
      funext i
      exact hg (q i)
    have hy' : y ∈ B.func F (g ∘ q) := by
      rw [hgargs]
      exact hy
    have himg : y ∈ imageSet g (H.func F q) := by
      rw [g.map_func F q]
      exact hy'
    rcases himg with ⟨z, hz, hzy⟩
    refine ⟨z.1, ?_, ?_⟩
    · change z.1 ∈ A.func F (Subtype.val ∘ q) at hz
      rw [hqA] at hz
      exact hz
    · calc
        p z.1 = g z := (hg z).symm
        _ = y := hzy

/-- An EHN projection is a full homomorphism exactly when it also reflects
function-domain nonemptiness.  The forward incidence and nonempty-fibre
surjectivity are automatic. -/
theorem IsEHNHomomorphismEmbedding.isHomomorphism_of_domainReflection
    {A : Structure L U} {B : Structure L V}
    {p : U → V}
    (hp : A.IsEHNHomomorphismEmbedding B p)
    (hreflect :
      ∀ F (x : Fin (L.funcArity F) → U),
        (B.func F (p ∘ x)).Nonempty → (A.func F x).Nonempty) :
    A.IsHomomorphism B p := by
  constructor
  · exact hp.1.1
  · intro F x
    by_cases hsrc : (A.func F x).Nonempty
    · exact hp.map_func_of_nonempty F x hsrc
    · have htgt : ¬ (B.func F (p ∘ x)).Nonempty := by
        intro h
        exact hsrc (hreflect F x h)
      ext y
      constructor
      · rintro ⟨z, hz, _⟩
        exact False.elim (hsrc ⟨z, hz⟩)
      · intro hy
        exact False.elim (htgt ⟨y, hy⟩)

end StructuralRamsey.Structure
