import PartiteConstruction.Functional.PureHistoryTreeCompletion
import PartiteConstruction.Functional.HistoryTreeCompletion

/-! # Projected-history completions at a fixed vertex bound

The functional iteration ultimately concerns genuine closed substructures
with at most n vertices.  Such a finite structure is generated by at most
n vertices, even in the presence of set-valued functions.  Pullback of the
combined history invariant along a full embedding then supplies its complete
projected-history witness.

This avoids incorrectly requiring a whole (possibly very large) EHN
Picture stage to be generated by at most n vertices merely to deal with a
pure test inside it.
-/

namespace StructuralRamsey.Structure.FunctionalHistoryTreeLike

universe u v

variable {L : Language.{u}}
variable {U P W V X : Type v}
variable {A : Structure L U} {D : Structure L P}
variable {C : Structure L W} {Base : Structure L V}
variable {p : W → P} {n : ℕ}

/-- Every finite full embedded test with at most n vertices inherits a full
projected-history completion from the ambient generator-rank-n invariant. -/
theorem fullProjectedHistory_of_smallEmbedding
    [Finite X]
    (h : FunctionalHistoryTreeLike
      (A := A) (D := D) (C := C) (Base := Base) p n)
    (Small : Structure L X)
    (e : Embedding Small C)
    (hcard : Nat.card X ≤ n) :
    HasProjectedHistoryTreeCompletion Base Small (p ∘ e) := by
  classical
  letI : Fintype X := Fintype.ofFinite X
  have hgen : Small.GeneratedByAtMost n := by
    apply (generatedByAtMost_card Small).mono
    simpa only [Nat.card_eq_fintype_card] using hcard
  have hSmall :
      FunctionalHistoryTreeLike
        (A := A) (D := D) (C := Small) (Base := Base)
        (p ∘ e) n :=
    h.pullback_embedding e
  exact hSmall.toProjectedHistory.toFullProjectedHistoryCompletion hgen

end StructuralRamsey.Structure.FunctionalHistoryTreeLike
