import PartiteConstruction.Functional.ClosedGeneratorRank
import PartiteConstruction.Structure.FreeAmalgam

/-! # Generator budgets for functional free amalgams

A generated substructure of a free amalgam may use generators from both sides.
For one fixed side, the generators landing on that side together with the
whole common root already generate the side.  Functions cannot cross the free
amalgam: a derivation coming from the other side can enter the chosen side
only through the common root.

This is the function-language replacement for the elementary cardinal bound
used in the relational root-budget argument.
-/

namespace StructuralRamsey.Structure.IsFreeAmalgam

universe u v

variable {L : Language.{u}}
variable {H E F C : Type v}
variable {Root : Structure L H}
variable {Left : Structure L E}
variable {Right : Structure L F}
variable {Whole : Structure L C}
variable {sL : Embedding Root Left}
variable {sR : Embedding Root Right}
variable {iL : Embedding Left Whole}
variable {iR : Embedding Right Whole}

/-- If the whole free amalgam is generated by at most `n` vertices, the
left side is generated by at most `n + |Root|` vertices. -/
theorem left_generatedByAtMost_add_root
    [Finite H] [Finite E]
    (hfree : IsFreeAmalgam sL sR iL iR)
    {n : ℕ}
    (hgen : Whole.GeneratedByAtMost n) :
    Left.GeneratedByAtMost (n + Nat.card H) := by
  classical
  letI : Fintype H := Fintype.ofFinite H
  letI : Fintype E := Fintype.ofFinite E
  rcases hgen with ⟨G, hGcard, hGgen⟩

  let GL : Finset E :=
    (Finset.univ : Finset E).filter (fun x => iL x ∈ G)
  let GR : Finset E :=
    (Finset.univ : Finset H).image sL
  let Gen : Finset E := GL ∪ GR

  have hGLcard : GL.card ≤ G.card := by
    let phi : ↥(↑GL : Set E) → ↥(↑G : Set C) :=
      fun x => ⟨iL x.1, (Finset.mem_filter.mp x.2).2⟩
    have hphi : Function.Injective phi := by
      intro x y hxy
      apply Subtype.ext
      apply iL.injective
      exact congrArg Subtype.val hxy
    simpa [GL] using Fintype.card_le_of_injective phi hphi

  have hGRcard : GR.card ≤ Nat.card H := by
    simpa only [Nat.card_eq_fintype_card] using
      (Finset.card_image_le
        (s := (Finset.univ : Finset H)) (f := sL))

  refine ⟨Gen, ?_, ?_⟩
  · calc
      Gen.card ≤ GL.card + GR.card := Finset.card_union_le _ _
      _ ≤ G.card + Nat.card H :=
        Nat.add_le_add hGLcard hGRcard
      _ ≤ n + Nat.card H :=
        Nat.add_le_add_right hGcard (Nat.card H)
  · ext x
    constructor
    · intro _
      simp
    · intro _
      intro T hT hGenT

      let TWhole : Set C :=
        Set.range iR ∪ iL '' T

      have hCommonT : ∀ d : H, sL d ∈ T := by
        intro d
        apply hGenT
        apply Finset.mem_union_right
        exact Finset.mem_image.mpr ⟨d, Finset.mem_univ d, rfl⟩

      have hTWholeClosed : Whole.IsClosed TWhole := by
        intro F0 args hargs y hy
        rcases (hfree.func_iff F0 args y).mp hy with
          hleft | hright
        · rcases hleft with ⟨a, b, hb, hargsEq, hyEq⟩
          have haT : ∀ k, a k ∈ T := by
            intro k
            have hk : iL (a k) ∈ TWhole := by
              rw [← congrFun hargsEq k]
              exact hargs k
            rcases hk with hR | hL
            · rcases hR with ⟨r, hr⟩
              obtain ⟨d, had, _⟩ :=
                (hfree.overlap (a k) r).mp hr.symm
              rw [had]
              exact hCommonT d
            · rcases hL with ⟨a', ha'T, ha'eq⟩
              have haa : a' = a k := iL.injective ha'eq
              simpa [haa] using ha'T
          have hbT : b ∈ T := hT F0 a haT hb
          exact Or.inr ⟨b, hbT, hyEq⟩
        · rcases hright with ⟨a, b, hb, hargsEq, hyEq⟩
          exact Or.inl ⟨b, hyEq⟩

      have hGTWhole : (↑G : Set C) ⊆ TWhole := by
        intro g hg
        rcases hfree.covers g with ⟨l, hgl⟩ | ⟨r, hgr⟩
        · have hlGL : l ∈ GL := by
            apply Finset.mem_filter.mpr
            exact ⟨Finset.mem_univ l, by simpa [hgl] using hg⟩
          have hlT : l ∈ T := by
            apply hGenT
            exact Finset.mem_union_left Gen hlGL
          exact Or.inr ⟨l, hlT, hgl⟩
        · exact Or.inl ⟨r, hgr⟩

      have hxWhole : iL x ∈ TWhole := by
        have hxClosure : iL x ∈ Whole.functionClosure (↑G : Set C) := by
          rw [hGgen]
          simp
        exact hxClosure TWhole hTWholeClosed hGTWhole

      rcases hxWhole with hR | hL
      · rcases hR with ⟨r, hr⟩
        obtain ⟨d, hxd, _⟩ :=
          (hfree.overlap x r).mp hr.symm
        rw [hxd]
        exact hCommonT d
      · rcases hL with ⟨l, hlT, hleq⟩
        have hlx : l = x := iL.injective hleq
        simpa [hlx] using hlT

/-- Symmetric generator budget for the right side. -/
theorem right_generatedByAtMost_add_root
    [Finite H] [Finite F]
    (hfree : IsFreeAmalgam sL sR iL iR)
    {n : ℕ}
    (hgen : Whole.GeneratedByAtMost n) :
    Right.GeneratedByAtMost (n + Nat.card H) := by
  exact hfree.swap.left_generatedByAtMost_add_root hgen

end StructuralRamsey.Structure.IsFreeAmalgam
