import PartiteConstruction.Functional.ClosedGeneratorRank
import PartiteConstruction.Functional.WitnessGlue
import PartiteConstruction.Functional.WeakInvariant

/-! # Generator-local tree completability for function structures

The closure-aware iteration is naturally phrased for finite structures
generated by at most n vertices.  Since every genuine substructure is the
image of a full embedding, using embeddings as the interface avoids repeated
set/subtype bookkeeping and is stable under change of presentation.
-/

namespace StructuralRamsey.Structure

universe u v
variable {L : Language.{u}}
variable {V W X Y : Type v}

/-- Restrict the target of a full homomorphism-embedding to its closed range. -/
theorem IsHomomorphismEmbedding.codRestrictRange
    {A : Structure L V} {B : Structure L W}
    {f : V → W} (hf : A.IsHomomorphismEmbedding B f) :
    let R := Set.range f
    A.IsHomomorphismEmbedding
      (B.induce R hf.1.range_isClosed)
      (fun x => ⟨f x, ⟨x, rfl⟩⟩) := by
  let R := Set.range f
  let lift : V → R := fun x => ⟨f x, ⟨x, rfl⟩⟩
  have hhom :
      A.IsHomomorphism (B.induce R hf.1.range_isClosed) lift :=
    hf.1.codRestrict R hf.1.range_isClosed (fun x => ⟨x, rfl⟩)
  refine ⟨hhom, ?_⟩
  intro Z E hE e
  obtain ⟨g, hg⟩ := hf.2 E hE e
  let inc : Embedding (B.induce R hf.1.range_isClosed) B :=
    inclusion B R hf.1.range_isClosed
  have hrange : ∀ z, ∃ r : R, g z = inc r := by
    intro z
    let r : R := ⟨g z, ⟨e z, (hg z).symm⟩⟩
    exact ⟨r, rfl⟩
  let gr : Embedding E (B.induce R hf.1.range_isClosed) :=
    g.factorThroughRange inc hrange
  refine ⟨gr, ?_⟩
  intro z
  apply Subtype.ext
  have hfactor : g z = inc (gr z) :=
    Classical.choose_spec (hrange z)
  change (gr z).1 = f (e z)
  exact hfactor.symm.trans (hg z)


/-- An irreducible test in an EHN-partite functional system already has a
one-copy tree completion.  The weak global projection becomes a genuine full
embedding on the irreducible test by definition of the EHN invariant. -/
theorem HasTreeCompletion.of_irreducible_partite
    {P Z : Type v}
    {A : Structure L P} {Base : Structure L V}
    {C : FunctionalPartite.System L P W}
    (hC : C.WeaklyPartiteOver A)
    (eAB : Embedding A Base)
    (E : Structure L Z) (hE : E.Irreducible)
    (e : Embedding E C.toStructure) :
    HasTreeCompletion Base E := by
  obtain ⟨g, hg⟩ := hC.2 E hE e
  let h : Embedding E Base := eAB.comp g
  have hTree : TreeAmalgam Base V Base :=
    TreeAmalgam.copy (Embedding.id Base) (by
      intro x
      exact ⟨x, rfl⟩)
  exact ⟨V, Base, hTree, h, h.isHomomorphismEmbedding⟩

/-- Every finite n-generated genuine substructure of C has a full
homomorphism-embedding into a genuine tree amalgam of copies of Base. -/
def LocallyGeneratedTreeCompletable
    (Base : Structure L V) (C : Structure L W) (n : ℕ) : Prop :=
  ∀ {Z : Type v} [Finite Z] (E : Structure L Z),
    E.GeneratedByAtMost n →
    ∀ e : Embedding E C, HasTreeCompletion Base E

namespace LocallyGeneratedTreeCompletable

variable {Base : Structure L V} {C : Structure L W}
variable {m n : ℕ}

theorem mono
    (h : LocallyGeneratedTreeCompletable Base C n) (hmn : m ≤ n) :
    LocallyGeneratedTreeCompletable Base C m := by
  intro Z _ E hE e
  exact h (Z := Z) E (hE.mono hmn) e

/-- A tree amalgam of Base is generator-locally tree completable at every
finite level, by the inclusion of each genuine substructure. -/
theorem of_treeAmalgam
    (hTree : TreeAmalgam Base W C) (n : ℕ) :
    LocallyGeneratedTreeCompletable Base C n := by
  intro Z _ E _ e
  exact ⟨W, C, hTree, e, e.isHomomorphismEmbedding⟩

theorem base (Base : Structure L V) (n : ℕ) :
    LocallyGeneratedTreeCompletable Base Base n := by
  have hTree : TreeAmalgam Base V Base :=
    TreeAmalgam.copy (Embedding.id Base) (by
      intro x
      exact ⟨x, rfl⟩)
  intro Z _ E _ e
  exact ⟨V, Base, hTree, e, e.isHomomorphismEmbedding⟩

/-- The generator-local property pulls back along a full
homomorphism-embedding.  This is the composition step used whenever the
closure-aware partite projection is already full. -/
theorem pullback_homEmbedding
    {D : Structure L X} {p : W → X}
    (hp : C.IsHomomorphismEmbedding D p)
    (hD : LocallyGeneratedTreeCompletable Base D n) :
    LocallyGeneratedTreeCompletable Base C n := by
  intro Z _ E hgen e
  let q : Z → X := p ∘ e
  have hED : E.IsHomomorphismEmbedding D q :=
    hp.comp e.isHomomorphismEmbedding
  let Rset : Set X := Set.range q
  let R := D.induce Rset hED.1.range_isClosed
  let qR : Z → Rset := fun z => ⟨q z, ⟨z, rfl⟩⟩
  have hER : E.IsHomomorphismEmbedding R qR := by
    simpa [R, Rset, qR] using hED.codRestrictRange
  have hRgen : R.GeneratedByAtMost n := by
    exact homRange_generatedByAtMost hED.1 hgen
  let inc : Embedding R D := inclusion D Rset hED.1.range_isClosed
  obtain ⟨TCarrier, T, hTree, f, hf⟩ :=
    hD (Z := Rset) R hRgen inc
  exact ⟨TCarrier, T, hTree, f ∘ qR, hf.comp hER⟩

/-- Generator-local completability implies the user-facing closed-substructure
statement: a closed set of at most n vertices is generated by all its
vertices. -/
theorem toLocallyClosedTreeCompletable
    (h : LocallyGeneratedTreeCompletable Base C n) :
    LocallyClosedTreeCompletable Base C n := by
  intro S hScard hclosed
  let E := C.induce (↑S : Set W) hclosed
  letI : Fintype ↥(↑S : Set W) := Fintype.ofFinite _
  have hgen0 :
      E.GeneratedByAtMost (Fintype.card ↥(↑S : Set W)) :=
    generatedByAtMost_card E
  have hcard :
      Fintype.card ↥(↑S : Set W) = S.card := by
    simp
  have hgen : E.GeneratedByAtMost n := by
    apply hgen0.mono
    simpa [hcard] using hScard
  let e : Embedding E C :=
    inclusion C (↑S : Set W) hclosed
  exact h (Z := ↥(↑S : Set W)) E hgen e

end LocallyGeneratedTreeCompletable

end StructuralRamsey.Structure
