import PartiteConstruction.Functional.GeneratedTreeCompletion

/-! # Generator-budget rooted witnesses for functional structures

For function languages the union of a finite side test with a gluing root need
not itself be closed.  The correct analogue of the relational rooted-witness
lemma therefore takes the function-closure of that union.

The closure is still generated by the chosen side vertices together with the
whole root.  Thus a generator-local hypothesis at
`n + |Root|` yields a tree witness for the side in which an irreducible root
is represented by an actual embedding.
-/

namespace StructuralRamsey.Structure.LocallyGeneratedTreeCompletable

universe u v

variable {L : Language.{u}}
variable {VB H X E : Type v}
variable {Base : Structure L VB}
variable {Core : Structure L X}
variable {Root : Structure L H}
variable {Side : Structure L E}

/-- Test a finite embedded side together with the whole irreducible root.

The function-closure of the two ranges costs only the number of named
generators, not the cardinality of the closure.  The resulting local
homomorphism-embedding is an actual embedding on the irreducible root. -/
theorem rootedWitness
    [Finite H] [Finite E] [Finite X]
    (hRoot : Root.Irreducible)
    (eRoot : Embedding Root Core)
    (eSide : Embedding Side Core)
    (n : ℕ)
    (hSideCard : Nat.card E ≤ n)
    (hCore :
      LocallyGeneratedTreeCompletable
        Base Core (n + Nat.card H)) :
    ∃ (Y : Type v) (T : Structure L Y),
      TreeAmalgam Base Y T ∧
      ∃ p : E → Y,
        Side.IsHomomorphismEmbedding T p ∧
        ∃ tRoot : Embedding Root T,
          ∀ x d, eSide x = eRoot d → p x = tRoot d := by
  classical
  letI : Fintype H := Fintype.ofFinite H
  letI : Fintype E := Fintype.ofFinite E

  let G : Finset X :=
    (Finset.univ.image eSide) ∪ (Finset.univ.image eRoot)
  let Hset : Set X := Core.functionClosure (↑G : Set X)
  let Hull : Structure L Hset :=
    Core.induce Hset (Core.functionClosure_isClosed (↑G : Set X))
  let inc : Embedding Hull Core :=
    inclusion Core Hset (Core.functionClosure_isClosed (↑G : Set X))

  have hSideRange : ∀ x : E, ∃ z : Hset, eSide x = inc z := by
    intro x
    have hxG : eSide x ∈ G := by
      apply Finset.mem_union_left
      exact Finset.mem_image.mpr ⟨x, Finset.mem_univ x, rfl⟩
    have hxH : eSide x ∈ Hset :=
      Core.subset_functionClosure (↑G : Set X) (by
        simpa using hxG)
    exact ⟨⟨eSide x, hxH⟩, rfl⟩

  have hRootRange : ∀ d : H, ∃ z : Hset, eRoot d = inc z := by
    intro d
    have hdG : eRoot d ∈ G := by
      apply Finset.mem_union_right
      exact Finset.mem_image.mpr ⟨d, Finset.mem_univ d, rfl⟩
    have hdH : eRoot d ∈ Hset :=
      Core.subset_functionClosure (↑G : Set X) (by
        simpa using hdG)
    exact ⟨⟨eRoot d, hdH⟩, rfl⟩

  let iSide : Embedding Side Hull :=
    eSide.factorThroughClosedRange inc hSideRange
  let iRoot : Embedding Root Hull :=
    eRoot.factorThroughClosedRange inc hRootRange

  have hGcard : G.card ≤ n + Nat.card H := by
    calc
      G.card ≤
          (Finset.univ.image eSide).card +
            (Finset.univ.image eRoot).card :=
        Finset.card_union_le _ _
      _ ≤ Fintype.card E + Fintype.card H := by
        exact Nat.add_le_add
          (by
            simpa using
              (Finset.card_image_le
                (s := (Finset.univ : Finset E)) (f := eSide)))
          (by
            simpa using
              (Finset.card_image_le
                (s := (Finset.univ : Finset H)) (f := eRoot)))
      _ ≤ n + Nat.card H := by
        simpa only [Nat.card_eq_fintype_card] using
          Nat.add_le_add_right hSideCard (Nat.card H)

  have hHullGen :
      Hull.GeneratedByAtMost (n + Nat.card H) := by
    have h0 := functionClosure_finset_generatedByAtMost Core G
    exact h0.mono hGcard

  obtain ⟨Y, T, hTree, f, hf⟩ :=
    hCore Hull hHullGen inc

  obtain ⟨tRoot, htRoot⟩ :=
    hf.2 Root hRoot iRoot

  let p : E → Y := f ∘ iSide
  have hp : Side.IsHomomorphismEmbedding T p :=
    hf.comp iSide.isHomomorphismEmbedding

  refine ⟨Y, T, hTree, p, hp, tRoot, ?_⟩
  intro x d hxd
  calc
    p x = f (iSide x) := rfl
    _ = f (iRoot d) := by
      apply congrArg f
      apply inc.injective
      calc
        inc (iSide x) = eSide x :=
          Embedding.factorThroughClosedRange_spec
            eSide inc hSideRange x
        _ = eRoot d := hxd
        _ = inc (iRoot d) :=
          (Embedding.factorThroughClosedRange_spec
            eRoot inc hRootRange d).symm
    _ = tRoot d := (htRoot d).symm

end StructuralRamsey.Structure.LocallyGeneratedTreeCompletable
