import PartiteConstruction.Functional.ProjectedHistoryTreeCompletion
import PartiteConstruction.Functional.ClosedGeneratorRank

/-! # The zero-generator functional history invariant

In a positive-arity function language the function-closure of the empty set is
empty.  Hence every genuine closed test generated by zero vertices has empty
carrier.

If Base embeds into the ambient Ramsey witness D, nullary relations on the
empty test agree with Base automatically.  Factoring the empty inclusion
through that Base-copy therefore gives a full embedding into the one-copy
Base-tree.  All projected histories and partial A-intersection requests are
then vacuous on the source test.

This is the rank-zero starting point for the closure-aware functional
sparsening iteration.
-/

namespace StructuralRamsey.Structure.FunctionalProjectedHistoryTreeLike

universe u v

variable {L : Language.{u}}
variable {U V P : Type v}
variable {A : Structure L U}
variable {Base : Structure L V}
variable {D : Structure L P}

/-- Identity projected-history coherence at generator rank zero.

The embedding Base -> D is used only to synchronize nullary relations on the
empty induced structure; positive arity ensures that no function value is
generated from the empty carrier. -/
theorem identity_zero_of_embeddings
    (hL : L.PositiveFuncArity)
    (hA : A.Irreducible)
    (eAB : Embedding A Base)
    (eBD : Embedding Base D) :
    FunctionalProjectedHistoryTreeLike
      (A := A) (D := D) (C := D) (Base := Base) id 0 := by
  classical
  intro S hS hgen history
  let Small := D.induce (↑S : Set P) hS
  letI : IsEmpty (↥(↑S : Set P)) :=
    GeneratedByAtMost.isEmpty_of_zero hL hgen
  let inc : Embedding Small D :=
    inclusion D (↑S : Set P) hS
  have hrange :
      ∀ x : ↥(↑S : Set P), ∃ b : V, inc x = eBD b := by
    intro x
    exact isEmptyElim x
  let eSmall : Embedding Small Base :=
    inc.factorThroughClosedRange eBD hrange
  have hTree : TreeAmalgam Base V Base :=
    TreeAmalgam.copy (Embedding.id Base) (by
      intro b
      exact ⟨b, rfl⟩)
  let f : ↥(↑S : Set P) → V := eSmall
  have hf : Small.IsHomomorphismEmbedding Base f :=
    eSmall.isHomomorphismEmbedding
  have hPart :
      FunctionalProjectedPartialIntersections
        (A := A) (D := D) (C := D) (T := Base) id S f := by
    intro beta H hH e hproj hRange
    let eHT : Embedding (A.induce H hH) Base :=
      eAB.comp (inclusion A H hH)
    refine ⟨eHT, ?_, ?_⟩
    · intro x
      exact isEmptyElim
        (⟨e x, hRange x⟩ : ↥(↑S : Set P))
    · refine ⟨U, A, hA, eAB, ?_⟩
      intro x
      exact ⟨x.1, rfl⟩
  have hHist :
      FunctionalRespectsProjectedHistory id S f history := by
    intro K hK x y hxy
    exact isEmptyElim x
  exact ⟨V, Base, hTree, f, hf, hPart, hHist⟩

end StructuralRamsey.Structure.FunctionalProjectedHistoryTreeLike
