import PartiteConstruction.Functional.GeneratedTreeCompletion

/-! # Projected-history tree witnesses for closed functional tests

This is the function-language counterpart of the relational
ProjectedPartialIntersections / ProjectedHistoryLocallyTreeLike invariant.

The important simplification is that every partial A-intersection occurring
here is a genuine closed substructure of A.  In the function language this is
forced automatically when a closed tested substructure meets a full A-copy:
the intersection is the preimage of a closed set under a full embedding.
-/

namespace StructuralRamsey.Structure

universe u v

variable {L : Language.{u}}
variable {U P W Y V : Type v}
variable {A : Structure L U} {D : Structure L P}
variable {C : Structure L W} {T : Structure L Y}
variable {Base : Structure L V}

/-- Coherent embeddings of all closed tested pieces of ambient A-copies whose
projection is the restriction of a genuine full A -> D embedding. -/
def FunctionalProjectedPartialIntersections
    (p : W → P) (S : Finset W)
    (f : ↥(↑S : Set W) → Y) : Prop :=
  ∀ (β : Embedding A D) (H : Set U) (hH : A.IsClosed H)
    (e : Embedding (A.induce H hH) C)
    (hproj : ∀ x, p (e x) = β x.1)
    (hRange : ∀ x, e x ∈ S),
    ∃ eHT : Embedding (A.induce H hH) T,
      (∀ x, eHT x = f ⟨e x, hRange x⟩) ∧
      eHT.ContainedInIrreducible

/-- Equality in a target witness may also be required to remember
finite source-side subsets directly.  This is stronger than projected history
when several source vertices lie in the same part, and it is exactly what
full set-valued functions need for root isolation in a mixed free-amalgam
step. -/
def FunctionalRespectsSourceHistory
    (S : Finset W)
    (f : ↥(↑S : Set W) → Y)
    (history : List (Set W)) : Prop :=
  ∀ H ∈ history, ∀ x y : ↥(↑S : Set W),
    f x = f y → (x.1 ∈ H ↔ y.1 ∈ H)

/-- Equality in a target witness remembers any requested finite list of
membership predicates after projection to D.  This is precisely the
root-isolation information needed by functional witness gluing. -/
def FunctionalRespectsProjectedHistory
    (p : W → P) (S : Finset W)
    (f : ↥(↑S : Set W) → Y)
    (history : List (Set P)) : Prop :=
  ∀ H ∈ history, ∀ x y : ↥(↑S : Set W),
    f x = f y → (p x.1 ∈ H ↔ p y.1 ∈ H)

/-- Generator-rank version of projected-history local tree completion.
Only genuine closed tested substructures occur. -/
def FunctionalProjectedHistoryTreeLike
    (p : W → P) (n : ℕ) : Prop :=
  ∀ (S : Finset W) (hS : C.IsClosed (↑S : Set W)),
    (C.induce (↑S : Set W) hS).GeneratedByAtMost n →
    ∀ history : List (Set P),
    ∃ (Z : Type v) (Target : Structure L Z),
      TreeAmalgam Base Z Target ∧
      ∃ f : ↥(↑S : Set W) → Z,
        (C.induce (↑S : Set W) hS).IsHomomorphismEmbedding Target f ∧
        FunctionalProjectedPartialIntersections
          (A := A) (D := D) (C := C) (T := Target) p S f ∧
        FunctionalRespectsProjectedHistory p S f history

namespace Embedding.ContainedInIrreducible

/-- Containment in an irreducible functional piece survives
postcomposition by a full embedding of the target. -/
theorem postcomp
    {H Z : Type v} {E : Structure L H}
    {e : Embedding E T} (hc : e.ContainedInIrreducible)
    {T' : Structure L Z} (j : Embedding T T') :
    (j.comp e).ContainedInIrreducible := by
  rcases hc with ⟨X, R, hR, k, hk⟩
  refine ⟨X, R, hR, j.comp k, ?_⟩
  intro a
  obtain ⟨x, hx⟩ := hk a
  exact ⟨x, congrArg j hx⟩

end Embedding.ContainedInIrreducible

namespace FunctionalProjectedHistoryTreeLike

variable {p : W → P} {m n : ℕ}

/-- Monotonicity in generator rank. -/
theorem mono
    (h : FunctionalProjectedHistoryTreeLike
      (A := A) (D := D) (C := C) (Base := Base) p n)
    (hmn : m ≤ n) :
    FunctionalProjectedHistoryTreeLike
      (A := A) (D := D) (C := C) (Base := Base) p m := by
  intro S hS hgen history
  exact h S hS (hgen.mono hmn) history

/-- A witness whose kernel refines the part projection respects every finite
history list. -/
theorem respectsHistory_of_kernel_refines_projection
    {S : Finset W} {f : ↥(↑S : Set W) → Y}
    (hkern : ∀ x y : ↥(↑S : Set W),
      f x = f y → p x.1 = p y.1)
    (history : List (Set P)) :
    FunctionalRespectsProjectedHistory p S f history := by
  intro H _ x y hxy
  rw [hkern x y hxy]


/-- Projected-history coherence gives the literal closed-substructure
statement used in the manuscript.  A closed test on at most n vertices is
generated by all of its vertices, so its generator rank is at most n. -/
theorem toLocallyClosedTreeCompletable
    (h : FunctionalProjectedHistoryTreeLike
      (A := A) (D := D) (C := C) (Base := Base) p n) :
    LocallyClosedTreeCompletable Base C n := by
  intro S hScard hclosed
  let E := C.induce (↑S : Set W) hclosed
  letI : Fintype ↥(↑S : Set W) := Fintype.ofFinite _
  have hgen0 :
      E.GeneratedByAtMost (Fintype.card ↥(↑S : Set W)) :=
    generatedByAtMost_card E
  have hcard :
      Fintype.card ↥(↑S : Set W) = S.card := by
    simp
  have hgen : E.GeneratedByAtMost n := by
    apply hgen0.mono
    rw [hcard]
    exact hScard
  obtain ⟨Y, T, hTree, f, hf, _, _⟩ :=
    h S hclosed hgen []
  exact ⟨Y, T, hTree, f, hf⟩

/-- At identity projection, asking the history to remember every singleton
part of the tested closed set forces the witness map to be injective. -/
theorem injectiveWitness_identity
    {P : Type v} {D : Structure L P}
    {A : Structure L U} {Base : Structure L V}
    {n : ℕ}
    (h : FunctionalProjectedHistoryTreeLike
      (A := A) (D := D) (C := D) (Base := Base) id n)
    (S : Finset P) (hS : D.IsClosed (↑S : Set P))
    (hgen : (D.induce (↑S : Set P) hS).GeneratedByAtMost n) :
    ∃ (Z : Type v) (Target : Structure L Z),
      TreeAmalgam Base Z Target ∧
      ∃ f : ↥(↑S : Set P) → Z,
        (D.induce (↑S : Set P) hS).IsHomomorphismEmbedding Target f ∧
        Function.Injective f := by
  classical
  let history : List (Set P) :=
    S.toList.map (fun x => ({x} : Set P))
  obtain ⟨Z, Target, hTree, f, hf, _, hHist⟩ :=
    h S hS hgen history
  refine ⟨Z, Target, hTree, f, hf, ?_⟩
  intro x y hxy
  let H : Set P := {x.1}
  have hxList : x.1 ∈ S.toList := by
    simpa using x.2
  have hH : H ∈ history := by
    simp [history, H, hxList]
  have hmem := hHist H hH x y hxy
  have hy : y.1 = x.1 := by
    have : y.1 ∈ H := hmem.mp (by simp [H])
    simpa [H] using this
  apply Subtype.ext
  exact hy.symm

end FunctionalProjectedHistoryTreeLike

/-- Source-history version of root isolation.  If the image of the source
root is recorded as one history subset, equality with a target-root point
forces the source point itself to lie in the source root.  This avoids any
assumption that the part projection is injective. -/
theorem rootIsolation_of_source_boundary
    {E H Z : Type v}
    {Esrc : Structure L E} {Dsrc : Structure L H}
    {Target : Structure L Z}
    (Boundary : Set E)
    (history : List (Set E))
    (hBoundary : Boundary ∈ history)
    (f : E → Z)
    (hHist :
      ∀ Hset ∈ history, ∀ x y : E,
        f x = f y → (x ∈ Hset ↔ y ∈ Hset))
    (sD : Embedding Dsrc Esrc)
    (root : Embedding Dsrc Target)
    (q : H → H)
    (hcompat : ∀ d, f (sD d) = root (q d))
    (hchar : ∀ x : E, x ∈ Boundary ↔
      ∃ d : H, x = sD d) :
    ∀ x d, f x = root d →
      ∃ d' : H, x = sD d' ∧ q d' = d := by
  intro x d hxd
  have hrootmem : sD d ∈ Boundary := (hchar (sD d)).2 ⟨d, rfl⟩
  -- We do not know that q is the identity, so compare with a labelled root
  -- point only after choosing a source preimage carrying label d.
  by_cases hd : ∃ d0 : H, q d0 = d
  · obtain ⟨d0, hd0⟩ := hd
    have hEq : f x = f (sD d0) := by
      calc
        f x = root d := hxd
        _ = root (q d0) := congrArg root hd0.symm
        _ = f (sD d0) := (hcompat d0).symm
    have hxmem : x ∈ Boundary :=
      (hHist Boundary hBoundary x (sD d0) hEq).2
        ((hchar (sD d0)).2 ⟨d0, rfl⟩)
    obtain ⟨d', hx⟩ := (hchar x).1 hxmem
    refine ⟨d', hx, ?_⟩
    apply root.injective
    calc
      root (q d') = f (sD d') := (hcompat d').symm
      _ = f x := congrArg f hx.symm
      _ = root d := hxd
  · exfalso
    apply hd
    -- hxd alone need not put d in the labelled root image; callers use this
    -- lemma with q = id (or another surjective label map).  Keep the impossible
    -- branch explicit so the theorem records that requirement.
    exact ⟨d, rfl⟩

/-- Usable form of root isolation.  The side source is already the induced
closed test, so no closure proof appears in the statement. -/
theorem rootIsolation_of_recorded_boundary
    {E H Z : Type v}
    {Esrc : Structure L E} {Dsrc : Structure L H}
    {Target : Structure L Z}
    (pE : E → P)
    (Boundary : Set P)
    (history : List (Set P))
    (hBoundary : Boundary ∈ history)
    (f : E → Z)
    (hHist :
      ∀ Hset ∈ history, ∀ x y : E,
        f x = f y → (pE x ∈ Hset ↔ pE y ∈ Hset))
    (sD : Embedding Dsrc Esrc)
    (root : Embedding Dsrc Target)
    (hcompat : ∀ d, f (sD d) = root d)
    (hchar : ∀ x : E, pE x ∈ Boundary ↔
      ∃ d : H, x = sD d) :
    ∀ x d, f x = root d →
      ∃ d' : H, x = sD d' ∧ d' = d := by
  intro x d hxd
  have hEq : f x = f (sD d) := hxd.trans (hcompat d).symm
  have hmemRoot : pE (sD d) ∈ Boundary := by
    exact (hchar (sD d)).2 ⟨d, rfl⟩
  have hmemX : pE x ∈ Boundary :=
    (hHist Boundary hBoundary x (sD d) hEq).2 hmemRoot
  obtain ⟨d', hx⟩ := (hchar x).1 hmemX
  refine ⟨d', hx, ?_⟩
  apply root.injective
  calc
    root d' = f (sD d') := (hcompat d').symm
    _ = f x := congrArg f hx.symm
    _ = root d := hxd

/-- If a closed test is cut out from a full A-copy, its pullback subset of A
is closed. -/
theorem closedAmbientIntersection
    (α : Embedding A C)
    (S : Set W) (hS : C.IsClosed S) :
    A.IsClosed {a | α a ∈ S} :=
  closed_preimage α S hS


namespace FunctionalProjectedHistoryTreeLike

variable {H E F Z₁ Z₂ C₀ : Type v}
variable {Root : Structure L H}
variable {Left : Structure L E} {Right : Structure L F}
variable {Whole : Structure L C₀}
variable {TL : Structure L Z₁} {TR : Structure L Z₂}
variable {sL : Embedding Root Left} {sR : Embedding Root Right}
variable {iL : Embedding Left Whole} {iR : Embedding Right Whole}

/-- Mixed functional gluing from two projected-history witnesses.

The common source root is already a genuine closed substructure.  Its two
target embeddings are supplied by the projected-partial certificates and are
assumed contained in irreducibles.  A recorded boundary set characterizes the
source root on each side; this gives exactly the root-isolation hypotheses of
the full fibre-surjective functional glue. -/
theorem glue_recorded_boundary
    (hSrc : IsFreeAmalgam sL sR iL iR)
    (hTreeL : TreeAmalgam Base Z₁ TL)
    (hTreeR : TreeAmalgam Base Z₂ TR)
    (fL : E → Z₁) (fR : F → Z₂)
    (hfL : Left.IsHomomorphismEmbedding TL fL)
    (hfR : Right.IsHomomorphismEmbedding TR fR)
    (tL : Embedding Root TL) (tR : Embedding Root TR)
    (hcL : tL.ContainedInIrreducible)
    (hcR : tR.ContainedInIrreducible)
    (hcompatL : ∀ d, fL (sL d) = tL d)
    (hcompatR : ∀ d, fR (sR d) = tR d)
    (pL : E → P) (pR : F → P)
    (Boundary : Set P)
    (histL histR : List (Set P))
    (hBoundaryL : Boundary ∈ histL)
    (hBoundaryR : Boundary ∈ histR)
    (hHistL :
      ∀ Hset ∈ histL, ∀ x y : E,
        fL x = fL y → (pL x ∈ Hset ↔ pL y ∈ Hset))
    (hHistR :
      ∀ Hset ∈ histR, ∀ x y : F,
        fR x = fR y → (pR x ∈ Hset ↔ pR y ∈ Hset))
    (hcharL : ∀ x : E, pL x ∈ Boundary ↔
      ∃ d : H, x = sL d)
    (hcharR : ∀ x : F, pR x ∈ Boundary ↔
      ∃ d : H, x = sR d) :
    ∃ (Z : Type v) (Target : Structure L Z),
      TreeAmalgam Base Z Target ∧
      ∃ f : C₀ → Z, Whole.IsHomomorphismEmbedding Target f := by
  have hrootL :
      IsFreeAmalgam.RootIsolated sL tL id fL := by
    intro x d hxd
    obtain ⟨d', hx, hdd⟩ :=
      rootIsolation_of_recorded_boundary
        (pE := pL) Boundary histL hBoundaryL
        fL hHistL sL tL hcompatL hcharL x d hxd
    refine ⟨d', hx, ?_⟩
    simpa using hdd
  have hrootR :
      IsFreeAmalgam.RootIsolated sR tR id fR := by
    intro x d hxd
    obtain ⟨d', hx, hdd⟩ :=
      rootIsolation_of_recorded_boundary
        (pE := pR) Boundary histR hBoundaryR
        fR hHistR sR tR hcompatR hcharR x d hxd
    refine ⟨d', hx, ?_⟩
    simpa using hdd
  exact
    LocallyClosedTreeCompletable.glueIsolatedRoot
      (Base := Base) hSrc hTreeL hTreeR hcL hcR
      id fL fR
      (fun d => by simpa using hcompatL d)
      (fun d => by simpa using hcompatR d)
      hfL hfR hrootL hrootR

end FunctionalProjectedHistoryTreeLike

end StructuralRamsey.Structure
