import PartiteConstruction.Functional.GeneratedTreeCompletion
import PartiteConstruction.Functional.WeakInvariant
import PartiteConstruction.Functional.FibreExactness

/-! # Unary EHN projections are already full on closed structures

For unary set-valued functions there is no higher-arity synchronization
obstruction.  The closed hull generated by one point is irreducible: it is the
closed hull of the weak image of a one-point irreducible structure.  Hence an
EHN projection is a full embedding on that hull.  Every unary fibre over the
point is contained in the hull, so the projection is fibre-surjective there.

Consequently an EHN homomorphism-embedding in a unary language is an ordinary
(full, fibre-surjective) homomorphism-embedding.  If the target A embeds into
the tree base B, every closed finite test already completes into one copy of B.
-/

namespace StructuralRamsey

universe u v

namespace Language

/-- All function symbols are unary. -/
def UnaryFuncArity (L : Language.{u}) : Prop :=
  ∀ F, L.funcArity F = 1

end Language

namespace Structure

variable {L : Language.{u}}
variable {U V W : Type v}

/-- The closed hull generated by one point is irreducible.  In a free
decomposition the generator belongs to one side, and the image of that side
is closed, hence it contains the whole generated hull. -/
theorem onePointClosure_irreducible
    (C : Structure L W) (c : W) :
    (C.induce
      (C.functionClosure (Set.range (fun _ : W => c)))
      (C.functionClosure_isClosed
        (Set.range (fun _ : W => c)))).Irreducible := by
  classical
  let q :
      W → C.functionClosure (Set.range (fun _ : W => c)) :=
    closureLift C (fun _ : W => c)
  have hgen :
      (C.induce
        (C.functionClosure (Set.range (fun _ : W => c)))
        (C.functionClosure_isClosed
          (Set.range (fun _ : W => c)))).Generates q := by
    simpa [q] using
      (closureLift_generates C (fun _ : W => c))
  rw [irreducible_iff_noProperFreeDecomposition]
  rintro ⟨d⟩
  rcases d.free.covers (q c) with hleft | hright
  · rcases hleft with ⟨x, hx⟩
    apply d.leftProper
    intro z
    apply hgen (Set.range d.leftIn) d.leftIn.range_isClosed
    intro a
    refine ⟨x, ?_⟩
    have hqa : q a = q c := by
      apply Subtype.ext
      rfl
    exact (hqa.trans hx).symm
  · rcases hright with ⟨x, hx⟩
    apply d.rightProper
    intro z
    apply hgen (Set.range d.rightIn) d.rightIn.range_isClosed
    intro a
    refine ⟨x, ?_⟩
    have hqa : q a = q c := by
      apply Subtype.ext
      rfl
    exact (hqa.trans hx).symm

/-- For unary functions, an EHN projection preserves complete function fibres
onto the target, hence is a full homomorphism. -/
theorem IsEHNHomomorphismEmbedding.isHomomorphism_of_unary
    (hL : L.UnaryFuncArity)
    {C : Structure L W} {A : Structure L U}
    {p : W → U}
    (hp : C.IsEHNHomomorphismEmbedding A p) :
    C.IsHomomorphism A p := by
  apply hp.isHomomorphism_of_domainReflection
  intro F x htgt
  obtain ⟨y, hy⟩ := htgt
  have hAr : L.funcArity F = 1 := hL F
  have hpos : 0 < L.funcArity F := by
    omega
  let i0 : Fin (L.funcArity F) := ⟨0, hpos⟩
  have hidx : ∀ i : Fin (L.funcArity F), i = i0 := by
    intro i
    apply Fin.ext
    change i.val = i0.val
    change i.val = 0
    omega
  let c : W := x i0
  let q0 : W → W := fun _ => c
  let Hset : Set W := C.functionClosure (Set.range q0)
  have hHirr :
      (C.induce Hset
        (C.functionClosure_isClosed (Set.range q0))).Irreducible := by
    simpa [Hset, q0, c] using
      (onePointClosure_irreducible C c)
  let H : Structure L Hset :=
    C.induce Hset (C.functionClosure_isClosed (Set.range q0))
  let inc : Embedding H C :=
    inclusion C Hset (C.functionClosure_isClosed (Set.range q0))
  obtain ⟨g, hg⟩ := hp.2 H (by simpa [H] using hHirr) inc
  have hcH : c ∈ Hset := by
    apply C.subset_functionClosure (Set.range q0)
    exact ⟨c, rfl⟩
  let cH : Hset := ⟨c, hcH⟩
  let xH : Fin (L.funcArity F) → Hset := fun _ => cH
  have hxC : Subtype.val ∘ xH = x := by
    funext i
    rw [hidx i]
    rfl
  have hgargs : g ∘ xH = p ∘ x := by
    funext i
    rw [hidx i]
    change g cH = p c
    exact hg cH
  have hy' : y ∈ A.func F (g ∘ xH) := by
    rw [hgargs]
    exact hy
  have himg : y ∈ imageSet g (H.func F xH) := by
    rw [g.map_func F xH]
    exact hy'
  rcases himg with ⟨z, hz, _⟩
  refine ⟨z.1, ?_⟩
  change z.1 ∈ C.func F (Subtype.val ∘ xH) at hz
  rw [hxC] at hz
  exact hz

/-- Unary EHN projections are ordinary full homomorphism-embeddings. -/
theorem IsEHNHomomorphismEmbedding.toFull_of_unary
    (hL : L.UnaryFuncArity)
    {C : Structure L W} {A : Structure L U}
    {p : W → U}
    (hp : C.IsEHNHomomorphismEmbedding A p) :
    C.IsHomomorphismEmbedding A p :=
  ⟨hp.isHomomorphism_of_unary hL, hp.2⟩

/-- In a unary language, an EHN projection into A followed by A ↪ Base gives
generator-local tree completion at every depth, witnessed by one Base-copy. -/
theorem LocallyGeneratedTreeCompletable.of_ehn_unary
    (hL : L.UnaryFuncArity)
    {C : Structure L W} {A : Structure L U} {Base : Structure L V}
    {p : W → U}
    (hp : C.IsEHNHomomorphismEmbedding A p)
    (eAB : Embedding A Base)
    (n : ℕ) :
    LocallyGeneratedTreeCompletable Base C n := by
  have hCB :
      C.IsHomomorphismEmbedding Base (eAB ∘ p) :=
    eAB.isHomomorphismEmbedding.comp (hp.toFull_of_unary hL)
  intro Z _ E _ e
  let q : Z → V := (eAB ∘ p) ∘ e
  have hq : E.IsHomomorphismEmbedding Base q := by
    exact hCB.comp e.isHomomorphismEmbedding
  have hTree : TreeAmalgam Base V Base :=
    TreeAmalgam.copy (Embedding.id Base) (by
      intro b
      exact ⟨b, rfl⟩)
  exact ⟨V, Base, hTree, q, hq⟩

end Structure
end StructuralRamsey
