import PartiteConstruction.Functional.GeneratedTreeCompletion
import PartiteConstruction.Functional.WeakInvariant

/-! # Unary EHN projections are already full on closed structures

For unary set-valued functions there is no higher-arity synchronization
obstruction.  The closed hull generated by one point is irreducible: it is the
closed hull of the weak image of a one-point irreducible structure.  Hence an
EHN projection is a full embedding on that hull.  Every unary fibre over the
point is contained in the hull, so the projection is fibre-surjective there.

Consequently an EHN homomorphism-embedding in a unary language is an ordinary
(full, fibre-surjective) homomorphism-embedding.  If the target A embeds into
the tree base B, every closed finite test already completes into one copy of B.
-/

namespace StructuralRamsey

universe u v

namespace Language

/-- All function symbols are unary. -/
def UnaryFuncArity (L : Language.{u}) : Prop :=
  ∀ F, L.funcArity F = 1

end Language

namespace Structure

variable {L : Language.{u}}
variable {U V W : Type v}

/-- A singleton carrier living in the ambient carrier universe. -/
inductive One : Type v where
  | star

instance : Subsingleton (One) where
  allEq := by
    intro x y
    cases x
    cases y
    rfl

/-- The empty-incidence one-point structure, used only as a generator for a
one-generated closed hull. -/
def pointSkeleton (L : Language.{u}) : Structure L One where
  rel _ _ := False
  func _ _ := ∅

theorem pointSkeleton_irreducible :
    (pointSkeleton (L := L)).Irreducible := by
  intro H E F C Dsrc Esrc Fsrc Csrc sE sF iE iF hfree e
  rcases hfree.covers (e One.star) with ⟨x, hx⟩ | ⟨x, hx⟩
  · refine Or.inl ?_
    intro a
    refine ⟨x, ?_⟩
    have ha : a = One.star := Subsingleton.elim _ _
    simpa [ha] using hx
  · refine Or.inr ?_
    intro a
    refine ⟨x, ?_⟩
    have ha : a = One.star := Subsingleton.elim _ _
    simpa [ha] using hx

theorem pointSkeleton_weak
    (C : Structure L W) (c : W) :
    (pointSkeleton (L := L)).IsWeakHomomorphism C
      (fun _ : One => c) := by
  constructor
  · intro R x hx
    exact False.elim hx
  · intro F x y hy
    change False at hy
    exact hy.elim

/-- The closed hull generated by one point is irreducible. -/
theorem onePointClosure_irreducible
    (C : Structure L W) (c : W) :
    (C.induce
      (C.functionClosure (Set.range (fun _ : One => c)))
      (C.functionClosure_isClosed
        (Set.range (fun _ : One => c)))).Irreducible := by
  exact pointSkeleton_irreducible.functionClosure_weakImage
    (pointSkeleton_weak C c)

/-- For unary functions, an EHN projection preserves complete function fibres
onto the target, hence is a full homomorphism. -/
theorem IsEHNHomomorphismEmbedding.isHomomorphism_of_unary
    (hL : L.UnaryFuncArity)
    {C : Structure L W} {A : Structure L U}
    {p : W → U}
    (hp : C.IsEHNHomomorphismEmbedding A p) :
    C.IsHomomorphism A p := by
  constructor
  · exact hp.1.1
  · intro F x
    ext y
    constructor
    · rintro ⟨z, hz, rfl⟩
      exact hp.1.2 F x z hz
    · intro hy
      have hAr : L.funcArity F = 1 := hL F
      have hpos : 0 < L.funcArity F := by
        rw [hAr]
        decide
      let i0 : Fin (L.funcArity F) := ⟨0, hpos⟩
      have hidx : ∀ i : Fin (L.funcArity F), i = i0 := by
        intro i
        apply Fin.ext
        change i.val = i0.val
        have hi : i.val < 1 := by
          omega
        change i.val = 0
        omega
      let c : W := x i0
      let q : One → W := fun _ => c
      let Hset : Set W := C.functionClosure (Set.range q)
      have hHclosed : C.IsClosed Hset :=
        C.functionClosure_isClosed (Set.range q)
      let H : Structure L Hset := C.induce Hset hHclosed
      have hHirr : H.Irreducible := by
        change
          (C.induce Hset
            (C.functionClosure_isClosed (Set.range q))).Irreducible
        simpa [Hset, q, c] using
          (onePointClosure_irreducible C c)
      let inc : Embedding H C := inclusion C Hset hHclosed
      obtain ⟨g, hg⟩ := hp.2 H hHirr inc
      have hcH : c ∈ Hset := by
        apply C.subset_functionClosure (Set.range q)
        exact ⟨One.star, rfl⟩
      let cH : Hset := ⟨c, hcH⟩
      let xH : Fin (L.funcArity F) → Hset := fun _ => cH
      have hxC : Subtype.val ∘ xH = x := by
        funext i
        rw [hidx i]
        rfl
      have hgargs : g ∘ xH = p ∘ x := by
        funext i
        rw [hidx i]
        change g cH = p c
        exact hg cH
      have hy' : y ∈ A.func F (g ∘ xH) := by
        rw [hgargs]
        exact hy
      have himg : y ∈ imageSet g (H.func F xH) := by
        rw [g.map_func F xH]
        exact hy'
      rcases himg with ⟨z, hz, hzy⟩
      refine ⟨z.1, ?_, ?_⟩
      · change z.1 ∈ C.func F (Subtype.val ∘ xH) at hz
        rw [hxC] at hz
        exact hz
      · calc
          p z.1 = g z := (hg z).symm
          _ = y := hzy

/-- Unary EHN projections are ordinary full homomorphism-embeddings. -/
theorem IsEHNHomomorphismEmbedding.toFull_of_unary
    (hL : L.UnaryFuncArity)
    {C : Structure L W} {A : Structure L U}
    {p : W → U}
    (hp : C.IsEHNHomomorphismEmbedding A p) :
    C.IsHomomorphismEmbedding A p :=
  ⟨hp.isHomomorphism_of_unary hL, hp.2⟩

/-- In a unary language, an EHN projection into A followed by A ↪ Base gives
generator-local tree completion at every depth, witnessed by one Base-copy. -/
theorem LocallyGeneratedTreeCompletable.of_ehn_unary
    (hL : L.UnaryFuncArity)
    {C : Structure L W} {A : Structure L U} {Base : Structure L V}
    {p : W → U}
    (hp : C.IsEHNHomomorphismEmbedding A p)
    (eAB : Embedding A Base)
    (n : ℕ) :
    LocallyGeneratedTreeCompletable Base C n := by
  have hCB :
      C.IsHomomorphismEmbedding Base (eAB ∘ p) :=
    eAB.isHomomorphismEmbedding.comp (hp.toFull_of_unary hL)
  intro Z _ E _ e
  let q : Z → V := (eAB ∘ p) ∘ e
  have hq : E.IsHomomorphismEmbedding Base q := by
    exact hCB.comp e.isHomomorphismEmbedding
  have hTree : TreeAmalgam Base V Base :=
    TreeAmalgam.copy (Embedding.id Base) (by
      intro b
      exact ⟨b, rfl⟩)
  exact ⟨V, Base, hTree, q, hq⟩

end Structure
end StructuralRamsey
