import PartiteConstruction.Functional.GeneratedTreeCompletion
import PartiteConstruction.Functional.WeakInvariant

/-! # Unary EHN projections are already full on closed structures

For unary set-valued functions there is no higher-arity synchronization
obstruction.  The closed hull generated by one point is irreducible: it is the
closed hull of the weak image of a one-point irreducible structure.  Hence an
EHN projection is a full embedding on that hull.  Every unary fibre over the
point is contained in the hull, so the projection is fibre-surjective there.

Consequently an EHN homomorphism-embedding in a unary language is an ordinary
(full, fibre-surjective) homomorphism-embedding.  If the target A embeds into
the tree base B, every closed finite test already completes into one copy of B.
-/

namespace StructuralRamsey

universe u v

namespace Language

/-- All function symbols are unary. -/
def UnaryFuncArity (L : Language.{u}) : Prop :=
  ∀ F, L.funcArity F = 1

end Language

namespace Structure

variable {L : Language.{u}}
variable {U V W : Type v}

/-- The empty-incidence one-point structure, used only as a generator for a
one-generated closed hull. -/
def pointSkeleton (L : Language.{u}) : Structure L Unit where
  rel _ _ := False
  func _ _ := ∅

theorem pointSkeleton_irreducible :
    (pointSkeleton L).Irreducible := by
  intro H E F C Dsrc Esrc Fsrc Csrc sE sF iE iF hfree e
  rcases hfree.covers (e ()) with ⟨x, hx⟩ | ⟨x, hx⟩
  · refine Or.inl ?_
    intro a
    exact ⟨x, by simpa using hx⟩
  · refine Or.inr ?_
    intro a
    exact ⟨x, by simpa using hx⟩

theorem pointSkeleton_weak
    (C : Structure L W) (c : W) :
    (pointSkeleton L).IsWeakHomomorphism C (fun _ : Unit => c) := by
  constructor
  · intro R x hx
    exact False.elim hx
  · intro F x y hy
    exact Set.not_mem_empty y hy

/-- The closed hull generated by one point is irreducible. -/
theorem onePointClosure_irreducible
    (C : Structure L W) (c : W) :
    let q : Unit → W := fun _ => c
    let Hset := C.functionClosure (Set.range q)
    (C.induce Hset (C.functionClosure_isClosed (Set.range q))).Irreducible := by
  let q : Unit → W := fun _ => c
  exact pointSkeleton_irreducible.functionClosure_weakImage
    (pointSkeleton_weak C c)

/-- For unary functions, an EHN projection preserves complete function fibres
onto the target, hence is a full homomorphism. -/
theorem IsEHNHomomorphismEmbedding.isHomomorphism_of_unary
    (hL : L.UnaryFuncArity)
    {C : Structure L W} {A : Structure L U}
    {p : W → U}
    (hp : C.IsEHNHomomorphismEmbedding A p) :
    C.IsHomomorphism A p := by
  constructor
  · exact hp.1.1
  · intro F x
    rw [hL F] at x ⊢
    ext y
    constructor
    · rintro ⟨z, hz, rfl⟩
      exact hp.1.2 F x z hz
    · intro hy
      let c : W := x 0
      let q : Unit → W := fun _ => c
      let Hset : Set W := C.functionClosure (Set.range q)
      have hHclosed : C.IsClosed Hset :=
        C.functionClosure_isClosed (Set.range q)
      let H : Structure L Hset := C.induce Hset hHclosed
      have hHirr : H.Irreducible := by
        simpa [H, Hset, q, c] using onePointClosure_irreducible C c
      let inc : Embedding H C := inclusion C Hset hHclosed
      obtain ⟨g, hg⟩ := hp.2 H hHirr inc
      have hcH : c ∈ Hset := by
        apply C.subset_functionClosure (Set.range q)
        exact ⟨(), rfl⟩
      let cH : Hset := ⟨c, hcH⟩
      let xH : Fin 1 → Hset := fun _ => cH
      have hxC : Subtype.val ∘ xH = x := by
        funext i
        have hi : i = 0 := Subsingleton.elim _ _
        subst i
        rfl
      have hgargs : g ∘ xH = p ∘ x := by
        funext i
        have hi : i = 0 := Subsingleton.elim _ _
        subst i
        change g cH = p c
        exact hg cH
      have hy' : y ∈ A.func F (g ∘ xH) := by
        rw [hgargs]
        exact hy
      have himg : y ∈ imageSet g (H.func F xH) := by
        rw [g.map_func F xH]
        exact hy'
      rcases himg with ⟨z, hz, hzy⟩
      refine ⟨z.1, ?_, ?_⟩
      · change z.1 ∈ C.func F (Subtype.val ∘ xH) at hz
        rw [hxC] at hz
        exact hz
      · calc
          p z.1 = g z := (hg z).symm
          _ = y := hzy

/-- Unary EHN projections are ordinary full homomorphism-embeddings. -/
theorem IsEHNHomomorphismEmbedding.toFull_of_unary
    (hL : L.UnaryFuncArity)
    {C : Structure L W} {A : Structure L U}
    {p : W → U}
    (hp : C.IsEHNHomomorphismEmbedding A p) :
    C.IsHomomorphismEmbedding A p :=
  ⟨hp.isHomomorphism_of_unary hL, hp.2⟩

/-- In a unary language, an EHN projection into A followed by A ↪ Base gives
generator-local tree completion at every depth, witnessed by one Base-copy. -/
theorem LocallyGeneratedTreeCompletable.of_ehn_unary
    (hL : L.UnaryFuncArity)
    {C : Structure L W} {A : Structure L U} {Base : Structure L V}
    {p : W → U}
    (hp : C.IsEHNHomomorphismEmbedding A p)
    (eAB : Embedding A Base)
    (n : ℕ) :
    LocallyGeneratedTreeCompletable Base C n := by
  have hCB :
      C.IsHomomorphismEmbedding Base (eAB ∘ p) :=
    eAB.isHomomorphismEmbedding.comp (hp.toFull_of_unary hL)
  exact LocallyGeneratedTreeCompletable.pullback_homEmbedding
    hCB (LocallyGeneratedTreeCompletable.base Base n)

end Structure
end StructuralRamsey
