import PartiteConstruction.Ramsey.ClosurePictureCoordinate
import PartiteConstruction.Ramsey.ClosureAttachmentSubhistory
import PartiteConstruction.Ramsey.ClosurePictureRetraction
import PartiteConstruction.Ramsey.ClosureAttachmentFold
import PartiteConstruction.Ramsey.ClosureClosedCover
import PartiteConstruction.Ramsey.ClosureRelativeGeneratorDrop
import PartiteConstruction.Ramsey.ClosureRankOneBase
import PartiteConstruction.Ramsey.ClosureIrreducibleHulls
import PartiteConstruction.Ramsey.ClosureFreeAmalgamGenerators
import PartiteConstruction.Ramsey.ClosureProjectedRankGlue
import PartiteConstruction.Ramsey.ClosureProjectedGenerators
import PartiteConstruction.Ramsey.ClosureProjectedCompletion
import PartiteConstruction.Ramsey.ClosureProjectedBoundary
import PartiteConstruction.Ramsey.CompatibleClassCompletion
import PartiteConstruction.Ramsey.CopywiseRamseyTransfer
import PartiteConstruction.Ramsey.ClosureLocalCompletionRank
import PartiteConstruction.Ramsey.ClosureDescription2019
import PartiteConstruction.Functional.FreeAmalgamClosed
import PartiteConstruction.Functional.FunctionClosedLocalTree
import PartiteConstruction.Functional.HalfClosedTheorem
import PartiteConstruction.Functional.QuotientFibreObstruction
import PartiteConstruction.Functional.GeneratedRootedWitness
import PartiteConstruction.Functional.HistoryRootedWitness
import PartiteConstruction.Functional.FunctionalHistoryRootedWitness
import PartiteConstruction.Functional.HistoryIrreducibleRootGlue
import PartiteConstruction.Functional.TreeExtensionWitness
import PartiteConstruction.Functional.FreeAmalgamGeneratorBudget

#print axioms StructuralRamsey.RelStructure.Embedding.functionClosedSet_preimage
#print axioms StructuralRamsey.RelStructure.Embedding.functionClosed_iff_range
#print axioms StructuralRamsey.RelStructure.IsFreeAmalgam.functionClosedSet_iff
#print axioms StructuralRamsey.RelStructure.IsFreeAmalgam.left_preimage_right_range
#print axioms StructuralRamsey.RelStructure.IsFreeAmalgam.right_preimage_left_range
#print axioms StructuralRamsey.RelStructure.IsFreeAmalgam.left_closed_iff
#print axioms StructuralRamsey.RelStructure.IsFreeAmalgam.right_closed_iff
#print axioms StructuralRamsey.RelStructure.IsFreeAmalgam.sides_closed_iff
#print axioms StructuralRamsey.RelStructure.IsFreeAmalgam.common_image_closed_iff
#print axioms StructuralRamsey.Partite.HalfClosed.ramseyPartiteWitness
#print axioms StructuralRamsey.Structure.QuotientFibreObstruction.collapse_surjective
#print axioms StructuralRamsey.Structure.QuotientFibreObstruction.generated_image_exact
#print axioms StructuralRamsey.Structure.QuotientFibreObstruction.collapse_graph_hom
#print axioms StructuralRamsey.Structure.QuotientFibreObstruction.collapse_not_full_hom

#print axioms StructuralRamsey.Structure.LocallyGeneratedTreeCompletable.rootedWitness
#print axioms StructuralRamsey.Structure.FunctionalHistoryTreeLike.rootedWitness
#print axioms StructuralRamsey.Structure.LocallyClosedTreeCompletable.freeAmalgam_irreducibleRoot
#print axioms StructuralRamsey.Structure.HasTreeExtensionCompletion.of_embedding_into_base

#print axioms StructuralRamsey.RelStructure.FunctionClosedHasTreeCompletion.glue
#print axioms StructuralRamsey.RelStructure.FunctionClosedLocallyTreeCompletable.toFunctional
#print axioms StructuralRamsey.RelStructure.FunctionClosedLocallyTreeCompletable.of_treeAmalgam
#print axioms StructuralRamsey.RelStructure.FunctionClosedHasTreeCompletion.of_closedEmbedding

#print axioms StructuralRamsey.RelStructure.ClosureRule.rootLE

#print axioms StructuralRamsey.RelStructure.arrow_of_BCopywiseCompletion
#print axioms StructuralRamsey.RelStructure.arrow_of_BCopywiseCompletion_inClass
#print axioms StructuralRamsey.RelStructure.IsUSubstructure.image_inclusion
#print axioms StructuralRamsey.RelStructure.UClosureHull_induce_generated
#print axioms StructuralRamsey.RelStructure.USize_le_of_generating
#print axioms StructuralRamsey.RelStructure.USize_induce_UClosureHull_le
#print axioms StructuralRamsey.RelStructure.local_property_of_closed_USize
#print axioms StructuralRamsey.RelStructure.HasCopywiseCompletion.of_compatible_class_diagram

#print axioms StructuralRamsey.RelStructure.IsClosedUHomomorphismEmbedding.on_test
#print axioms StructuralRamsey.RelStructure.IsClosedUHomomorphismEmbedding.comp
#print axioms StructuralRamsey.RelStructure.IsClosedUHomomorphismEmbedding.precomp_embedding
#print axioms StructuralRamsey.RelStructure.IsClosedUHomomorphismEmbedding.codRestrict
#print axioms StructuralRamsey.RelStructure.IsClosedUHomomorphismEmbedding.weakImage
#print axioms StructuralRamsey.RelStructure.IsClosedUHomomorphismEmbedding.copywise
#print axioms StructuralRamsey.RelStructure.Embedding.isClosedUHomomorphismEmbedding
#print axioms StructuralRamsey.RelStructure.HasClosedUKCompletion.pullback_embedding
#print axioms StructuralRamsey.RelStructure.HasClosedUKCompletion.of_closed_USize
#print axioms StructuralRamsey.RelStructure.HasClosedUKCompletion.toCopywise
#print axioms StructuralRamsey.RelStructure.closedHull_factor_closed_copy
#print axioms StructuralRamsey.RelStructure.closedHull_in_class_of_subset_copy
#print axioms StructuralRamsey.RelStructure.IsClosedUHomomorphismEmbedding.common_boundary_embeddings
#print axioms StructuralRamsey.RelStructure.HasCopywiseCompletion.of_independent_projected_completions
#print axioms StructuralRamsey.RelStructure.IsFreeAmalgam.closed_test_factor
#print axioms StructuralRamsey.RelStructure.IsClosedUHomomorphismEmbedding.fold_free
#print axioms StructuralRamsey.RelStructure.HasClosedUKCompletion.of_independent_projected_completions

#print axioms StructuralRamsey.RelStructure.IsUSubstructure.preimage_homomorphism
#print axioms StructuralRamsey.RelStructure.IsHomomorphism.image_UClosureHull_subset
#print axioms StructuralRamsey.RelStructure.IsHomomorphism.range_subset_generatedHull
#print axioms StructuralRamsey.RelStructure.IsHomomorphism.generatedHull_eq_rangeHull
#print axioms StructuralRamsey.RelStructure.IsClosedUHomomorphismEmbedding.to_generatedHull
#print axioms StructuralRamsey.RelStructure.HasClosedUKCompletion.precomp_closedMap
#print axioms StructuralRamsey.RelStructure.projected_generator_card_lt
#print axioms StructuralRamsey.RelStructure.HasClosedUKCompletion.of_projected_generators
#print axioms StructuralRamsey.RelStructure.HasClosedUKCompletion.of_generator_collision
#print axioms StructuralRamsey.RelStructure.HasClosedUKCompletion.of_common_projection_supports
#print axioms StructuralRamsey.RelStructure.HasClosedUKCompletion.of_common_projection_generators
#print axioms StructuralRamsey.RelStructure.IsFreeAmalgam.left_generated_over_root
#print axioms StructuralRamsey.RelStructure.IsFreeAmalgam.right_generated_over_root
#print axioms StructuralRamsey.RelStructure.IsFreeAmalgam.left_projection_mem_hull
#print axioms StructuralRamsey.RelStructure.IsFreeAmalgam.right_projection_mem_hull
#print axioms StructuralRamsey.RelStructure.HasClosedUKCompletion.of_whole_generated_projection_supports

#print axioms StructuralRamsey.RelStructure.IsUClosed.uIrreducible_of_irreducible_generators
#print axioms StructuralRamsey.RelStructure.IsUClosed.irreducibleSeed_hull_isUIrreducible
#print axioms StructuralRamsey.RelStructure.IsClosedUHomomorphismEmbedding.on_irreducibleSeed_hull
#print axioms StructuralRamsey.RelStructure.IsClosedUHomomorphismEmbedding.toHomomorphismEmbedding_of_closed
#print axioms StructuralRamsey.RelStructure.IsClosedUHomomorphismEmbedding.injOn_irreducibleSeed_hull
#print axioms StructuralRamsey.RelStructure.IsClosedUHomomorphismEmbedding.image_irreducibleSeed_hull_eq
#print axioms StructuralRamsey.RelStructure.IsUClosed.singleton_hull_isUIrreducible
#print axioms StructuralRamsey.RelStructure.IsUClosed.uIrreducible_of_USize_le_one
#print axioms StructuralRamsey.RelStructure.closed_rank_one_completions_of_protected_coverage
#print axioms StructuralRamsey.RelStructure.HasClosedUKCompletion.ordinary_pullback_from_closed
#print axioms StructuralRamsey.RelStructure.ordinary_weak_completions_of_closed_USize
#print axioms StructuralRamsey.RelStructure.IsFreeAmalgam.left_generator_drop_over_root
#print axioms StructuralRamsey.RelStructure.IsFreeAmalgam.right_generator_drop_over_root
#print axioms StructuralRamsey.RelStructure.IsFreeAmalgam.both_generator_budgets_over_root

#print axioms StructuralRamsey.RelStructure.IsUIrreducible.closed_cover
#print axioms StructuralRamsey.RelStructure.IsClosedUHomomorphismEmbedding.of_comp_homomorphisms
#print axioms StructuralRamsey.RelStructure.Attachment.rest_isUSubstructure
#print axioms StructuralRamsey.RelStructure.Attachment.closed_test_core_or_copy
#print axioms StructuralRamsey.RelStructure.Attachment.fold_isClosedUHomomorphismEmbedding
#print axioms StructuralRamsey.RelStructure.Attachment.protected_retraction_to_old
#print axioms StructuralRamsey.RelStructure.Attachment.completion_from_old_rank_via_retraction
#print axioms StructuralRamsey.RelStructure.Attachment.protected_coverage_of_retraction
#print axioms StructuralRamsey.RelStructure.Attachment.subfamily_range_isUSubstructure
#print axioms StructuralRamsey.RelStructure.Attachment.subfamily_isUClosed
#print axioms StructuralRamsey.RelStructure.Attachment.exterior_index_from_generator
#print axioms StructuralRamsey.RelStructure.Attachment.factor_through_generator_subfamily
#print axioms StructuralRamsey.Partite.Induced.coordinate_homomorphism
#print axioms StructuralRamsey.Partite.Induced.coordinate_closedMap
#print axioms StructuralRamsey.Partite.Induced.coordinate_lineMap_parameter
#print axioms StructuralRamsey.Partite.Induced.completion_of_common_generator_coordinate
#print axioms StructuralRamsey.Partite.Induced.no_monochromatic_line_with_fixed_parameter
