import PartiteConstruction

#print axioms StructuralRamsey.HalesJewett.finite
#print axioms StructuralRamsey.Partite.NonInduced.lineMap_rel_iff
#print axioms StructuralRamsey.Partite.NonInduced.lineEmbedding_comp_letter
#print axioms StructuralRamsey.Partite.NonInduced.partiteLemma
#print axioms StructuralRamsey.Partite.NonInduced.partiteLemma_expanded
#print axioms StructuralRamsey.Partite.arrow_iff_expanded
#print axioms StructuralRamsey.Partite.projectedEquiv
#print axioms StructuralRamsey.Partite.backwardFusion
#print axioms StructuralRamsey.RelStructure.Attachment.core_rel_iff
#print axioms StructuralRamsey.RelStructure.Attachment.copy_rel_iff
#print axioms StructuralRamsey.Partite.Attachment.copy_extends
#print axioms StructuralRamsey.Partite.Picture.copy_comp_restrict
#print axioms StructuralRamsey.Partite.pictureLemma
#print axioms StructuralRamsey.Partite.Initial.copyEmbedding
#print axioms StructuralRamsey.Partite.nonInducedConstruction
#print axioms StructuralRamsey.Partite.allProjections
#print axioms StructuralRamsey.Partite.nonInducedConstruction_preserving
#print axioms StructuralRamsey.Partite.ramseyFromProjections
#print axioms StructuralRamsey.RelStructure.Embedding.completeOrder
#print axioms StructuralRamsey.RelStructure.arrow_completeOrder
#print axioms StructuralRamsey.RelStructure.exists_order_extension
#print axioms StructuralRamsey.FiniteRamsey.strictMono
#print axioms StructuralRamsey.RelStructure.Embedding.strictMono
#print axioms StructuralRamsey.Partite.orderedRamseyFromProjections
#print axioms StructuralRamsey.Partite.increasingProjectionRamsey
#print axioms StructuralRamsey.Partite.orderedRamsey

#print axioms StructuralRamsey.RelStructure.IsHomomorphismEmbedding.comp
#print axioms StructuralRamsey.Partite.Induced.power_isPartiteOver
#print axioms StructuralRamsey.Partite.Induced.partiteLemma
#print axioms StructuralRamsey.RelStructure.Attachment.irreducible_core_or_copy
#print axioms StructuralRamsey.Partite.Attachment.attach_isPartiteOver
#print axioms StructuralRamsey.Partite.Induced.pictureLemma
#print axioms StructuralRamsey.Partite.Induced.Initial.picture_covers
#print axioms StructuralRamsey.Partite.Induced.relevant_iff_image_contained
#print axioms StructuralRamsey.Partite.Induced.Attachment.attach_covers
#print axioms StructuralRamsey.Partite.Induced.canonical_based
#print axioms StructuralRamsey.Partite.Induced.pictureStep
#print axioms StructuralRamsey.Partite.Induced.inducedConstruction

#print axioms StructuralRamsey.Structure.embeddingEquivClosedGraph
#print axioms StructuralRamsey.Structure.arrow_ofGraph_iff_closed
#print axioms StructuralRamsey.Partite.Closed.Induced.partiteLemma
#print axioms StructuralRamsey.Partite.Closed.support_functionClosed
#print axioms StructuralRamsey.Partite.Closed.Initial.uTransversal
#print axioms StructuralRamsey.Partite.Closed.Attachment.core_closed
#print axioms StructuralRamsey.Partite.Closed.Attachment.copy_closed
#print axioms StructuralRamsey.Partite.Closed.Attachment.uTransversal
#print axioms StructuralRamsey.Partite.Closed.Picture.pictureLemma
#print axioms StructuralRamsey.Partite.Closed.Construction.inducedConstruction
#print axioms StructuralRamsey.Structure.inducedRamsey

#print axioms StructuralRamsey.Structure.weakInduce_graph_rel_iff
#print axioms StructuralRamsey.Structure.weakLocallyTreeLike_iff
#print axioms StructuralRamsey.RelStructure.LocallyTreeLike.completeControl
#print axioms StructuralRamsey.Partite.Iterated.canonicalStep_locallyTreeLike

#print axioms StructuralRamsey.Partite.Iterated.WeakTrace.locallyTreeLike

#print axioms StructuralRamsey.RelStructure.FreeAmalgam.fold_isHomomorphismEmbedding
#print axioms StructuralRamsey.RelStructure.FreeAmalgam.attachOverIrreducible_preservesProjection
#print axioms StructuralRamsey.RelStructure.HereditarilyIrreducible.pullback
#print axioms StructuralRamsey.RelStructure.LocallyTreeLike.base
#print axioms StructuralRamsey.RelStructure.LocallyTreeLike.freeAmalgam
#print axioms StructuralRamsey.RelStructure.FreeAmalgam.attachOverIrreducible_preservesProjectionAndLocalTree
#print axioms StructuralRamsey.RelStructure.FreeAmalgam.irreduciblesExtendTo_amalgam
#print axioms StructuralRamsey.RelStructure.FinalCompletion.exists_completion
#print axioms StructuralRamsey.RelStructure.FinalSparsening.build_all
#print axioms StructuralRamsey.RelStructure.FinalSparsening.Stage.arrow
#print axioms StructuralRamsey.Partite.Induced.Trace.locallyTreeLike
#print axioms StructuralRamsey.Partite.Induced.inducedConstruction_locallyTreeLike
#print axioms StructuralRamsey.RelStructure.ProjectsIrreduciblesInto.precomp
#print axioms StructuralRamsey.Partite.IteratedSparsening.build
#print axioms StructuralRamsey.Partite.IteratedSparsening.sparseningRamsey_hereditarilyIrreducible
#print axioms StructuralRamsey.Partite.IteratedSparsening.sparseningRamsey_hereditarilyIrreducible_all

#print axioms StructuralRamsey.Partite.HalfClosed.Initial.uTransversal
#print axioms StructuralRamsey.Partite.HalfClosed.Initial.isPartiteOver
#print axioms StructuralRamsey.Partite.HalfClosed.Construction.inducedConstruction
#print axioms StructuralRamsey.Partite.HalfClosed.Construction.relevant_iff_image_contained
#print axioms StructuralRamsey.RelStructure.Attachment.copy_comp_not_functionClosed
#print axioms StructuralRamsey.Partite.ClosedRepair.disjointCopies_uTransversal
#print axioms StructuralRamsey.Partite.ClosedRepair.uTransversal_of_tupleCovered
#print axioms StructuralRamsey.Partite.ClosedRepair.copyGenerated_uTransversal
#print axioms StructuralRamsey.Partite.ClosedRepair.copyGenerated_arrow
#print axioms StructuralRamsey.Partite.Nested.flatten_isPartiteOver
#print axioms StructuralRamsey.Partite.Nested.flatten_uTransversal
#print axioms StructuralRamsey.Language.PositiveFuncArity.withParts
#print axioms StructuralRamsey.Partite.closedArrow_iff_functionalExpanded
#print axioms StructuralRamsey.Partite.halfClosedArrow_iff_functionalExpanded
#print axioms StructuralRamsey.Partite.irreducible_expandFunctional_of_reduct
#print axioms StructuralRamsey.Partite.isPartiteOver_of_functionalExpanded
#print axioms StructuralRamsey.Partite.functionOutputTransversal_of_expanded
#print axioms StructuralRamsey.Partite.Closed.Embedding.toFlattenedFunctional
#print axioms StructuralRamsey.Partite.closedArrow_flattened_of_functionalExpanded
#print axioms StructuralRamsey.Partite.Nested.flatten_uTransversal_comp
#print axioms StructuralRamsey.Partite.HalfClosed.inducedPartite
#print axioms StructuralRamsey.Partite.Recursive.build
#print axioms StructuralRamsey.Partite.Recursive.recursiveConstruction_of_localPictures
#print axioms StructuralRamsey.Partite.Recursive.localHalfClosedPicture_of_closed
#print axioms StructuralRamsey.Partite.HalfClosed.inducedPartiteOver

#print axioms StructuralRamsey.Structure.rankExpand_singletonValued
#print axioms StructuralRamsey.Structure.mem_rankedValue_of_mem
#print axioms StructuralRamsey.Structure.Embedding.rankExpand
#print axioms StructuralRamsey.Structure.Embedding.rankExpand_unique

#print axioms StructuralRamsey.Structure.Embedding.forgetRanks
#print axioms StructuralRamsey.Structure.arrow_of_rankExpansion
#print axioms StructuralRamsey.Structure.arrow_of_singletonExpansion

#print axioms StructuralRamsey.Structure.Embedding.partialGraph
#print axioms StructuralRamsey.Structure.Embedding.ofPartialGraph
#print axioms StructuralRamsey.Structure.Embedding.partialGraphEquiv
#print axioms StructuralRamsey.Structure.embeddingEquivRankedPartialGraph

#print axioms StructuralRamsey.Partite.System.FunctionOutputSingleValued.uTransversal
#print axioms StructuralRamsey.Partite.Closed.Induced.power_singleValued
#print axioms StructuralRamsey.Partite.HalfClosed.Initial.singleValued
#print axioms StructuralRamsey.Partite.Closed.Attachment.singleValued
#print axioms StructuralRamsey.Partite.Nested.flatten_singleValued

#print axioms StructuralRamsey.Partite.Closed.Picture.build_singleValued
#print axioms StructuralRamsey.Partite.Closed.Picture.pictureLemma_singleValued

#print axioms StructuralRamsey.Partite.HalfClosed.Construction.build_singleValued
#print axioms StructuralRamsey.Partite.HalfClosed.Construction.inducedConstruction_singleValued

#print axioms StructuralRamsey.Partite.HalfClosed.inducedPartiteOver_singleton
#print axioms StructuralRamsey.Partite.HalfClosed.inducedPartiteOver_singleton_uTransversal

#print axioms StructuralRamsey.Language.PositiveFuncArity.withFunctionDomains
#print axioms StructuralRamsey.Structure.Embedding.withFunctionDomains
#print axioms StructuralRamsey.RelStructure.withFunctionDomains_graph_semiClosed
#print axioms StructuralRamsey.RelStructure.closedEmbedding_of_localSemiClosed

#print axioms StructuralRamsey.Partite.System.induce_isPartiteOver
#print axioms StructuralRamsey.Partite.System.induce_outputImpliesDomain
#print axioms StructuralRamsey.Partite.System.restrict_outputImpliesDomain

#print axioms StructuralRamsey.Partite.Attachment.restrictClosedToInduce
#print axioms StructuralRamsey.Partite.Attachment.selectedCopy_closed

#print axioms StructuralRamsey.Partite.SemiClosed.Picture.pictureLemma

#print axioms StructuralRamsey.Partite.SemiClosed.Picture.selectedLift_core

#print axioms StructuralRamsey.Partite.SemiClosed.Picture.liftCore_unique

#print axioms StructuralRamsey.Partite.SemiClosed.Picture.build_isPartiteOver
#print axioms StructuralRamsey.Partite.SemiClosed.Picture.halfClosedProperty

#print axioms StructuralRamsey.Partite.Attachment.selectedCopy_closed_of_projection
#print axioms StructuralRamsey.Partite.SemiClosed.Recursive.step
#print axioms StructuralRamsey.Partite.SemiClosed.Recursive.build
#print axioms StructuralRamsey.Partite.SemiClosed.Recursive.recursiveConstruction

#print axioms StructuralRamsey.RelStructure.rootPrune_outputImpliesDomain
#print axioms StructuralRamsey.RelStructure.Embedding.toRootPrune
#print axioms StructuralRamsey.RelStructure.arrow_rootPrune

#print axioms StructuralRamsey.Partite.SemiClosed.Recursive.recursiveConstruction_from_ordinaryWitness

#print axioms StructuralRamsey.Structure.Embedding.strictMono
#print axioms StructuralRamsey.Structure.Embedding.completeLinearOrder
#print axioms StructuralRamsey.Structure.arrow_forgetFunctionDomains
#print axioms StructuralRamsey.Structure.arrow_completeLinearOrder
#print axioms StructuralRamsey.Structure.exists_linearOrder_extension
#print axioms StructuralRamsey.RelStructure.ordinaryWitness_namedOrder
#print axioms StructuralRamsey.Structure.orderedRamsey_singleton
#print axioms StructuralRamsey.Structure.orderedRamsey
#print axioms StructuralRamsey.Structure.orderedClosedGraphRamsey

#print axioms StructuralRamsey.RelStructure.LocallyTreeLike.rootedWitness_controlled
#print axioms StructuralRamsey.RelStructure.LocallyTreeLike.rootedWitness
#print axioms StructuralRamsey.RelStructure.LocallyTreeLike.freeAmalgam_rootBudget
#print axioms StructuralRamsey.RelStructure.FreeAmalgam.attachOverIrreducible_preservesProjectionAndLocalTree_rootBudget
#print axioms StructuralRamsey.RelStructure.RootBudgetTrace.locallyTreeLike

#print axioms StructuralRamsey.RelStructure.TreeAmalgam.exists_base_embedding
#print axioms StructuralRamsey.RelStructure.TreeAmalgam.attachIndexedList
#print axioms StructuralRamsey.RelStructure.TreeAmalgam.attachIndexed

#print axioms StructuralRamsey.RelStructure.LocallyTreeLike.attachmentWitness_of_selected

#print axioms StructuralRamsey.RelStructure.LocallyTreeLike.testTrace
#print axioms StructuralRamsey.RelStructure.LocallyTreeLike.eq_of_testTrace_eq
#print axioms StructuralRamsey.RelStructure.LocallyTreeLike.exists_selected_indices

#print axioms StructuralRamsey.RelStructure.LocallyTreeLike.fixedSupportBudget
#print axioms StructuralRamsey.RelStructure.LocallyTreeLike.attachment_locallyTreeLike_fixedSupport

#print axioms StructuralRamsey.RelStructure.Attachment.fold
#print axioms StructuralRamsey.RelStructure.Attachment.fold_copy
#print axioms StructuralRamsey.RelStructure.Attachment.fold_isHomomorphismEmbedding

#print axioms StructuralRamsey.RelStructure.Embedding.rangeInverse
#print axioms StructuralRamsey.RelStructure.Embedding.rangeInverse_apply
#print axioms StructuralRamsey.RelStructure.Embedding.rangeInverse_left

#print axioms StructuralRamsey.RelStructure.Embedding.imageFinset
#print axioms StructuralRamsey.RelStructure.Embedding.mem_imageFinset_iff
#print axioms StructuralRamsey.RelStructure.Embedding.imageInverse
#print axioms StructuralRamsey.RelStructure.Embedding.imageInverse_apply
#print axioms StructuralRamsey.RelStructure.Embedding.imageInverse_left

#print axioms StructuralRamsey.RelStructure.rootEmbeddingIntoBase

#print axioms StructuralRamsey.RelStructure.Embedding.imageInverseAt
#print axioms StructuralRamsey.RelStructure.Embedding.imageInverseAt_apply

#print axioms StructuralRamsey.RelStructure.FinalSupport.Root.beta
#print axioms StructuralRamsey.RelStructure.FinalSupport.Root.toBase
#print axioms StructuralRamsey.RelStructure.FinalSupport.Root.support
#print axioms StructuralRamsey.RelStructure.FinalSupport.Root.supportEmbedding
#print axioms StructuralRamsey.RelStructure.FinalSupport.AtSupport.embedding
#print axioms StructuralRamsey.RelStructure.FinalSupport.AtSupport.embedding_compat

#print axioms StructuralRamsey.RelStructure.FinalSupport.Root.support_irreducible

#print axioms StructuralRamsey.RelStructure.FinalCompletion.coreOrBase_attachment

#print axioms StructuralRamsey.RelStructure.UniformFinal.initial
#print axioms StructuralRamsey.RelStructure.UniformFinal.attachSupport

#print axioms StructuralRamsey.FiniteTrace.selectIndices
#print axioms StructuralRamsey.FiniteTrace.selectIndices_cardBound

#print axioms StructuralRamsey.RelStructure.UniformFinal.CoversSupport.of_embedding
#print axioms StructuralRamsey.RelStructure.UniformFinal.attachSupportList
#print axioms StructuralRamsey.RelStructure.UniformFinal.build_all_supports

#print axioms StructuralRamsey.Partite.IteratedSparsening.sparseningRamsey_uniformFinal
#print axioms StructuralRamsey.Partite.IteratedSparsening.sparseningRamsey_uniformFinal_all

#print axioms StructuralRamsey.RelStructure.LocallyTreeLike.compatible_overlap_kernel_iff
#print axioms StructuralRamsey.RelStructure.LocallyTreeLike.no_compatible_overlap_of_kernel_mismatch
#print axioms StructuralRamsey.RelStructure.LocallyTreeLike.same_kernel_of_controlled_gluing_data

#print axioms StructuralRamsey.RelStructure.MixedOverlapExample.A_irreducible
#print axioms StructuralRamsey.RelStructure.MixedOverlapExample.left_valid
#print axioms StructuralRamsey.RelStructure.MixedOverlapExample.right_valid
#print axioms StructuralRamsey.RelStructure.MixedOverlapExample.no_common_embedded_overlap

#print axioms StructuralRamsey.RelStructure.IntersectionStrongLocallyTreeLike.toLocallyTreeLike
#print axioms StructuralRamsey.RelStructure.IntersectionStrongLocallyTreeLike.zero_of_embeddings
#print axioms StructuralRamsey.RelStructure.IntersectionStrongLocallyTreeLike.of_homEmbedding_to_base
#print axioms StructuralRamsey.RelStructure.IntersectionStrongLocallyTreeLike.pullback_embedding
#print axioms StructuralRamsey.RelStructure.IntersectionStrongLocallyTreeLike.witness_of_homEmbedding_image

#print axioms StructuralRamsey.RelStructure.LocallyTreeLike.glueControlled_of_contained

#print axioms StructuralRamsey.RelStructure.LocallyTreeLike.glueProjectedFull_intersectionStrong

#print axioms StructuralRamsey.RelStructure.Embedding.ContainedInIrreducible.postcomp
#print axioms StructuralRamsey.RelStructure.LocallyTreeLike.EmbeddedIntersections.postcomp
#print axioms StructuralRamsey.RelStructure.LocallyTreeLike.addControl_of_embeddedIntersection
#print axioms StructuralRamsey.RelStructure.LocallyTreeLike.completeControl_of_embeddedIntersections

#print axioms StructuralRamsey.Partite.Iterated.pureCore_embeddedWitness

#print axioms StructuralRamsey.RelStructure.Attachment.irreducible_copy_or_intersection_in_support

#print axioms StructuralRamsey.Partite.Induced.embedding_coordinate
