import PartiteConstruction.Functional.ClosedTestGraphTreeObstruction
import PartiteConstruction.Functional.ProjectedClosedTreePullback
import PartiteConstruction.Functional.EHNClosedTestGraphCorollary
import PartiteConstruction.Functional.PublishedSparseningScope
import PartiteConstruction.Functional.PublishedSparseningUnary
import PartiteConstruction.Functional.PublishedSparseningTarget
import PartiteConstruction.Functional.PublishedProjectionObstruction
import PartiteConstruction.Functional.EHNIteratedWeakTree
import PartiteConstruction.Functional.EHNStageAttachmentGraph
import PartiteConstruction.Functional.EHNAttachmentGraphIso
import PartiteConstruction.Functional.EHNRestrictionGraph
import PartiteConstruction.Functional.EHNAttachmentGraph
import PartiteConstruction.Functional.EHNPowerGraph
import PartiteConstruction.Functional.EHNToRelationalPartite
import PartiteConstruction.Functional.EHNProjectionGraphBridge
import PartiteConstruction.Functional.EHNFibreBijective
import PartiteConstruction.Functional.NativePowerStaircase
import PartiteConstruction.Functional.NoSquareFreeGluing
import PartiteConstruction.Functional.NativePowerTreeSquare
import PartiteConstruction.Functional.NativePowerConcreteStage
import PartiteConstruction.Functional.NativePowerFullObstruction
import PartiteConstruction.Functional.QuotientBoundaryDomainObstruction
import PartiteConstruction.Functional.ProjectedWeakImage
import PartiteConstruction.Functional.DirectWeakIteration
import PartiteConstruction.Functional.FreeAmalgamEmbeddedInduction
import PartiteConstruction.Functional.FreeAmalgamHistoryInduction
import PartiteConstruction.Functional.PureHistoryTreeCompletion
import PartiteConstruction.Functional.FiniteHistoryRankBound
import PartiteConstruction.Functional.FiniteHistoryInduction
import PartiteConstruction.Functional.EHNDomainFailureDecompose
import PartiteConstruction.Functional.InjectiveProjectedGlue
import PartiteConstruction.Functional.EHNClosedRootInduction
import PartiteConstruction.Functional.TreeExtensionHistoryGlue
import PartiteConstruction.Functional.TreeExtensionHistoryWitness
import PartiteConstruction.Functional.TreeExtensionHistoryInduction
import PartiteConstruction.Functional.RelativeHistoryRootedWithHistory
import PartiteConstruction.Functional.ProjectedHistoryFactor
import PartiteConstruction.Functional.TreeExtensionAutoHistoryGlue
import PartiteConstruction.Functional.EHNClosedAttachmentRootHistory
import PartiteConstruction.Functional.EHNClosedMixedSize
import PartiteConstruction.Functional.EHNClosedPullbackRootDichotomy
import PartiteConstruction.Functional.EHNIrreducibleMixedCompletion
import PartiteConstruction.Functional.EHNClosedPullbackProjection
import PartiteConstruction.Functional.LooseTreeAmalgam
import PartiteConstruction.Functional.PureCoreProjectedHistory
import PartiteConstruction.Functional.InitialTreeCompletion
import PartiteConstruction.Functional.HistoryZero
import PartiteConstruction.Functional.EHNInvariantConstruction
import PartiteConstruction.Functional.EHNPictureInvariant
import PartiteConstruction.Functional.EHNStageInvariant
import PartiteConstruction.Ramsey.FreeAmalgamationFunctionsAllArity
import PartiteConstruction.Ramsey.ForbiddenFunctionsAllArity
import PartiteConstruction.Ramsey.ForbiddenFunctions
import PartiteConstruction.Structure.RootedReduction
import PartiteConstruction.Structure.RootedFunctor
import PartiteConstruction.Structure.RootedSplit
import PartiteConstruction.Structure.RootedCorrectness
import PartiteConstruction.Structure.RootedFreeAmalgam
import PartiteConstruction.Structure.RootedClass
import PartiteConstruction.Structure.RootedEmbedding
import PartiteConstruction.Structure.RootedOrder
import PartiteConstruction.Structure.RootedCanonical
import PartiteConstruction.Structure.NullaryRoot

#print axioms StructuralRamsey.Structure.generates_of_surjective
#print axioms StructuralRamsey.Structure.IsWeakHomomorphism.preimage_isClosed
#print axioms StructuralRamsey.Structure.ProperFreeDecomposition.pullback_generated_weak
#print axioms StructuralRamsey.Structure.Irreducible.of_generated_weakHomomorphism
#print axioms StructuralRamsey.Structure.Irreducible.of_surjective_weakHomomorphism
#print axioms StructuralRamsey.Structure.Irreducible.weakImage
#print axioms StructuralRamsey.Structure.subset_functionClosure
#print axioms StructuralRamsey.Structure.functionClosure_isClosed
#print axioms StructuralRamsey.Structure.IsWeakHomomorphism.closureLift
#print axioms StructuralRamsey.Structure.closureLift_generates
#print axioms StructuralRamsey.Structure.Irreducible.functionClosure_weakImage
#print axioms StructuralRamsey.FunctionalPartite.Induced.letter_func_member
#print axioms StructuralRamsey.FunctionalPartite.Induced.weak_lineMap_rel_iff
#print axioms StructuralRamsey.FunctionalPartite.Induced.weak_lineMap_func_mem
#print axioms StructuralRamsey.FunctionalPartite.Induced.weak_lineMap_func
#print axioms StructuralRamsey.FunctionalPartite.Induced.weak_lineEmbedding
#print axioms StructuralRamsey.FunctionalPartite.Induced.weak_wordEmbedding
#print axioms StructuralRamsey.FunctionalPartite.Induced.weak_wordEmbedding_apply
#print axioms StructuralRamsey.FunctionalPartite.Induced.weak_lineEmbedding_comp_letter
#print axioms StructuralRamsey.FunctionalPartite.Induced.weak_partiteLemma
#print axioms StructuralRamsey.Structure.IsEHNHomomorphismEmbedding.comp
#print axioms StructuralRamsey.Structure.Embedding.isEHNHomomorphismEmbedding
#print axioms StructuralRamsey.FunctionalPartite.Induced.coordinateWeak
#print axioms StructuralRamsey.FunctionalPartite.Induced.power_projectionWeak
#print axioms StructuralRamsey.FunctionalPartite.Induced.power_weaklyPartiteOver
#print axioms StructuralRamsey.FunctionalPartite.Induced.weak_partiteLemma_withInvariant
#print axioms StructuralRamsey.Structure.Embedding.factorWithMap
#print axioms StructuralRamsey.Structure.Embedding.factorThroughClosedRange
#print axioms StructuralRamsey.Structure.Embedding.cancel_weak
#print axioms StructuralRamsey.FunctionalPartite.System.weak_support_closed
#print axioms StructuralRamsey.FunctionalPartite.System.weakRestrict_projection
#print axioms StructuralRamsey.FunctionalPartite.System.weakRestrict_invariant
#print axioms StructuralRamsey.FunctionalPartite.weakRestrictCopy
#print axioms StructuralRamsey.Structure.IsEHNHomomorphismEmbedding.of_freeAmalgam
#print axioms StructuralRamsey.Structure.Attachment.unit_isFreeAmalgam
#print axioms StructuralRamsey.FunctionalPartite.Attachment.unit_weaklyPartiteOver
#print axioms StructuralRamsey.FunctionalPartite.Attachment.unit_mem
#print axioms StructuralRamsey.FunctionalPartite.EHN.Stage.attach
#print axioms StructuralRamsey.FunctionalPartite.EHN.attachList
#print axioms StructuralRamsey.FunctionalPartite.EHN.attachAll
#print axioms StructuralRamsey.FunctionalPartite.EHN.mem_of_weaklyPartiteOver
#print axioms StructuralRamsey.FunctionalPartite.EHN.placed_over
#print axioms StructuralRamsey.FunctionalPartite.EHN.empty_closed
#print axioms StructuralRamsey.FunctionalPartite.EHN.initialList
#print axioms StructuralRamsey.FunctionalPartite.EHN.initial
#print axioms StructuralRamsey.FunctionalPartite.EHN.pictureLemma
#print axioms StructuralRamsey.FunctionalPartite.EHN.canonicalize
#print axioms StructuralRamsey.FunctionalPartite.EHN.inducedConstruction
#print axioms StructuralRamsey.Structure.Embedding.linearOrderReduct
#print axioms StructuralRamsey.Structure.IsFreeAmalgam.linearOrderReduct
#print axioms StructuralRamsey.Structure.FreeAmalgamationClass.orderLift
#print axioms StructuralRamsey.Structure.FreeAmalgamationClass.orderedRamsey
#print axioms StructuralRamsey.Structure.FreeAmalgamationClass.orderedRamsey_of_mem_target
#print axioms StructuralRamsey.Structure.avoidsEmbeddings_freeAmalgamationClass
#print axioms StructuralRamsey.Structure.orderedRamsey_avoiding
#print axioms StructuralRamsey.Structure.irreducible_of_linearOrderReduct
#print axioms StructuralRamsey.Structure.Embedding.orderPair_iff
#print axioms StructuralRamsey.Structure.OrderTotalOnIrreducibles.hereditary
#print axioms StructuralRamsey.Structure.OrderTotalOnIrreducibles.free
#print axioms StructuralRamsey.Structure.withLinearOrder_orderTotal
#print axioms StructuralRamsey.Structure.OrderTotalOnIrreducibles.orderPair_complete_iff
#print axioms StructuralRamsey.Structure.Embedding.beforeOrderCompletion
#print axioms StructuralRamsey.Structure.orderedForbiddenClass_free
#print axioms StructuralRamsey.Structure.orderedRamsey_forbidden_expansions

#print axioms StructuralRamsey.Structure.nullaryRoot_isClosed
#print axioms StructuralRamsey.Structure.nullaryRoot_subset_closed
#print axioms StructuralRamsey.Structure.Embedding.image_isClosed
#print axioms StructuralRamsey.Structure.Embedding.image_functionClosure
#print axioms StructuralRamsey.Structure.Embedding.image_nullaryRoot
#print axioms StructuralRamsey.Structure.Embedding.nullaryRoot_surjective
#print axioms StructuralRamsey.Structure.mem_nullaryRoot_iff

#print axioms StructuralRamsey.Rooted.language_positive

#print axioms StructuralRamsey.Rooted.rootEmbedding
#print axioms StructuralRamsey.Rooted.decodeEmbedding

#print axioms StructuralRamsey.Rooted.splitEquiv
#print axioms StructuralRamsey.Rooted.splitEmbedding
#print axioms StructuralRamsey.Rooted.splitEmbedding_surjective

#print axioms StructuralRamsey.Rooted.Pattern.normalize_eq_self_of_comp
#print axioms StructuralRamsey.Rooted.Pattern.pad_sumFill

#print axioms StructuralRamsey.Rooted.Pattern.normalize_pad
#print axioms StructuralRamsey.Rooted.Pattern.dummy_sumFill
#print axioms StructuralRamsey.Rooted.Pattern.funcTuple_preimage_canonical
#print axioms StructuralRamsey.Rooted.Pattern.sumMap_sumFill_of_pad_eq

#print axioms StructuralRamsey.Rooted.Pattern.side_pad_eq
#print axioms StructuralRamsey.Rooted.decode_isFreeAmalgam

#print axioms StructuralRamsey.Rooted.decodedClass_free
#print axioms StructuralRamsey.Rooted.unsplitEmbedding
#print axioms StructuralRamsey.Rooted.encode_mem_decodedClass
#print axioms StructuralRamsey.Rooted.outsideMap_injective
#print axioms StructuralRamsey.Rooted.fill_map
#print axioms StructuralRamsey.Rooted.root_func_iff
#print axioms StructuralRamsey.Rooted.outside_func_image
#print axioms StructuralRamsey.Rooted.encodeEmbedding

#print axioms StructuralRamsey.Rooted.orderRank_strictMono
#print axioms StructuralRamsey.Rooted.cutRank_embedding
#print axioms StructuralRamsey.Rooted.cutRank_encode
#print axioms StructuralRamsey.Rooted.reconstructedOrder
#print axioms StructuralRamsey.Rooted.liftOrderedEmbedding

#print axioms StructuralRamsey.Rooted.canonicalRootEmbedding_range
#print axioms StructuralRamsey.Rooted.canonicalRoot_image_range
#print axioms StructuralRamsey.Rooted.orderedEmbedding_agrees_on_root

#print axioms StructuralRamsey.Rooted.split_embedding

#print axioms StructuralRamsey.Rooted.encodeOrderedEmbedding

#print axioms StructuralRamsey.Rooted.liftOrderedEmbedding_comp

#print axioms StructuralRamsey.Rooted.Structure.FreeAmalgamationClass.orderedRamsey_allArity

#print axioms StructuralRamsey.FunctionalPartite.EHN.rootTransport
#print axioms StructuralRamsey.FunctionalPartite.EHN.rootTransport_spec
#print axioms StructuralRamsey.FunctionalPartite.EHN.initialList_allArity
#print axioms StructuralRamsey.FunctionalPartite.EHN.initial_allArity
#print axioms StructuralRamsey.FunctionalPartite.EHN.inducedConstruction_allArity

#print axioms StructuralRamsey.Structure.allStructures_free
#print axioms StructuralRamsey.Structure.orderedRamsey_forbidden_expansions_allArity

#print axioms StructuralRamsey.FunctionalPartite.EHN.attachList_preserving
#print axioms StructuralRamsey.FunctionalPartite.EHN.attachAll_preserving
#print axioms StructuralRamsey.FunctionalPartite.EHN.pictureLemma_preserving
#print axioms StructuralRamsey.FunctionalPartite.EHN.canonicalize_preserving
#print axioms StructuralRamsey.FunctionalPartite.EHN.inducedConstruction_preserving

#print axioms StructuralRamsey.Structure.GeneratedByAtMost.empty_isClosed_of_positiveArity
#print axioms StructuralRamsey.Structure.GeneratedByAtMost.functionClosure_empty_of_positiveArity
#print axioms StructuralRamsey.Structure.GeneratedByAtMost.isEmpty_of_zero
#print axioms StructuralRamsey.Structure.FunctionalProjectedHistoryTreeLike.identity_zero_of_embeddings
#print axioms StructuralRamsey.Structure.FunctionalHistoryTreeLike.of_treeAmalgam_of_closedSubstructures_irreducible
#print axioms StructuralRamsey.FunctionalPartite.EHN.initial_history
#print axioms StructuralRamsey.Structure.IsEHNHomomorphismEmbedding.closedTest_induction_with_common
#print axioms StructuralRamsey.Structure.LocallyClosedTreeCompletable.glueTreeExtensions_withProjectedHistory
#print axioms StructuralRamsey.Structure.HasTreeExtensionProjectedHistoryCompletion.toTreeExtension
#print axioms StructuralRamsey.Structure.HasCommonRootedProjectedHistoryCompletions.glue
#print axioms StructuralRamsey.Structure.HasTreeExtensionProjectedHistoryCompletion.root_of_projectedFactor
#print axioms StructuralRamsey.Structure.HasTreeExtensionProjectedHistoryCompletion.mono_history
#print axioms StructuralRamsey.Structure.HasTreeExtensionProjectedHistoryCompletion.pullback_embedding
#print axioms StructuralRamsey.Structure.HasTreeExtensionProjectedHistoryCompletion.rebase
#print axioms StructuralRamsey.Structure.HasTreeExtensionProjectedHistoryCompletion.glue_relative
#print axioms StructuralRamsey.Structure.FunctionalRelativeHistoryTreeLike.fullWitness_rootedBase_withHistory
#print axioms StructuralRamsey.Structure.FunctionalRelativeHistoryTreeLike.commonRootedProjectedHistory_embeddedLabels
#print axioms StructuralRamsey.Structure.singleton_mem_singletonProjectedHistory
#print axioms StructuralRamsey.Structure.projectedKernel_of_singletonHistory
#print axioms StructuralRamsey.Structure.projectedMap_factors_of_kernel
#print axioms StructuralRamsey.Structure.projectedMap_factors_of_singletonHistory
#print axioms StructuralRamsey.Structure.HasCommonRootedProjectedHistoryCompletions.of_rootHistory
#print axioms StructuralRamsey.Structure.HasCommonRootedProjectedHistoryCompletions.of_sharedExtensions
#print axioms StructuralRamsey.Structure.HasTreeExtensionProjectedHistoryCompletion.projectionFactorsThroughRoot
#print axioms StructuralRamsey.Structure.LocallyClosedTreeCompletable.glueRelative_withAutomaticProjectedHistory
#print axioms StructuralRamsey.FunctionalPartite.Attachment.closedTest_treeCompletion_of_sharedRootHistories
#print axioms StructuralRamsey.FunctionalPartite.Attachment.closedMixed_pullback_card_lt
#print axioms StructuralRamsey.FunctionalPartite.closedRoot_induction_with_common

#print axioms StructuralRamsey.FunctionalPartite.pureCore_projectedHistory_of_domainReflection
#print axioms StructuralRamsey.FunctionalPartite.pureCore_projectedHistoryTree_of_domainReflection
#print axioms StructuralRamsey.Structure.LocallyClosedTreeCompletable.glueProjectedFull_injectiveProjection
#print axioms StructuralRamsey.Structure.LocallyClosedTreeCompletable.glueProjectedFull_injectiveProjection_withHistory

#print axioms StructuralRamsey.Structure.IsEHNHomomorphismEmbedding.closedTest_decompose_of_domainFailure

#print axioms StructuralRamsey.Structure.IsFreeAmalgam.finite_embedded_induction

#print axioms StructuralRamsey.Structure.IsFreeAmalgam.finiteHistoryCompletion_of_relativeMixed

#print axioms StructuralRamsey.Structure.HasProjectedHistoryTreeCompletion.pullback_embedding
#print axioms StructuralRamsey.Structure.FunctionalProjectedHistoryTreeLike.toFullProjectedHistoryCompletion

#print axioms StructuralRamsey.Structure.IsFreeAmalgam.finiteHistoryCompletion_of_sides_and_relativeMixed

#print axioms StructuralRamsey.Structure.FunctionalHistoryTreeLike.fullProjectedHistory_of_smallEmbedding

#print axioms StructuralRamsey.Structure.IsFreeAmalgam.finiteBoundedHistoryCompletion_of_relativeMixed

#print axioms StructuralRamsey.FunctionalPartite.Attachment.closedTestPullback_common_EHN
#print axioms StructuralRamsey.FunctionalPartite.Attachment.closedTestPullback_common_embedding_or_decompose

#print axioms StructuralRamsey.Structure.IsFreeAmalgam.projectedHistoryCompletion_of_irreducibleEHN_root

#print axioms StructuralRamsey.FunctionalPartite.Attachment.closedTestPullback_common_part_compat
#print axioms StructuralRamsey.Structure.IsEHNHomomorphismEmbedding.hasInjectiveLooseTreeCompletion
#print axioms StructuralRamsey.Structure.IsEHNHomomorphismEmbedding.locallyClosedLooseTreeEmbeddable

#print axioms StructuralRamsey.Structure.irreducible_of_graph_irreducible
#print axioms StructuralRamsey.FunctionalPartite.EHN.directSupport_and_restriction
#print axioms StructuralRamsey.FunctionalPartite.EHN.directSupportInduceToWeak

#print axioms StructuralRamsey.Structure.IsEHNHomomorphismEmbedding.graphHomomorphismEmbedding

#print axioms StructuralRamsey.FunctionalPartite.System.toGraphPartite
#print axioms StructuralRamsey.FunctionalPartite.System.toGraphPartite_isPartiteOver

#print axioms StructuralRamsey.FunctionalPartite.Induced.vertexGraphEquiv
#print axioms StructuralRamsey.FunctionalPartite.Induced.powerGraphIso

#print axioms StructuralRamsey.Structure.Attachment.attachingGraphMap
#print axioms StructuralRamsey.Structure.Attachment.copyMap_graph_eq

#print axioms StructuralRamsey.FunctionalPartite.System.weakRestrictGraphIso

#print axioms StructuralRamsey.Structure.Attachment.graphAttachmentIso

#print axioms StructuralRamsey.FunctionalPartite.EHN.Stage.attachGraphIso

#print axioms StructuralRamsey.FunctionalPartite.EHN.pictureLemma_preservingSupport

#print axioms StructuralRamsey.FunctionalPartite.EHN.Stage.attach_weakGraphLocallyTreeLike
#print axioms StructuralRamsey.FunctionalPartite.EHN.pictureLemma_weakGraphLocallyTreeLike
#print axioms StructuralRamsey.FunctionalPartite.EHN.base_weakGraphLocallyTreeLike
#print axioms StructuralRamsey.FunctionalPartite.EHN.initialList_weakGraphLocallyTreeLike
#print axioms StructuralRamsey.FunctionalPartite.EHN.initial_weakGraphLocallyTreeLike
#print axioms StructuralRamsey.FunctionalPartite.EHN.inducedConstruction_weakGraphLocallyTreeLike
#print axioms StructuralRamsey.FunctionalPartite.EHN.NativeIteratedWeak.first
#print axioms StructuralRamsey.FunctionalPartite.EHN.NativeIteratedWeak.succ
#print axioms StructuralRamsey.FunctionalPartite.EHN.NativeIteratedWeak.build
#print axioms StructuralRamsey.Structure.inducedRamsey_directFunctionalWeakGraph

#print axioms StructuralRamsey.Structure.inducedRamsey_directFunctional_closedGraphTests

#print axioms StructuralRamsey.Structure.FunctionalClosedTestGraphObstruction.fullTree_noTwoStep
#print axioms StructuralRamsey.Structure.FunctionalClosedTestGraphObstruction.pathGraph_tree
#print axioms StructuralRamsey.Structure.FunctionalClosedTestGraphObstruction.pathGraph_hasTreeCompletion
#print axioms StructuralRamsey.Structure.FunctionalClosedTestGraphObstruction.path_no_fullTreeCompletion
#print axioms StructuralRamsey.Structure.FunctionalClosedTestGraphObstruction.closedSource_graphCompletion_not_fullCompletion

#print axioms StructuralRamsey.Structure.LocallyClosedTreeCompletable.pullback_localFull_closedImage
#print axioms StructuralRamsey.Structure.LocallyClosedTreeCompletable.pullback_EHN_closedImage_of_domainReflection

#print axioms StructuralRamsey.Structure.IsWeakHomomorphismEmbedding.weakImage
#print axioms StructuralRamsey.Structure.WeakLocallyTreeCompletable.completion_of_small_weakImage

#print axioms StructuralRamsey.Structure.IsEHNHomomorphismEmbedding.injOn_func_of_nonempty
#print axioms StructuralRamsey.Structure.IsEHNHomomorphismEmbedding.bijOn_func_of_nonempty

#print axioms StructuralRamsey.Structure.IsolatedQuotientBoundary.false_of_domainFailure
#print axioms StructuralRamsey.Structure.QuotientBoundaryRequest.fullLabel_iff_isolatedOneCopy

#print axioms StructuralRamsey.Structure.NativePowerObstruction.staircase_noSquare_obstruction

#print axioms StructuralRamsey.Structure.NativePowerObstruction.squareFree_of_freeUnion

#print axioms StructuralRamsey.Structure.NativePowerObstruction.strictTree_squareFree

#print axioms StructuralRamsey.Structure.NativePowerObstruction.actualPowerDomain_iff_staircase
#print axioms StructuralRamsey.Structure.NativePowerObstruction.actualPower_noSquareTarget

#print axioms StructuralRamsey.Structure.NativePowerObstruction.actualPower_no_fullStrictTreeHom
#print axioms StructuralRamsey.Structure.NativePowerObstruction.actualPower_no_fullTreeCompletion
#print axioms StructuralRamsey.Structure.NativePowerObstruction.actualPower_not_locallyStrictTreeCompletable

#print axioms StructuralRamsey.Structure.sparseningRamsey_functionalWeakGraph
#print axioms StructuralRamsey.Structure.sparseningRamsey_functionalWeakGraph_inClass

#print axioms StructuralRamsey.Structure.PublishedFunctionalProjectionObstruction.projection_not_full

#print axioms StructuralRamsey.Structure.sparseningRamsey_unary_fullProjection_inClass
#print axioms StructuralRamsey.Structure.sparseningRamsey_unary_strictIfOriginalLocallyCompletable
