import PartiteConstruction.Functional.FreeAmalgamClosed
import PartiteConstruction.Functional.FunctionClosedLocalTree
import PartiteConstruction.Functional.HalfClosedTheorem
import PartiteConstruction.Functional.QuotientFibreObstruction
import PartiteConstruction.Functional.GeneratedRootedWitness
import PartiteConstruction.Functional.HistoryRootedWitness
import PartiteConstruction.Functional.HistoryIrreducibleRootGlue
import PartiteConstruction.Functional.TreeExtensionWitness
import PartiteConstruction.Functional.FreeAmalgamGeneratorBudget

#print axioms StructuralRamsey.RelStructure.Embedding.functionClosedSet_preimage
#print axioms StructuralRamsey.RelStructure.Embedding.functionClosed_iff_range
#print axioms StructuralRamsey.RelStructure.IsFreeAmalgam.functionClosedSet_iff
#print axioms StructuralRamsey.RelStructure.IsFreeAmalgam.left_preimage_right_range
#print axioms StructuralRamsey.RelStructure.IsFreeAmalgam.right_preimage_left_range
#print axioms StructuralRamsey.RelStructure.IsFreeAmalgam.left_closed_iff
#print axioms StructuralRamsey.RelStructure.IsFreeAmalgam.right_closed_iff
#print axioms StructuralRamsey.RelStructure.IsFreeAmalgam.sides_closed_iff
#print axioms StructuralRamsey.RelStructure.IsFreeAmalgam.common_image_closed_iff
#print axioms StructuralRamsey.Partite.HalfClosed.ramseyPartiteWitness
#print axioms StructuralRamsey.Structure.QuotientFibreObstruction.collapse_surjective
#print axioms StructuralRamsey.Structure.QuotientFibreObstruction.generated_image_exact
#print axioms StructuralRamsey.Structure.QuotientFibreObstruction.collapse_graph_hom
#print axioms StructuralRamsey.Structure.QuotientFibreObstruction.collapse_not_full_hom

#print axioms StructuralRamsey.Structure.LocallyGeneratedTreeCompletable.rootedWitness
#print axioms StructuralRamsey.Structure.FunctionalHistoryTreeLike.rootedWitness
#print axioms StructuralRamsey.Structure.LocallyClosedTreeCompletable.freeAmalgam_irreducibleRoot
#print axioms StructuralRamsey.Structure.HasTreeExtensionCompletion.of_embedding_into_base

#print axioms StructuralRamsey.RelStructure.FunctionClosedHasTreeCompletion.glue
#print axioms StructuralRamsey.RelStructure.FunctionClosedLocallyTreeCompletable.toFunctional
#print axioms StructuralRamsey.RelStructure.FunctionClosedLocallyTreeCompletable.of_treeAmalgam
#print axioms StructuralRamsey.RelStructure.FunctionClosedHasTreeCompletion.of_closedEmbedding
