import PartiteConstruction.Functional.FreeAmalgamClosed

#print axioms StructuralRamsey.RelStructure.Embedding.functionClosedSet_preimage
#print axioms StructuralRamsey.RelStructure.Embedding.functionClosed_iff_range
#print axioms StructuralRamsey.RelStructure.IsFreeAmalgam.functionClosedSet_iff
#print axioms StructuralRamsey.RelStructure.IsFreeAmalgam.left_preimage_right_range
#print axioms StructuralRamsey.RelStructure.IsFreeAmalgam.right_preimage_left_range
#print axioms StructuralRamsey.RelStructure.IsFreeAmalgam.left_closed_iff
#print axioms StructuralRamsey.RelStructure.IsFreeAmalgam.right_closed_iff
#print axioms StructuralRamsey.RelStructure.IsFreeAmalgam.sides_closed_iff
#print axioms StructuralRamsey.RelStructure.IsFreeAmalgam.common_image_closed_iff
