import PartiteConstruction.Structure.Basic

/-! # Free amalgamation and irreducibility with set-valued functions

For full structures, a free amalgam has no relation tuple or function-value
incidence crossing the two sides.  The universal characterization of
irreducibility says that every embedded copy of an irreducible structure in a
free amalgam lies wholly in one side.  For finite structures this is
equivalent to not being a free amalgam of two proper substructures, and unlike
the relational Gaifman shortcut it correctly sees closure generated by
function symbols.
-/
namespace StructuralRamsey.Structure

universe u v
variable {L : Language.{u}}
variable {U V W X : Type v}

/-- A full structure C is the free amalgam of A and B over D via the displayed
embeddings. Function values, just like relation tuples, come wholly from one
side. -/
structure IsFreeAmalgam
    {D : Structure L U} {A : Structure L V}
    {B : Structure L W} {C : Structure L X}
    (fA : Embedding D A) (fB : Embedding D B)
    (iA : Embedding A C) (iB : Embedding B C) : Prop where
  covers : ∀ z : X, (∃ a : V, z = iA a) ∨ (∃ b : W, z = iB b)
  overlap : ∀ a : V, ∀ b : W,
    iA a = iB b ↔ ∃ d : U, a = fA d ∧ b = fB d
  rel_iff : ∀ R z,
    C.rel R z ↔
      (∃ x : Fin (L.relArity R) → V,
        A.rel R x ∧ z = iA ∘ x) ∨
      (∃ y : Fin (L.relArity R) → W,
        B.rel R y ∧ z = iB ∘ y)
  func_iff : ∀ F x y,
    y ∈ C.func F x ↔
      (∃ a : Fin (L.funcArity F) → V, ∃ b : V,
        b ∈ A.func F a ∧ x = iA ∘ a ∧ y = iA b) ∨
      (∃ a : Fin (L.funcArity F) → W, ∃ b : W,
        b ∈ B.func F a ∧ x = iB ∘ a ∧ y = iB b)

/-- Irreducibility in the survey's free-amalgamation sense, in universal
no-crossing form: an embedded copy of A in any free amalgam lies wholly in one
side. For finite structures this is equivalent to A not being the free amalgam
of two proper substructures. -/
def Irreducible (A : Structure L U) : Prop :=
  ∀ {H E F C : Type v}
    {Dsrc : Structure L H} {Esrc : Structure L E}
    {Fsrc : Structure L F} {Csrc : Structure L C}
    {sE : Embedding Dsrc Esrc} {sF : Embedding Dsrc Fsrc}
    {iE : Embedding Esrc Csrc} {iF : Embedding Fsrc Csrc},
    IsFreeAmalgam sE sF iE iF →
    ∀ e : Embedding A Csrc,
      (∀ a : U, ∃ x : E, e a = iE x) ∨
      (∀ a : U, ∃ x : F, e a = iF x)

namespace IsFreeAmalgam

/-- The universal irreducibility predicate gives side localization directly. -/
theorem irreducible_side
    {A : Structure L U}
    (hA : Irreducible A)
    {H E F C : Type v}
    {Dsrc : Structure L H} {Esrc : Structure L E}
    {Fsrc : Structure L F} {Csrc : Structure L C}
    {sE : Embedding Dsrc Esrc} {sF : Embedding Dsrc Fsrc}
    {iE : Embedding Esrc Csrc} {iF : Embedding Fsrc Csrc}
    (hfree : IsFreeAmalgam sE sF iE iF)
    (e : Embedding A Csrc) :
    (∀ a : U, ∃ x : E, e a = iE x) ∨
      (∀ a : U, ∃ x : F, e a = iF x) :=
  hA hfree e

end IsFreeAmalgam

/-- Full homomorphism-embedding: a homomorphism whose composition with every
embedding of an irreducible structure is a full embedding. This is the
composition-friendly form of "restriction to every irreducible substructure
is an embedding". -/
def IsHomomorphismEmbedding (A : Structure L U) (B : Structure L V)
    (f : U → V) : Prop :=
  A.IsHomomorphism B f ∧
  ∀ {X : Type v} (E : Structure L X), Irreducible E →
    ∀ e : Embedding E A,
      ∃ g : Embedding E B, ∀ x, g x = f (e x)

namespace IsHomomorphismEmbedding

variable {A : Structure L U} {B : Structure L V} {C : Structure L W}
variable {f : U → V} {g : V → W}

theorem comp
    (hg : B.IsHomomorphismEmbedding C g)
    (hf : A.IsHomomorphismEmbedding B f) :
    A.IsHomomorphismEmbedding C (g ∘ f) := by
  constructor
  · exact hg.1.comp hf.1
  · intro X E hE e
    obtain ⟨eB, heB⟩ := hf.2 E hE e
    obtain ⟨eC, heC⟩ := hg.2 E hE eB
    refine ⟨eC, ?_⟩
    intro x
    rw [heC x, heB x]
    rfl

end IsHomomorphismEmbedding

namespace Embedding

variable {A : Structure L U} {B : Structure L V}

/-- Every full embedding is a homomorphism-embedding. -/
theorem isHomomorphismEmbedding (e : Embedding A B) :
    A.IsHomomorphismEmbedding B e := by
  constructor
  · exact e.isHomomorphism
  · intro X E hE f
    exact ⟨e.comp f, fun _ => rfl⟩

end Embedding

end StructuralRamsey.Structure
