import PartiteConstruction.Structure.GeneratedWeakHomImage

set_option autoImplicit false

/-! # The canonical root generated by nullary function values

For a structure with set-valued functions, the substructure generated by the
empty set is precisely the fixed part forced by nullary functions/constants
and everything obtained from them by further functions.

A full embedding carries this root *onto* the target root.  This is the formal
core of the standard reduction which removes constants before applying the
positive-arity Ramsey construction: fix the root, delete it from the moving
carrier, and encode incidences with the root by additional relational symbols.
-/
namespace StructuralRamsey.Structure

universe u v
variable {L : Language.{u}} {U V : Type v}

/-- The canonical fixed part of a structure: the closed hull of the empty set. -/
def nullaryRoot (A : Structure L U) : Set U :=
  A.functionClosure ∅

theorem nullaryRoot_isClosed (A : Structure L U) :
    A.IsClosed A.nullaryRoot :=
  A.functionClosure_isClosed ∅

/-- Every closed substructure contains the canonical root. -/
theorem nullaryRoot_subset_closed
    (A : Structure L U) {S : Set U} (hS : A.IsClosed S) :
    A.nullaryRoot ⊆ S := by
  intro x hx
  exact hx S hS (by simp)

/-- The image of a closed subset under a full embedding is closed. -/
theorem Embedding.image_isClosed
    {A : Structure L U} {B : Structure L V}
    (e : Embedding A B) {S : Set U} (hS : A.IsClosed S) :
    B.IsClosed (imageSet e S) := by
  classical
  intro F x hx y hy
  choose a haS hxa using hx
  have hxeq : x = e ∘ a := by
    funext i
    exact (hxa i).symm
  subst x
  rw [← e.map_func F a] at hy
  rcases hy with ⟨z, hz, hzy⟩
  have hzS : z ∈ S :=
    hS F a haS hz
  exact ⟨z, hzS, hzy⟩

/-- Full embeddings commute with taking function-generated closed hulls. -/
theorem Embedding.image_functionClosure
    {A : Structure L U} {B : Structure L V}
    (e : Embedding A B) (S : Set U) :
    imageSet e (A.functionClosure S) =
      B.functionClosure (imageSet e S) := by
  ext y
  constructor
  · rintro ⟨x, hx, rfl⟩
    let T : Set U :=
      {a | e a ∈ B.functionClosure (imageSet e S)}
    have hT : A.IsClosed T := by
      exact e.preimage_isClosed
        (B.functionClosure (imageSet e S))
        (B.functionClosure_isClosed (imageSet e S))
    have hST : S ⊆ T := by
      intro s hs
      exact B.subset_functionClosure (imageSet e S) ⟨s, hs, rfl⟩
    exact hx T hT hST
  · intro hy
    apply hy
      (imageSet e (A.functionClosure S))
      (e.image_isClosed (A.functionClosure_isClosed S))
    rintro _ ⟨s, hs, rfl⟩
    exact ⟨s, A.subset_functionClosure S hs, rfl⟩

/-- Every full embedding maps the fixed/nullary root onto the target root. -/
theorem Embedding.image_nullaryRoot
    {A : Structure L U} {B : Structure L V}
    (e : Embedding A B) :
    imageSet e A.nullaryRoot = B.nullaryRoot := by
  rw [nullaryRoot, nullaryRoot, e.image_functionClosure]
  have hEmpty : imageSet e (∅ : Set U) = (∅ : Set V) := by
    ext y
    simp [imageSet]
  rw [hEmpty]

/-- Pointwise form of surjectivity on the canonical root. -/
theorem Embedding.nullaryRoot_surjective
    {A : Structure L U} {B : Structure L V}
    (e : Embedding A B) :
    ∀ y ∈ B.nullaryRoot,
      ∃ x ∈ A.nullaryRoot, e x = y := by
  intro y hy
  have hy' : y ∈ imageSet e A.nullaryRoot := by
    rw [e.image_nullaryRoot]
    exact hy
  rcases hy' with ⟨x, hx, rfl⟩
  exact ⟨x, hx, rfl⟩

/-- The canonical root is exactly the part common to every closed substructure. -/
theorem mem_nullaryRoot_iff
    (A : Structure L U) (x : U) :
    x ∈ A.nullaryRoot ↔
      ∀ S : Set U, A.IsClosed S → x ∈ S := by
  constructor
  · intro hx S hS
    exact nullaryRoot_subset_closed A hS hx
  · intro hx
    exact hx A.nullaryRoot (A.nullaryRoot_isClosed)

end StructuralRamsey.Structure
