import PartiteConstruction.Structure.RootedEmbedding
import PartiteConstruction.Ramsey.FreeAmalgamationFunctions
import Mathlib.Order.Hom.Set

set_option autoImplicit false

/-! # The canonical fixed root and rigidity of ordered root maps -/
namespace StructuralRamsey.Rooted

open StructuralRamsey Structure

universe u v
variable {L : Language.{u}} {U V : Type v}

/-- The canonical root generated by the nullary values. -/
abbrev canonicalRoot (A : Structure L U) : Structure L A.nullaryRoot :=
  A.induce A.nullaryRoot A.nullaryRoot_isClosed

/-- Canonical root inclusion. -/
def canonicalRootEmbedding (A : Structure L U) :
    Structure.Embedding (canonicalRoot A) A :=
  Structure.inclusion A A.nullaryRoot A.nullaryRoot_isClosed

@[simp] theorem canonicalRootEmbedding_apply
    (A : Structure L U) (x : A.nullaryRoot) :
    canonicalRootEmbedding A x = x.1 := rfl

theorem canonicalRootEmbedding_range (A : Structure L U) :
    Set.range (canonicalRootEmbedding A) = A.nullaryRoot := by
  ext x
  constructor
  · rintro ⟨r, rfl⟩
    exact r.2
  · intro hx
    exact ⟨⟨x, hx⟩, rfl⟩

/-- A full embedding sends the canonical root inclusion onto the target
canonical root. -/
theorem canonicalRoot_image_range
    {A : Structure L U} {B : Structure L V}
    (e : Structure.Embedding A B) :
    Set.range (e ∘ canonicalRootEmbedding A) = B.nullaryRoot := by
  ext y
  constructor
  · rintro ⟨r, rfl⟩
    have hy :
        e r.1 ∈ Structure.imageSet e A.nullaryRoot :=
      ⟨r.1, r.2, rfl⟩
    rw [e.image_nullaryRoot] at hy
    exact hy
  · intro hy
    have hy' : y ∈ Structure.imageSet e A.nullaryRoot := by
      rw [e.image_nullaryRoot]
      exact hy
    rcases hy' with ⟨x, hx, hxy⟩
    exact ⟨⟨x, hx⟩, hxy⟩

theorem canonicalRootEmbedding_strictMono
    (A : Structure L U) [LinearOrder U] :
    StrictMono (canonicalRootEmbedding A) := by
  intro x y hxy
  exact hxy

/-- Two ordered embeddings A -> B agree on the canonical root.  Both are
strictly increasing bijections from the ordered source root onto the same
ordered target root, hence are equal there. -/
theorem orderedEmbedding_agrees_on_root
    {A : Structure L U} {B : Structure L V}
    [Finite U] [LinearOrder U] [Finite V] [LinearOrder V]
    (e₀ e : Structure.Embedding A.withLinearOrder B.withLinearOrder) :
    ∀ r : A.nullaryRoot,
      e.linearOrderReduct (canonicalRootEmbedding A r) =
        e₀.linearOrderReduct (canonicalRootEmbedding A r) := by
  let f : A.nullaryRoot → V :=
    e.linearOrderReduct ∘ canonicalRootEmbedding A
  let g : A.nullaryRoot → V :=
    e₀.linearOrderReduct ∘ canonicalRootEmbedding A
  have hf : StrictMono f :=
    e.strictMono.comp (canonicalRootEmbedding_strictMono A)
  have hg : StrictMono g :=
    e₀.strictMono.comp (canonicalRootEmbedding_strictMono A)
  have hfr : Set.range f = B.nullaryRoot :=
    canonicalRoot_image_range e.linearOrderReduct
  have hgr : Set.range g = B.nullaryRoot :=
    canonicalRoot_image_range e₀.linearOrderReduct
  have hfg : f = g :=
    hf.eq_of_range_eq hg (hfr.trans hgr.symm)
  intro r
  exact congrFun hfg r

end StructuralRamsey.Rooted
