import PartiteConstruction.Ramsey.ClosureClosedCompletionRank

/-! # Projected generating supports for the rank step

Positive relational maps take the source closure of S INTO the target
closure of f[S]. Equality of these two sets is neither assumed nor needed.
In particular, a map out of a structure generated by S factors through
the closed target hull of the EXACT projected support f[S].

The hull has U-size at most |f[S]|. A collision of two distinct generators
therefore gives a strict rank drop. No bound on the number of vertices
of a hull is asserted. The original weak image is not declared closed.
Completions use the explicitly named closed-test convention.
-/

namespace StructuralRamsey.RelStructure

universe u v
variable {L : RelLanguage.{u}} {U V W : Type v}

/-- Preimages of relative U-substructures need only a positive map,
not a full embedding or any reflection of relation tuples. -/
theorem IsUSubstructure.preimage_homomorphism
    {rules : ClosureDescription L}
    {A : RelStructure L U} {B : RelStructure L V}
    {T : Set V} {f : U → V}
    (hT : IsUSubstructure rules B T)
    (hf : A.IsHomomorphism B f) :
    IsUSubstructure rules A (f ⁻¹' T) := by
  intro rule hrule t ht hRoot j
  exact hT rule hrule (f ∘ t) (hf rule.symbol t ht) hRoot j

/-- Closure transport uses only inclusion. It does not say that f[S]
is closed, that f reflects missing outputs, or that f is injective. -/
theorem IsHomomorphism.image_UClosureHull_subset
    {rules : ClosureDescription L}
    {A : RelStructure L U} {B : RelStructure L V} {f : U → V}
    (hf : A.IsHomomorphism B f) (S : Set U) :
    f '' UClosureHull rules A S ⊆ UClosureHull rules B (f '' S) := by
  let T : Set V := UClosureHull rules B (f '' S)
  have hT : IsUSubstructure rules B T :=
    UClosureHull_isUSubstructure rules B (f '' S)
  have hS : S ⊆ f ⁻¹' T := by
    intro x hx
    exact subset_UClosureHull rules B (f '' S) ⟨x, hx, rfl⟩
  have hHull : UClosureHull rules A S ⊆ f ⁻¹' T :=
    UClosureHull_minimal rules A (hT.preimage_homomorphism hf) hS
  rintro y ⟨x, hx, rfl⟩
  exact hHull hx

/-- All projected vertices lie in the hull of the projected generators.
No closedness of either structure is required for this assertion. -/
theorem IsHomomorphism.range_subset_generatedHull
    {rules : ClosureDescription L}
    {A : RelStructure L U} {B : RelStructure L V} {f : U → V}
    (hf : A.IsHomomorphism B f) (S : Set U)
    (hGen : IsUGenerating rules A S) :
    Set.range f ⊆ UClosureHull rules B (f '' S) := by
  rintro y ⟨x, rfl⟩
  have hx : x ∈ UClosureHull rules A S := by
    rw [hGen]
    trivial
  exact hf.image_UClosureHull_subset S ⟨x, hx, rfl⟩

/-- The hull of the whole projected source equals the hull of the
projected generators. This is equality of HULLS, not of weak images. -/
theorem IsHomomorphism.generatedHull_eq_rangeHull
    {rules : ClosureDescription L}
    {A : RelStructure L U} {B : RelStructure L V} {f : U → V}
    (hf : A.IsHomomorphism B f) (S : Set U)
    (hGen : IsUGenerating rules A S) :
    UClosureHull rules B (f '' S) = UClosureHull rules B (Set.range f) := by
  apply Set.Subset.antisymm
  · apply UClosureHull_mono
    rintro y ⟨x, _, rfl⟩
    exact ⟨x, rfl⟩
  · exact UClosureHull_minimal rules B
      (UClosureHull_isUSubstructure rules B (f '' S))
      (hf.range_subset_generatedHull S hGen)

/-- Closed-test maps factor through the projected-generator hull;
the map remains the original f on every vertex. -/
theorem IsClosedUHomomorphismEmbedding.to_generatedHull
    {rules : ClosureDescription L}
    {A : RelStructure L U} {B : RelStructure L V} {f : U → V}
    (hf : IsClosedUHomomorphismEmbedding rules A B f)
    (S : Set U) (hGen : IsUGenerating rules A S) :
    ∃ p : U → UClosureHull rules B (f '' S),
      IsClosedUHomomorphismEmbedding rules A
        (B.induce (UClosureHull rules B (f '' S))) p ∧
      ∀ x, (p x).1 = f x := by
  have hRange (x : U) : f x ∈ UClosureHull rules B (f '' S) :=
    hf.1.range_subset_generatedHull S hGen ⟨x, rfl⟩
  exact ⟨fun x => ⟨f x, hRange x⟩,
    hf.codRestrict (UClosureHull rules B (f '' S)) hRange,
    fun _ => rfl⟩

/-- Completion maps can be precomposed by another closed-test map.
The finite target and its class membership are unchanged. -/
theorem HasClosedUKCompletion.precomp_closedMap
    {K : StructureClass.{u,v} (L := L)} {rules : ClosureDescription L}
    {A : RelStructure L U} {B : RelStructure L V} {f : U → V}
    (hB : HasClosedUKCompletion K rules B)
    (hf : IsClosedUHomomorphismEmbedding rules A B f) :
    HasClosedUKCompletion K rules A := by
  obtain ⟨X, hX, Target, hK, hIrred, g, hg⟩ := hB
  exact ⟨X, hX, Target, hK, hIrred, g ∘ f, hg.comp hf⟩

/-- Two distinct generators with the same image reduce the size of
the exact projected support. The proof deletes one redundant generator. -/
theorem projected_generator_card_lt [DecidableEq V]
    (G : Finset U) (f : U → V)
    {x y : U} (hx : x ∈ G) (hy : y ∈ G)
    (hxy : x ≠ y) (hImage : f x = f y) :
    (G.image f).card < G.card := by
  classical
  have hErase : G.image f = (G.erase x).image f := by
    ext z
    constructor
    · intro hz
      obtain ⟨a, ha, haz⟩ := Finset.mem_image.mp hz
      by_cases hax : a = x
      · subst a
        exact Finset.mem_image.mpr
          ⟨y, Finset.mem_erase.mpr ⟨hxy.symm, hy⟩, hImage.symm.trans haz⟩
      · exact Finset.mem_image.mpr
          ⟨a, Finset.mem_erase.mpr ⟨hax, ha⟩, haz⟩
    · intro hz
      obtain ⟨a, ha, haz⟩ := Finset.mem_image.mp hz
      exact Finset.mem_image.mpr ⟨a, (Finset.mem_erase.mp ha).2, haz⟩
  have hBound : ((G.erase x).image f).card ≤ (G.erase x).card :=
    Finset.card_image_le
  have hCard := Finset.card_erase_of_mem hx
  have hPos : 0 < G.card := Finset.card_pos.mpr ⟨x, hx⟩
  rw [hErase]
  omega

/-- Projected-generator rank criterion: rank control in one finite
closed ambient B yields a completion of A as soon as its projected
generating support has size at most n. No bound on |A| is assumed. -/
theorem HasClosedUKCompletion.of_projected_generators
    {K : StructureClass.{u,v} (L := L)} {rules : ClosureDescription L}
    {A : RelStructure L U} {B : RelStructure L V} {f : U → V}
    [Finite V] [DecidableEq V]
    (hB : IsUClosed rules B)
    (hf : IsClosedUHomomorphismEmbedding rules A B f)
    (G : Finset U) (hGen : IsUGenerating rules A (↑G : Set U))
    (n : ℕ)
    (hRank : ∀ (T : Set V) [Fintype T],
      IsUClosed rules (B.induce T) →
      USize rules (B.induce T) ≤ n →
        HasClosedUKCompletion K rules (B.induce T))
    (hBudget : (G.image f).card ≤ n) :
    HasClosedUKCompletion K rules A := by
  classical
  let T : Set V := UClosureHull rules B (↑(G.image f) : Set V)
  letI : Fintype T := Fintype.ofFinite T
  have hT : IsUClosed rules (B.induce T) :=
    hB.induce_UClosureHull (↑(G.image f) : Set V)
  have hSize : USize rules (B.induce T) ≤ (G.image f).card :=
    USize_induce_UClosureHull_le rules B (G.image f)
  have hCT := hRank T hT (hSize.trans hBudget)
  have hRange (x : U) : f x ∈ T := by
    change f x ∈ UClosureHull rules B (↑(G.image f) : Set V)
    rw [Finset.coe_image]
    exact hf.1.range_subset_generatedHull (↑G : Set U) hGen ⟨x, rfl⟩
  exact hCT.precomp_closedMap (hf.codRestrict T hRange)

/-- The collision branch of the j-to-j+1 argument: a generating set
of size at most j+1 with two identified generators maps into a closed
hull of rank at most j, so the preceding rank hypothesis applies. -/
theorem HasClosedUKCompletion.of_generator_collision
    {K : StructureClass.{u,v} (L := L)} {rules : ClosureDescription L}
    {A : RelStructure L U} {B : RelStructure L V} {f : U → V}
    [Finite V] [DecidableEq V]
    (hB : IsUClosed rules B)
    (hf : IsClosedUHomomorphismEmbedding rules A B f)
    (G : Finset U) (hGen : IsUGenerating rules A (↑G : Set U))
    (j : ℕ) (hCard : G.card ≤ j + 1)
    (hRank : ∀ (T : Set V) [Fintype T],
      IsUClosed rules (B.induce T) →
      USize rules (B.induce T) ≤ j →
        HasClosedUKCompletion K rules (B.induce T))
    {x y : U} (hx : x ∈ G) (hy : y ∈ G)
    (hxy : x ≠ y) (hImage : f x = f y) :
    HasClosedUKCompletion K rules A := by
  have hDrop := projected_generator_card_lt G f hx hy hxy hImage
  apply HasClosedUKCompletion.of_projected_generators hB hf G hGen j hRank
  omega

end StructuralRamsey.RelStructure
