import PartiteConstruction.Ramsey.ClosureProtectedPictureStep
import PartiteConstruction.Ramsey.ClosureIrreducibleHulls
import PartiteConstruction.Ramsey.ClosureProjectedGenerators

/-! # Native power projection on irreducibly generated tests

A test generated by an ordinarily irreducible induced seed has an embedded
part projection in the positive coordinatewise power. The test need not be
closed. We work in the ACTUAL tagged induced power, not a surrogate product.

At each coordinate, ordinary homomorphism-embedding reflects the seed.
Positive closure transport puts the image of the whole test inside the
closure of that coordinate seed. The old protected map embeds this closed
hull. Relation reflection follows in every coordinate; injectivity of
part labels follows by checking equality at ALL coordinates.

The stronger assertion for *all* closed U-irreducible tests requires a
structural generator theorem. It is not silently inferred or added as
an axiom.
-/

namespace StructuralRamsey.Partite.Induced

open RelStructure
universe u v
variable {L : RelLanguage.{u}}
variable {P V E : Type v} {N : ℕ}

/-- A positive power's part map is a full embedding on any test whose
original vertices are U-generated by an ordinary irreducible seed. -/
theorem part_embedding_on_irreducibly_generated_test
    {rules : ClosureDescription L}
    {A : RelStructure L P}
    (B : System L P V)
    (hBClosed : IsUClosed rules B.toRelStructure)
    (hBPart : IsClosedUHomomorphismEmbedding rules
      B.toRelStructure A B.part)
    (hN : 0 < N)
    (Test : RelStructure L E)
    (e : RelStructure.Embedding Test (power B N).toRelStructure)
    (S : Set E) (hSeed : (Test.induce S).Irreducible)
    (hGen : IsUGenerating rules Test S) :
    ∃ d : RelStructure.Embedding Test A,
      ∀ x, d x = (power B N).part (e x) := by
  classical
  let Pwr := power B N
  have hPartOrdinary : B.IsPartiteOver A :=
    StructuralRamsey.RelStructure.IsClosedUHomomorphismEmbedding.toHomomorphismEmbedding_of_closed
      hBPart hBClosed
  have hPerCoord (k : Fin N) :
      (∀ x y : E, Pwr.part (e x) = Pwr.part (e y) →
        (e x).coord k = (e y).coord k) ∧
      (∀ (R : L.Symbol) (z : Fin (L.arity R) → E),
        A.rel R (fun j => Pwr.part (e (z j))) →
        B.rel R (fun j => (e (z j)).coord k)) := by
    let f : E → V := fun x => (e x).coord k
    have hf : Test.IsHomomorphismEmbedding B.toRelStructure f :=
      (coordinate_isHomomorphismEmbedding B hPartOrdinary k).comp
        e.isHomomorphismEmbedding
    obtain ⟨dSeed, hdSeed⟩ := hf.embeddingOn S hSeed
    have hImage : Set.range dSeed = f '' S := by
      ext x
      constructor
      · rintro ⟨y, rfl⟩
        exact ⟨y.1, y.2, (hdSeed y).symm⟩
      · rintro ⟨y, hy, rfl⟩
        exact ⟨⟨y, hy⟩, hdSeed ⟨y, hy⟩⟩
    have hIrredImage : (B.toRelStructure.induce (f '' S)).Irreducible := by
      rw [← hImage]
      exact hSeed.range_embedding dSeed
    let H : Set V := UClosureHull rules B.toRelStructure (f '' S)
    obtain ⟨dH, hdH⟩ :=
      hBPart.on_irreducibleSeed_hull hBClosed (f '' S) hIrredImage
    have hIn (x : E) : f x ∈ H :=
      hf.1.range_subset_generatedHull S hGen ⟨x, rfl⟩
    let dTest : E → H := fun x => ⟨f x, hIn x⟩
    have hPart (x : E) : dH (dTest x) = Pwr.part (e x) := by
      calc
        dH (dTest x) = B.part (f x) := hdH (dTest x)
        _ = Pwr.part (e x) := (e x).belongs k
    constructor
    · intro x y hxy
      have hd : dH (dTest x) = dH (dTest y) :=
        (hPart x).trans (hxy.trans (hPart y).symm)
      exact congrArg Subtype.val (dH.injective hd)
    · intro R z hA
      have hAT : A.rel R (dH ∘ (dTest ∘ z)) := by
        convert hA using 1
        funext j
        exact (hPart (z j)).symm
      have hBT : (B.toRelStructure.induce H).rel R (dTest ∘ z) :=
        (dH.map_rel_iff R (dTest ∘ z)).mp hAT
      exact hBT
  let d : RelStructure.Embedding Test A := {
    toFun := fun x => Pwr.part (e x)
    injective := by
      intro x y hxy
      apply e.injective
      apply NonInduced.Vertex.ext B
      · exact hxy
      · intro k
        exact (hPerCoord k).1 x y hxy
    map_rel_iff := by
      intro R z
      constructor
      · intro hA
        have hp : Pwr.rel R (e ∘ z) := by
          intro k
          exact (hPerCoord k).2 R z hA
        exact (e.map_rel_iff R z).mp hp
      · intro hT
        have hp : Pwr.rel R (e ∘ z) :=
          (e.map_rel_iff R z).mpr hT
        exact (power_projection_homomorphism hPartOrdinary hN)
          R (e ∘ z) hp
  }
  exact ⟨d, fun _ => rfl⟩

/-- Singleton generation is a concrete nontrivial special case. -/
theorem part_embedding_on_singleton_generated_test
    {rules : ClosureDescription L} {A : RelStructure L P}
    (B : System L P V)
    (hBClosed : IsUClosed rules B.toRelStructure)
    (hBPart : IsClosedUHomomorphismEmbedding rules
      B.toRelStructure A B.part)
    (hN : 0 < N)
    (Test : RelStructure L E)
    (e : RelStructure.Embedding Test (power B N).toRelStructure)
    (x : E) (hGen : IsUGenerating rules Test {x}) :
    ∃ d : RelStructure.Embedding Test A,
      ∀ y, d y = (power B N).part (e y) := by
  have hSeed : (Test.induce {x}).Irreducible := by
    intro a b hab
    exfalso
    apply hab
    apply Subtype.ext
    exact (Set.mem_singleton_iff.mp a.2).trans
      (Set.mem_singleton_iff.mp b.2).symm
  exact part_embedding_on_irreducibly_generated_test
    B hBClosed hBPart hN Test e {x} hSeed hGen

/-- A precise *conditional* upgrade to protectedness of every positive
power. The structural seed-existence hypothesis is left explicit. -/
theorem power_part_protected_of_irreducible_generators
    {rules : ClosureDescription L} {A : RelStructure L P}
    (B : System L P V)
    (hBClosed : IsUClosed rules B.toRelStructure)
    (hBPart : IsClosedUHomomorphismEmbedding rules
      B.toRelStructure A B.part)
    (hN : 0 < N)
    (hSeed : ∀ {X : Type v} (Test : RelStructure L X),
      IsUClosed rules Test → IsUIrreducible rules Test →
      ∃ S : Set X, (Test.induce S).Irreducible ∧
        IsUGenerating rules Test S) :
    IsClosedUHomomorphismEmbedding rules
      (power B N).toRelStructure A (power B N).part := by
  constructor
  · have hOrd : B.IsPartiteOver A :=
      StructuralRamsey.RelStructure.IsClosedUHomomorphismEmbedding.toHomomorphismEmbedding_of_closed
        hBPart hBClosed
    exact power_projection_homomorphism hOrd hN
  · intro X Test hClosed hIrred e
    obtain ⟨S, hIrr, hGen⟩ := hSeed Test hClosed hIrred
    exact part_embedding_on_irreducibly_generated_test
      B hBClosed hBPart hN Test e S hIrr hGen

end StructuralRamsey.Partite.Induced
