import PartiteConstruction.Ramsey.ClosureGeneratedHullRank

/-! # Correct U-size transfer from weak induced sources to ambient hulls

The observation after Definition 2.25 of the published 2019 paper
asserts that a possibly NONCLOSED induced weak substructure B0 has the
same U-size as its ambient U-closure. A three-vertex counterexample
in docs/theorem218-U-size-closure-strict-drop.md disproves equality:
intrinsic U-size 2 can decrease to U-size 1 in the ambient closure.

The generally valid replacement is one-sided. Any minimum generating
set G of the exact induced B0 also generates its ambient U-hull.
Indeed, any relative U-substructure of ambient A containing G,
intersected with B0, is relatively closed inside B0; hence it contains
B0 and consequently its ambient hull. Thus

  USize (A induced on cl_U^A(S)) <= USize(A induced on S).

The proof preserves the exact weak carrier, makes no false equality
claim, and uses neither full U-closedness of ambient A nor K
completions. It improves the earlier safe bound by |S| to a bound by
the MINIMAL intrinsic generating-set cardinality of weak S.
-/

namespace StructuralRamsey.RelStructure

universe u v
variable {L : RelLanguage.{u}} {V : Type v}

/-- An intrinsic generating set G of a weak induced substructure
also generates its entire AMBIENT closure. The two ambient hull sets
are equal even when the weak induced substructure or the ambient
structure is not intrinsically U-closed. -/
theorem UClosureHull_of_induce_generators_eq
    (rules : ClosureDescription L)
    (A : RelStructure L V) (S : Set V) (G : Set S)
    (hGen : IsUGenerating rules (A.induce S) G) :
    UClosureHull rules A (Subtype.val '' G) =
      UClosureHull rules A S := by
  let H : Set V := UClosureHull rules A (Subtype.val '' G)
  have hH : IsUSubstructure rules A H :=
    UClosureHull_isUSubstructure rules A (Subtype.val '' G)
  have hPre : IsUSubstructure rules (A.induce S)
      (Subtype.val ⁻¹' H) :=
    hH.preimage_embedding (inclusion A S)
  have hGPre : G ⊆ (Subtype.val ⁻¹' H) := by
    intro g hg
    exact subset_UClosureHull rules A (Subtype.val '' G)
      ⟨g, hg, rfl⟩
  have hS : S ⊆ H := by
    intro x hx
    have hAll : (⟨x, hx⟩ : S) ∈
        UClosureHull rules (A.induce S) G := by
      rw [hGen]
      trivial
    exact UClosureHull_minimal rules (A.induce S)
      hPre hGPre hAll
  apply Set.Subset.antisymm
  · apply UClosureHull_mono rules A
    rintro x ⟨g, hg, rfl⟩
    exact g.2
  · exact UClosureHull_minimal rules A hH hS

/-- Correct finite U-size inequality under ambient closure of a weak
induced structure. Equality is NOT valid in general. In particular,
the ambient closed hull does not have to be generated by all the
original weak vertices: a minimum intrinsic generating set suffices. -/
theorem USize_induce_ambient_hull_le_weak
    [Fintype V]
    (rules : ClosureDescription L)
    (A : RelStructure L V) (S : Set V)
    [Fintype S] [Fintype (UClosureHull rules A S)] :
    USize rules (A.induce (UClosureHull rules A S)) ≤
      USize rules (A.induce S) := by
  classical
  let H : Set V := UClosureHull rules A S
  letI : Fintype S := Fintype.ofFinite S
  letI : Fintype H := Fintype.ofFinite H
  obtain ⟨G, hGCard, hGGen⟩ := USize_spec rules (A.induce S)
  let e : S ↪ H := {
    toFun := fun s => ⟨s.1, subset_UClosureHull rules A S s.2⟩
    inj' := by
      intro x y hxy
      apply Subtype.ext
      exact congrArg (fun z : H => z.1) hxy
  }
  let GH : Finset H := G.map e
  have hHullEq : UClosureHull rules A
      (Subtype.val '' (↑G : Set S)) = H :=
    UClosureHull_of_induce_generators_eq rules A S (↑G : Set S) hGGen
  have hOnH : IsUGenerating rules (A.induce H)
      {x : H | x.1 ∈ Subtype.val '' (↑G : Set S)} := by
    have h := UClosureHull_induce_generated rules A
      (Subtype.val '' (↑G : Set S))
    rw [hHullEq] at h
    exact h
  have hSet : (↑GH : Set H) =
      {x : H | x.1 ∈ Subtype.val '' (↑G : Set S)} := by
    ext x
    constructor
    · intro hx
      obtain ⟨s, hs, hse⟩ := Finset.mem_map.mp hx
      exact ⟨s, hs, congrArg Subtype.val hse⟩
    · rintro ⟨s, hs, hse⟩
      apply Finset.mem_map.mpr
      refine ⟨s, hs, ?_⟩
      apply Subtype.ext
      exact hse
  have hGenH : IsUGenerating rules (A.induce H) (↑GH : Set H) := by
    rw [hSet]
    exact hOnH
  calc
    USize rules (A.induce H) ≤ GH.card :=
      USize_le_of_generating rules (A.induce H) GH hGenH
    _ = G.card := by simp [GH]
    _ = USize rules (A.induce S) := hGCard

end StructuralRamsey.RelStructure
