import PartiteConstruction.Ramsey.ClosureWeakProjectedRankGlue
import PartiteConstruction.Ramsey.ClosureFreeAmalgamGenerators

/-!
# Accounting for the generating rank of the actual closed boundary

The free-amalgam rank argument gives smaller generating supports for
each side AFTER adjoining the entire common root. That does not
automatically give an absolute rank drop, because the projected root
may have positive and arbitrarily large U-size.

This file proves the *correct* budget calculation. If the projected
separator already lies in the closure of q chosen vertices of D, and
a side can be generated over that separator by t vertices, then its
ENTIRE projected image lies in the closure of at most q+t
specified vertices. Consequently the previous rank-j completion
invariant applies when q+t<=j, and independent side completions
glue over the same closed K-boundary.

The theorem does not assume that q=0, does not infer the budget from
a generic source free cut, and does not assert the full rank
j-to-j+1 increment. It is an explicit auxiliary result for the
multi-line Hales--Jewett branch left open by the corrected proof.
-/

namespace StructuralRamsey.RelStructure

universe u v
variable {L : RelLanguage.{u}}
variable {U V : Type v}

/-- A side generated by finite or infinite S OVER a boundary Root
projects entirely into any target U-hull containing both the images
of S and Root. No ambient U-closedness or source injectivity is used.
This is the exact relative-generation counterpart of
`IsHomomorphism.range_subset_generatedHull`. -/
theorem IsHomomorphism.range_in_hull_of_relative_generators
    {rules : ClosureDescription L}
    {A : RelStructure L U} {B : RelStructure L V}
    {f : U → V}
    (hf : A.IsHomomorphism B f)
    (S Root : Set U)
    (hGen : IsUGenerating rules A (S ∪ Root))
    (J : Set V)
    (hS : ∀ x, x ∈ S → f x ∈ UClosureHull rules B J)
    (hRoot : ∀ x, x ∈ Root → f x ∈ UClosureHull rules B J) :
    Set.range f ⊆ UClosureHull rules B J := by
  let H : Set V := UClosureHull rules B J
  have hH : IsUSubstructure rules B H :=
    UClosureHull_isUSubstructure rules B J
  have hPre : IsUSubstructure rules A (f ⁻¹' H) :=
    hH.preimage_homomorphism hf
  have hSeeds : S ∪ Root ⊆ f ⁻¹' H := by
    intro x hx
    rcases hx with hx | hx
    · exact hS x hx
    · exact hRoot x hx
  have hAll : ∀ x : U, f x ∈ H := by
    intro x
    have hx : x ∈ UClosureHull rules A (S ∪ Root) := by
      rw [hGen]
      trivial
    exact UClosureHull_minimal rules A hPre hSeeds hx
  rintro y ⟨x, rfl⟩
  exact hAll x

variable {H E F C : Type v}
variable {Root : RelStructure L H}
variable {Left : RelStructure L E}
variable {Right : RelStructure L F}
variable {Whole : RelStructure L C}
variable {sL : Embedding Root Left} {sR : Embedding Root Right}
variable {iL : Embedding Left Whole} {iR : Embedding Right Whole}

/-- Correct absolute projected-rank criterion obtained by ADDING
the generator budgets for a shared boundary and each side.

The source is an exact weak free amalgam with relative U-closed
side ranges. The boundary generator support J0 need not contain
the separator vertices themselves: its TARGET hull must contain
their images. For each side, the intrinsic relative generating
set SL (respectively SR) generates that side AFTER adding the
actual common root.

The two numerical assumptions are
    |J0| + |SL| <= j,   |J0| + |SR| <= j.
These yield the two genuine absolute target supports
    J0 union p(iL[SL]),   J0 union p(iR[SR])
whose sizes are at most j. There is no claim that the
relative supports alone suffice when J0 has positive cost. -/
theorem HasClosedUKCompletion.of_boundary_and_relative_generator_budgets
    {K : StructureClass.{u,v} (L := L)}
    (rules : ClosureDescription L)
    (hK : HasFiniteStrongAmalgamation K)
    (hHereditary : ∀ {X Y : Type v}
      {T : RelStructure L X} {B : RelStructure L Y},
      K B → IsUClosed rules T → Embedding T B → K T)
    (hKIrr : ∀ {X : Type v} (B : RelStructure L X),
      K B → B.Irreducible)
    {UA : Type v} {A : RelStructure L UA}
    {D : RelStructure L V}
    [Finite V] [DecidableEq V]
    (hFree : IsFreeAmalgam sL sR iL iR)
    (hL : IsUSubstructure rules Whole (Set.range iL))
    (hR : IsUSubstructure rules Whole (Set.range iR))
    (hKA : K A) (hA : IsUClosed rules A)
    (hD : IsUClosed rules D)
    (a : Embedding A D)
    (p : C → V)
    (hp : IsClosedUHomomorphismEmbedding rules Whole D p)
    (hSeparator : ∀ r : H, p (iL (sL r)) ∈ Set.range a)
    (J0 : Finset V)
    (hJ0 : ∀ r : H,
      p (iL (sL r)) ∈ UClosureHull rules D (↑J0 : Set V))
    (SL : Finset E) (SR : Finset F)
    (hGenL : IsUGenerating rules Left
      ((↑SL : Set E) ∪ Set.range sL))
    (hGenR : IsUGenerating rules Right
      ((↑SR : Set F) ∪ Set.range sR))
    (j : ℕ)
    (hBudgetL : J0.card + SL.card ≤ j)
    (hBudgetR : J0.card + SR.card ≤ j)
    (hRank : ∀ (T : Set V) [Fintype T],
      IsUClosed rules (D.induce T) →
      USize rules (D.induce T) ≤ j →
        HasClosedUKCompletion K rules (D.induce T)) :
    HasClosedUKCompletion K rules Whole := by
  classical
  let JL : Finset V := J0 ∪ SL.image (p ∘ iL)
  let JR : Finset V := J0 ∪ SR.image (p ∘ iR)
  have hJL : JL.card ≤ j := by
    calc
      JL.card ≤ J0.card + (SL.image (p ∘ iL)).card :=
        Finset.card_union_le J0 (SL.image (p ∘ iL))
      _ ≤ J0.card + SL.card :=
        Nat.add_le_add_left Finset.card_image_le J0.card
      _ ≤ j := hBudgetL
  have hJR : JR.card ≤ j := by
    calc
      JR.card ≤ J0.card + (SR.image (p ∘ iR)).card :=
        Finset.card_union_le J0 (SR.image (p ∘ iR))
      _ ≤ J0.card + SR.card :=
        Nat.add_le_add_left Finset.card_image_le J0.card
      _ ≤ j := hBudgetR
  have hJ0L : (↑J0 : Set V) ⊆ (↑JL : Set V) := by
    intro x hx
    exact Finset.mem_union.mpr (Or.inl hx)
  have hJ0R : (↑J0 : Set V) ⊆ (↑JR : Set V) := by
    intro x hx
    exact Finset.mem_union.mpr (Or.inl hx)
  have hRootEq (r : H) : p (iL (sL r)) = p (iR (sR r)) := by
    apply congrArg p
    exact (hFree.overlap (sL r) (sR r)).mpr ⟨r, rfl, rfl⟩
  have hRootL (x : E) (hx : x ∈ Set.range sL) :
      p (iL x) ∈ UClosureHull rules D (↑JL : Set V) := by
    obtain ⟨r, rfl⟩ := hx
    exact (UClosureHull_mono rules D hJ0L) (hJ0 r)
  have hRootR (x : F) (hx : x ∈ Set.range sR) :
      p (iR x) ∈ UClosureHull rules D (↑JR : Set V) := by
    obtain ⟨r, rfl⟩ := hx
    rw [← hRootEq r]
    exact (UClosureHull_mono rules D hJ0R) (hJ0 r)
  have hSeedL (x : E) (hx : x ∈ (↑SL : Set E)) :
      p (iL x) ∈ UClosureHull rules D (↑JL : Set V) := by
    apply subset_UClosureHull rules D (↑JL : Set V)
    change p (iL x) ∈ JL
    exact Finset.mem_union.mpr
      (Or.inr (Finset.mem_image.mpr ⟨x, hx, rfl⟩))
  have hSeedR (x : F) (hx : x ∈ (↑SR : Set F)) :
      p (iR x) ∈ UClosureHull rules D (↑JR : Set V) := by
    apply subset_UClosureHull rules D (↑JR : Set V)
    change p (iR x) ∈ JR
    exact Finset.mem_union.mpr
      (Or.inr (Finset.mem_image.mpr ⟨x, hx, rfl⟩))
  have hProjL : Set.range (p ∘ iL) ⊆
      UClosureHull rules D (↑JL : Set V) :=
    IsHomomorphism.range_in_hull_of_relative_generators
      (hp.precomp_embedding iL).1
      (↑SL : Set E) (Set.range sL) hGenL
      (↑JL : Set V) hSeedL hRootL
  have hProjR : Set.range (p ∘ iR) ⊆
      UClosureHull rules D (↑JR : Set V) :=
    IsHomomorphism.range_in_hull_of_relative_generators
      (hp.precomp_embedding iR).1
      (↑SR : Set F) (Set.range sR) hGenR
      (↑JR : Set V) hSeedR hRootR
  have hRangeL (x : E) :
      p (iL x) ∈ UClosureHull rules D (↑JL : Set V) :=
    hProjL ⟨x, rfl⟩
  have hRangeR (x : F) :
      p (iR x) ∈ UClosureHull rules D (↑JR : Set V) :=
    hProjR ⟨x, rfl⟩
  exact HasClosedUKCompletion.of_common_projection_supports_relative
    rules hK hHereditary hKIrr hFree hL hR
    hKA hA hD a p hp hSeparator JL JR j
    hJL hJR hRangeL hRangeR hRank

end StructuralRamsey.RelStructure
