import PartiteConstruction.Ramsey.ClosureClosedCover
import PartiteConstruction.Ramsey.ClosureIrreducibleHulls

/-! # Closed irreducible homomorphic image hulls

The five-vertex obstruction rules out a universal ordinary irreducible
GENERATING SEED. It does not rule out transporting closed irreducibility
by pulling back a free decomposition of the TARGET.

If a closed target is generated by the image of a positive homomorphism
from a closed U-irreducible source, it is U-irreducible. The preimages of
its two closed free-amalgam sides are closed source substructures and
freely cover the source. Source irreducibility puts the image in one side;
generation then puts the entire target in that side.

No finiteness, injectivity, relation reflection, ordinary irreducible seed,
or equality between the raw image and its closure hull is assumed.
The source must be U-closed: this does NOT repair the literal nonclosed
tests of published Definition 2.15 or Definition 2.17(4b).
-/

namespace StructuralRamsey.RelStructure

universe u v
variable {L : RelLanguage.{u}} {U V : Type v}

/-- A closed target generated by a homomorphic image of a closed
U-irreducible source is U-irreducible. -/
theorem IsUClosed.uIrreducible_of_homomorphic_generators
    {rules : ClosureDescription L}
    {Source : RelStructure L U} {Target : RelStructure L V}
    (hTarget : IsUClosed rules Target)
    (hSource : IsUClosed rules Source)
    (hIrred : IsUIrreducible rules Source)
    {f : U → V} (hf : Source.IsHomomorphism Target f)
    (hGen : IsUGenerating rules Target (Set.range f)) :
    IsUIrreducible rules Target := by
  intro H E F Root Left Right sL sR iL iR hLeft hRight hFree
  have hL : IsUSubstructure rules Target (Set.range iL) :=
    iL.range_isUSubstructure hLeft hTarget
  have hR : IsUSubstructure rules Target (Set.range iR) :=
    iR.range_isUSubstructure hRight hTarget
  have hCover : ∀ x : U,
      x ∈ f ⁻¹' Set.range iL ∨ x ∈ f ⁻¹' Set.range iR := by
    intro x
    rcases hFree.covers (f x) with ⟨a, ha⟩ | ⟨b, hb⟩
    · exact Or.inl ⟨a, ha.symm⟩
    · exact Or.inr ⟨b, hb.symm⟩
  have hTuples : ∀ R (z : Fin (L.arity R) → U), Source.rel R z →
      (∀ k, z k ∈ f ⁻¹' Set.range iL) ∨
      (∀ k, z k ∈ f ⁻¹' Set.range iR) := by
    intro R z hz
    rcases (hFree.rel_iff R (f ∘ z)).mp (hf R z hz) with
        ⟨a, _, ha⟩ | ⟨b, _, hb⟩
    · left
      intro k
      exact ⟨a k, (congrFun ha k).symm⟩
    · right
      intro k
      exact ⟨b k, (congrFun hb k).symm⟩
  rcases hIrred.closed_cover hSource
      (f ⁻¹' Set.range iL) (f ⁻¹' Set.range iR)
      (hL.preimage_homomorphism hf) (hR.preimage_homomorphism hf)
      hCover hTuples with hInLeft | hInRight
  · left
    have hRange : Set.range f ⊆ Set.range iL := by
      rintro y ⟨x, rfl⟩
      exact hInLeft x
    have hHull := UClosureHull_minimal rules Target hL hRange
    intro y
    apply hHull
    rw [hGen]
    trivial
  · right
    have hRange : Set.range f ⊆ Set.range iR := by
      rintro y ⟨x, rfl⟩
      exact hInRight x
    have hHull := UClosureHull_minimal rules Target hR hRange
    intro y
    apply hHull
    rw [hGen]
    trivial

/-- The closed hull of the entire homomorphic image is U-irreducible.
The exact raw image is neither asserted induced nor asserted closed. -/
theorem IsUClosed.homomorphic_image_hull_isUIrreducible
    {rules : ClosureDescription L}
    {Source : RelStructure L U} {Target : RelStructure L V}
    (hSource : IsUClosed rules Source)
    (hIrred : IsUIrreducible rules Source)
    (hTarget : IsUClosed rules Target)
    {f : U → V} (hf : Source.IsHomomorphism Target f) :
    IsUIrreducible rules
      (Target.induce (UClosureHull rules Target (Set.range f))) := by
  let S : Set V := Set.range f
  let T : Set V := UClosureHull rules Target S
  let g : U → T := fun x =>
    ⟨f x, subset_UClosureHull rules Target S ⟨x, rfl⟩⟩
  have hg : Source.IsHomomorphism (Target.induce T) g := by
    intro R z hz
    exact hf R z hz
  have hRange : Set.range g = {x : T | x.1 ∈ S} := by
    ext x
    constructor
    · rintro ⟨y, rfl⟩
      exact ⟨y, rfl⟩
    · rintro ⟨y, hy⟩
      exact ⟨y, Subtype.ext hy⟩
  have hGen : IsUGenerating rules (Target.induce T) (Set.range g) := by
    rw [hRange]
    exact UClosureHull_induce_generated rules Target S
  intro H E F Root Left Right sL sR iL iR hLeft hRight hFree
  exact (hTarget.induce_UClosureHull S).uIrreducible_of_homomorphic_generators
    hSource hIrred hg hGen hLeft hRight hFree

end StructuralRamsey.RelStructure
