import PartiteConstruction.Ramsey.ClosureIrreducibleHulls

/-! # The rank-one base and ordinary weak-test completions

A closed structure of U-size at most one is generated by an ordinary
irreducible seed (possibly empty), hence is a protected U-irreducible test.
Coverage of protected tests by a finite irreducible K-member therefore
provides the first positive rank invariant without a rank-zero oracle.

A second consequence of irreducible hull protection strengthens weak-test
extraction: complete the CLOSED hull first, recover an ordinary relational
homomorphism-embedding on that closed hull, and only then restrict it to
the original weak test. This retains the same finite K-target. It does not
claim that an arbitrary closed-test map with a NONCLOSED source is ordinary,
nor that ordinary completion is the literal 2019 U-completion condition.
-/

namespace StructuralRamsey.RelStructure

universe u v
variable {L : RelLanguage.{u}} {U V W : Type v}

/-- Rank at most one, including zero, implies intrinsic U-irreducibility
for a closed structure. The generating seed may be empty. -/
theorem IsUClosed.uIrreducible_of_USize_le_one
    {rules : ClosureDescription L} {A : RelStructure L U}
    [Fintype U] (hA : IsUClosed rules A)
    (hRank : USize rules A ≤ 1) : IsUIrreducible rules A := by
  classical
  obtain ⟨G, hCard, hGen⟩ := USize_spec rules A
  have hSmall : G.card ≤ 1 := hCard.le.trans hRank
  have hSeed : (A.induce (↑G : Set U)).Irreducible := by
    intro x y hxy
    apply False.elim
    apply hxy
    apply Subtype.ext
    exact Finset.card_le_one.mp hSmall x.1 x.2 y.1 y.2
  let e : Embedding (A.induce (↑G : Set U)) A :=
    inclusion A (↑G : Set U)
  have hRange : Set.range e = (↑G : Set U) := by
    ext x
    constructor
    · rintro ⟨y, rfl⟩
      exact y.2
    · intro hx
      exact ⟨⟨x, hx⟩, rfl⟩
  have hGenerated : IsUGenerating rules A (Set.range e) := by
    rw [hRange]
    exact hGen
  intro H E F Root Left Right sL sR iL iR hLeft hRight hFree
  exact hA.uIrreducible_of_irreducible_generators
    hSeed e hGenerated hLeft hRight hFree

/-- Protected-copy coverage supplies all closed rank-one completions.
The coverage itself must come from the actual Picture construction;
this lemma does not assume that arbitrary pictures satisfy it. -/
theorem closed_rank_one_completions_of_protected_coverage
    {K : StructureClass.{u,v} (L := L)} {rules : ClosureDescription L}
    {C : RelStructure L U} {Base : RelStructure L V}
    [Finite V] (hK : K Base) (hBase : Base.Irreducible)
    (hCoverage : ∀ {E : Type v} (Test : RelStructure L E),
      IsUClosed rules Test → IsUIrreducible rules Test →
      Embedding Test C → Nonempty (Embedding Test Base))
    (S : Set U) [Fintype S]
    (hClosed : IsUClosed rules (C.induce S))
    (hRank : USize rules (C.induce S) ≤ 1) :
    HasClosedUKCompletion K rules (C.induce S) := by
  obtain ⟨e⟩ := hCoverage (C.induce S) hClosed
    (hClosed.uIrreducible_of_USize_le_one hRank) (inclusion C S)
  exact ⟨V, inferInstance, Base, hK, hBase,
    e, e.isClosedUHomomorphismEmbedding rules⟩

/-- A closed-test completion of a CLOSED structure induces an ordinary
completion of any weak structure embedded into it, with the SAME target. -/
theorem HasClosedUKCompletion.ordinary_pullback_from_closed
    {K : StructureClass.{u,v} (L := L)} {rules : ClosureDescription L}
    {A : RelStructure L U} {B : RelStructure L V}
    (hB : HasClosedUKCompletion K rules B)
    (hClosed : IsUClosed rules B) (e : Embedding A B) :
    ∃ (X : Type v) (_ : Finite X) (Target : RelStructure L X),
      K Target ∧ Target.Irreducible ∧
      ∃ f : U → X, A.IsHomomorphismEmbedding Target f := by
  obtain ⟨X, hX, Target, hK, hIrred, f, hf⟩ := hB
  exact ⟨X, hX, Target, hK, hIrred, f ∘ e,
    (hf.toHomomorphismEmbedding_of_closed hClosed).comp
      e.isHomomorphismEmbedding⟩

/-- Closed rank-n completion control yields ORDINARY completions of
all exact weak n-vertex tests. No hereditary-completion oracle is an input.
The test itself is not enlarged and need not be U-closed. -/
theorem ordinary_weak_completions_of_closed_USize
    {K : StructureClass.{u,v} (L := L)}
    [Finite U] (rules : ClosureDescription L) (A : RelStructure L U)
    (hA : IsUClosed rules A) (n : ℕ)
    (hRank : ∀ (T : Set U) [Fintype T],
      IsUClosed rules (A.induce T) →
      USize rules (A.induce T) ≤ n →
        HasClosedUKCompletion K rules (A.induce T))
    (S : Finset U) (hS : S.card ≤ n) :
    ∃ (X : Type v) (_ : Finite X) (Target : RelStructure L X),
      K Target ∧ Target.Irreducible ∧
      ∃ f : (↑S : Set U) → X,
        (A.induce (↑S : Set U)).IsHomomorphismEmbedding Target f := by
  classical
  let T : Set U := UClosureHull rules A (↑S : Set U)
  letI : Fintype T := Fintype.ofFinite T
  have hClosed : IsUClosed rules (A.induce T) :=
    hA.induce_UClosureHull (↑S : Set U)
  have hSize : USize rules (A.induce T) ≤ n :=
    (USize_induce_UClosureHull_le rules A S).trans hS
  have hCompleted := hRank T hClosed hSize
  let e : Embedding (A.induce (↑S : Set U)) (A.induce T) := {
    toFun := fun x => ⟨x.1, subset_UClosureHull rules A (↑S : Set U) x.2⟩
    injective := by
      intro x y h
      apply Subtype.ext
      exact congrArg (fun z : T => z.1) h
    map_rel_iff := fun _ _ => Iff.rfl
  }
  exact hCompleted.ordinary_pullback_from_closed hClosed e

end StructuralRamsey.RelStructure
