import PartiteConstruction.Ramsey.ClosureMaximalWeakRank
import PartiteConstruction.Ramsey.ClosureWeakHullUSize

/-!
# Minimum ambient U-generators form a maximally independent weak test

A U-CLOSED test T of U-size j+1 may have far more than j+1
vertices. The exact substructure on any MINIMUM generating set
of T, however, has precisely j+1 vertices and intrinsic U-size
j+1. It is therefore closure-independent: every subset is a
relative U-substructure of this weak generating test.

The proof uses the correct ambient-hull transport from #206:
if a smaller set G generated the induced weak structure on the
minimum support S, then G would generate the SAME ambient hull
as S, contradicting the minimality of S.

This explains how a closed-rank argument could be reduced to the
exact weak j+1-vertex geometry. But it is NOT a completion
extension theorem: a K-completion of the weak induced generator
set need not respect the ORIGINAL closure tuples of T outside
that set. To prove Lemma 2.30 by this alternative route, one
must also construct a completion of the entire generated hull
(or establish a rooted completion invariant preserving those
closure tuples). The present two theorems do not assume that.
-/

namespace StructuralRamsey.RelStructure

universe u v
variable {L : RelLanguage.{u}} {V : Type v}

/-- Any minimum generating support S in a finite relational
structure has MAXIMAL intrinsic U-rank in its induced weak
structure. Neither ambient U-closedness nor a target K-class
is necessary. -/
theorem USize_induce_minimal_generator_eq_card
    [Fintype V]
    (rules : ClosureDescription L) (A : RelStructure L V)
    (S : Finset V)
    (hGen : IsUGenerating rules A (↑S : Set V))
    (hMinimal : S.card = USize rules A) :
    USize rules (A.induce (↑S : Set V)) = S.card := by
  classical
  let Sset : Set V := ↑S
  obtain ⟨G, hCardG, hGenG⟩ :=
    USize_spec rules (A.induce Sset)
  let emb : Sset ↪ V :=
    ⟨Subtype.val, Subtype.val_injective⟩
  let H : Finset V := G.map emb
  have hImage :
      (↑H : Set V) = Subtype.val '' (↑G : Set Sset) := by
    ext x
    constructor
    · intro hx
      obtain ⟨y, hy, hxy⟩ := Finset.mem_map.mp hx
      exact ⟨y, hy, hxy⟩
    · rintro ⟨y, hy, hxy⟩
      exact Finset.mem_map.mpr ⟨y, hy, hxy⟩
  have hHGen : IsUGenerating rules A (↑H : Set V) := by
    change UClosureHull rules A (↑H : Set V) = Set.univ
    rw [hImage]
    rw [UClosureHull_of_induce_generators_eq
      rules A Sset (↑G : Set Sset) hGenG]
    exact hGen
  have hLower : S.card ≤ USize rules (A.induce Sset) := by
    calc
      S.card = USize rules A := hMinimal
      _ ≤ H.card := USize_le_of_generating rules A H hHGen
      _ = G.card := by simp [H]
      _ = USize rules (A.induce Sset) := hCardG
  have hUpper : USize rules (A.induce Sset) ≤ S.card := by
    simpa [Sset] using USize_le_card rules (A.induce Sset)
  exact Nat.le_antisymm hUpper hLower

/-- The exact weak structure on an AMBIENT MINIMUM U-generating
support is closure-independent. This says nothing about the
larger ambient closed hull generated by this support. -/
theorem minimal_generator_weak_all_subsets_relative
    [Fintype V]
    (rules : ClosureDescription L) (A : RelStructure L V)
    (S : Finset V)
    (hGen : IsUGenerating rules A (↑S : Set V))
    (hMinimal : S.card = USize rules A) :
    ∀ T : Set (↑S : Set V),
      IsUSubstructure rules (A.induce (↑S : Set V)) T := by
  have hMax : USize rules (A.induce (↑S : Set V)) =
      Fintype.card (↑S : Set V) := by
    simpa using
      USize_induce_minimal_generator_eq_card
        rules A S hGen hMinimal
  exact all_subsets_relative_of_USize_eq_card rules
    (A.induce (↑S : Set V)) hMax

end StructuralRamsey.RelStructure
