import PartiteConstruction.Ramsey.ClosureTwoSideSmallProjection
import PartiteConstruction.Ramsey.ClosureClosedLocalFiniteness

/-!
# The shared generated K-boundary is forced by two A-letter factorizations

The two-side projection gluing lemma requires a fixed closed member
Q∈K generated by the image of its source separator. The actual
transverse Hales--Jewett geometry (#223) naturally produces a
part map q:Root→A and two (potentially different) induced copies
aL,aR:A→D of ONE selected closed A∈K, not a preconstructed Q.

This module proves that the required Q is the literal U-closure of
q[Root] INSIDE A. Since A is U-closed, its induced closure Q
is U-closed; since K is closed-U-hereditary, Q is a member of K.
The exact root map into Q generates it by construction. The two
old A-letter embeddings restrict to embeddings Q→D, and both
side root compatibilities remain true.

Therefore, if the two weak source sides have distinct protected
maps into the same closed old picture D and size at most j,
the previous closed rank-j completion invariant suffices to
complete their free union, without an extra generated-Q oracle.

The theorem does not build the two side projections from an
arbitrary native multi-line Picture history; that is still the
substantial geometric obligation in repaired Lemma 2.30.
-/

namespace StructuralRamsey.RelStructure

universe u v
variable {L : RelLanguage.{u}}
variable {H E F C V P : Type v}
variable {Root : RelStructure L H}
variable {Left : RelStructure L E}
variable {Right : RelStructure L F}
variable {Whole : RelStructure L C}
variable {D : RelStructure L V}
variable {A : RelStructure L P}
variable {sL : Embedding Root Left}
variable {sR : Embedding Root Right}
variable {iL : Embedding Left Whole}
variable {iR : Embedding Right Whole}

/-- If both protected small sides have root values factoring
through two copies of the same U-closed A∈K, the common K-boundary
is not an additional hypothesis: it is the exact closure
of the root's A-parts INSIDE A.

The source, its two sides and its root may all be nonclosed.
Only the two side ranges inside the source must be relatively
U-closed. No projected U-rank saving on either side is assumed
beyond its actual ≤j VERTEX cardinality. -/
theorem HasClosedUKCompletion.of_two_small_side_projections_via_A
    {K : StructureClass.{u,v} (L := L)}
    (rules : ClosureDescription L)
    (hK : HasFiniteStrongAmalgamation K)
    (hHer : ClosedUHereditary K rules)
    (hKIrr : ∀ {Z : Type v} (T : RelStructure L Z),
      K T → T.Irreducible)
    (hSrc : IsFreeAmalgam sL sR iL iR)
    (hRelL : IsUSubstructure rules Whole (Set.range iL))
    (hRelR : IsUSubstructure rules Whole (Set.range iR))
    [Fintype E] [Fintype F] [Finite V] [Finite P]
    (hDClosed : IsUClosed rules D)
    (hAK : K A) (hAClosed : IsUClosed rules A)
    (q : H → P)
    (pL : E → V) (pR : F → V)
    (hpL : IsClosedUHomomorphismEmbedding rules Left D pL)
    (hpR : IsClosedUHomomorphismEmbedding rules Right D pR)
    (aL aR : Embedding A D)
    (hRootL : ∀ r : H, pL (sL r) = aL (q r))
    (hRootR : ∀ r : H, pR (sR r) = aR (q r))
    (j : ℕ)
    (hCardL : Fintype.card E ≤ j)
    (hCardR : Fintype.card F ≤ j)
    (hRank : ∀ (T : Set V) [Fintype T],
      IsUClosed rules (D.induce T) →
      USize rules (D.induce T) ≤ j →
        HasClosedUKCompletion K rules (D.induce T)) :
    HasClosedUKCompletion K rules Whole := by
  classical
  let S : Set P := Set.range q
  let T : Set P := UClosureHull rules A S
  let Q : RelStructure L T := A.induce T
  have hQClosed : IsUClosed rules Q :=
    hAClosed.induce_UClosureHull S
  have hQK : K Q :=
    hHer Q A hAK hQClosed (inclusion A T)
  let qQ : H → T := fun r =>
    ⟨q r, subset_UClosureHull rules A S ⟨r, rfl⟩⟩
  have hRange : Set.range qQ = {x : T | x.1 ∈ S} := by
    ext x
    constructor
    · rintro ⟨r, rfl⟩
      exact ⟨r, rfl⟩
    · rintro ⟨r, hr⟩
      refine ⟨r, ?_⟩
      apply Subtype.ext
      exact hr
  have hQGen : IsUGenerating rules Q (Set.range qQ) := by
    rw [hRange]
    exact UClosureHull_induce_generated rules A S
  let aLQ : Embedding Q D := aL.comp (inclusion A T)
  let aRQ : Embedding Q D := aR.comp (inclusion A T)
  have hRootLQ (r : H) : pL (sL r) = aLQ (qQ r) := by
    exact hRootL r
  have hRootRQ (r : H) : pR (sR r) = aRQ (qQ r) := by
    exact hRootR r
  exact HasClosedUKCompletion.of_two_small_side_projections
    rules hK hKIrr hSrc hRelL hRelR
    hDClosed hQK hQClosed
    qQ hQGen pL pR hpL hpR aLQ aRQ hRootLQ hRootRQ
    j hCardL hCardR hRank

end StructuralRamsey.RelStructure
