import PartiteConstruction.Ramsey.ClosureProjectedGenerators
import PartiteConstruction.Ramsey.ClosureEmbeddingRange

/-! # Irreducible seeds and their protected closure hulls

The positive construction protects closed U-irreducible tests. On a
U-closed source this already protects the closure of every ORDINARY
irreducible seed: a free decomposition into closed sides localizes the
seed in one side, and its generators then force the entire hull there.

Consequently a working closed-test map out of a U-closed source is an
ordinary relational homomorphism-embedding. Its restriction to the hull
of an irreducible seed is a full embedding. If the target is U-closed
as well, the image of that hull is EXACTLY the target hull of the seed's
image. The seed itself is not assumed closed, and its raw weak image is
not declared closed. The equality is NOT asserted for arbitrary seeds.

This does not identify the working map with the literal 2019 predicate,
which also tests intrinsically U-irreducible nonclosed substructures.
-/

namespace StructuralRamsey.RelStructure

universe u v
variable {L : RelLanguage.{u}} {U V W : Type v}

/-- A closed structure generated by an embedded ordinary irreducible
seed is intrinsically U-irreducible. No finiteness is needed. -/
theorem IsUClosed.uIrreducible_of_irreducible_generators
    {rules : ClosureDescription L}
    {A : RelStructure L U} {Seed : RelStructure L V}
    (hA : IsUClosed rules A) (hSeed : Seed.Irreducible)
    (e : Embedding Seed A)
    (hGen : IsUGenerating rules A (Set.range e)) :
    IsUIrreducible rules A := by
  intro H E F Root Left Right sL sR iL iR hLeft hRight hFree
  have hTest : (A.induce (Set.range e)).Irreducible :=
    hSeed.range_embedding e
  rcases hFree.irreducible_side (Set.range e) hTest with hL | hR
  · left
    have hSeedL : Set.range e ⊆ Set.range iL := by
      intro x hx
      obtain ⟨a, ha⟩ := hL ⟨x, hx⟩
      exact ⟨a, ha.symm⟩
    have hHull := UClosureHull_minimal rules A
      (iL.range_isUSubstructure hLeft hA) hSeedL
    intro x
    have hx : x ∈ UClosureHull rules A (Set.range e) := by
      rw [hGen]
      trivial
    exact hHull hx
  · right
    have hSeedR : Set.range e ⊆ Set.range iR := by
      intro x hx
      obtain ⟨a, ha⟩ := hR ⟨x, hx⟩
      exact ⟨a, ha.symm⟩
    have hHull := UClosureHull_minimal rules A
      (iR.range_isUSubstructure hRight hA) hSeedR
    intro x
    have hx : x ∈ UClosureHull rules A (Set.range e) := by
      rw [hGen]
      trivial
    exact hHull hx

/-- Closing an ordinary irreducible induced seed in a closed source
gives a protected closed U-irreducible test on the actual hull carrier. -/
theorem IsUClosed.irreducibleSeed_hull_isUIrreducible
    {rules : ClosureDescription L} {A : RelStructure L U}
    (hA : IsUClosed rules A) (S : Set U)
    (hS : (A.induce S).Irreducible) :
    IsUIrreducible rules (A.induce (UClosureHull rules A S)) := by
  let T : Set U := UClosureHull rules A S
  let e : Embedding (A.induce S) (A.induce T) := {
    toFun := fun x => ⟨x.1, subset_UClosureHull rules A S x.2⟩
    injective := by
      intro x y h
      apply Subtype.ext
      exact congrArg (fun z : T => z.1) h
    map_rel_iff := fun _ _ => Iff.rfl
  }
  have hRange : Set.range e = {x : T | x.1 ∈ S} := by
    ext x
    constructor
    · rintro ⟨y, rfl⟩
      exact y.2
    · intro hx
      exact ⟨⟨x.1, hx⟩, Subtype.ext rfl⟩
  have hGen : IsUGenerating rules (A.induce T) (Set.range e) := by
    rw [hRange]
    exact UClosureHull_induce_generated rules A S
  intro H E F Root Left Right sL sR iL iR hLeft hRight hFree
  exact (hA.induce_UClosureHull S).uIrreducible_of_irreducible_generators
    hS e hGen hLeft hRight hFree

/-- A working map is a full embedding on the entire closure of an
ordinary irreducible seed, even when that seed omits closure outputs. -/
theorem IsClosedUHomomorphismEmbedding.on_irreducibleSeed_hull
    {rules : ClosureDescription L}
    {A : RelStructure L U} {B : RelStructure L V} {f : U → V}
    (hf : IsClosedUHomomorphismEmbedding rules A B f)
    (hA : IsUClosed rules A) (S : Set U)
    (hS : (A.induce S).Irreducible) :
    ∃ e : Embedding (A.induce (UClosureHull rules A S)) B,
      ∀ x, e x = f x.1 := by
  exact hf.on_test (A.induce (UClosureHull rules A S))
    (hA.induce_UClosureHull S)
    (hA.irreducibleSeed_hull_isUIrreducible S hS)
    (inclusion A (UClosureHull rules A S))

/-- The stronger working closed-test condition on a CLOSED source
implies the ordinary relational homomorphism-embedding condition.
It still need not imply the literal intrinsic 2019 U-test predicate. -/
theorem IsClosedUHomomorphismEmbedding.toHomomorphismEmbedding_of_closed
    {rules : ClosureDescription L}
    {A : RelStructure L U} {B : RelStructure L V} {f : U → V}
    (hf : IsClosedUHomomorphismEmbedding rules A B f)
    (hA : IsUClosed rules A) :
    A.IsHomomorphismEmbedding B f := by
  refine ⟨hf.1, ?_⟩
  intro S hS
  let T : Set U := UClosureHull rules A S
  obtain ⟨g, hg⟩ := hf.on_irreducibleSeed_hull hA S hS
  let e : Embedding (A.induce S) (A.induce T) := {
    toFun := fun x => ⟨x.1, subset_UClosureHull rules A S x.2⟩
    injective := by
      intro x y h
      apply Subtype.ext
      exact congrArg (fun z : T => z.1) h
    map_rel_iff := fun _ _ => Iff.rfl
  }
  exact ⟨g.comp e, fun x => hg (e x)⟩

/-- No collisions occur inside the hull of an ordinary irreducible
seed. Collisions between different hulls are not ruled out. -/
theorem IsClosedUHomomorphismEmbedding.injOn_irreducibleSeed_hull
    {rules : ClosureDescription L}
    {A : RelStructure L U} {B : RelStructure L V} {f : U → V}
    (hf : IsClosedUHomomorphismEmbedding rules A B f)
    (hA : IsUClosed rules A) (S : Set U)
    (hS : (A.induce S).Irreducible) :
    Set.InjOn f (UClosureHull rules A S) := by
  obtain ⟨g, hg⟩ := hf.on_irreducibleSeed_hull hA S hS
  intro x hx y hy hxy
  have he : g ⟨x, hx⟩ = g ⟨y, hy⟩ :=
    (hg ⟨x, hx⟩).trans (hxy.trans (hg ⟨y, hy⟩).symm)
  exact congrArg Subtype.val (g.injective he)

/-- For an ordinary irreducible seed, and closed source and target,
the map commutes EXACTLY with closure. This equality concerns the
image of the source HULL, not the raw image f[S]. -/
theorem IsClosedUHomomorphismEmbedding.image_irreducibleSeed_hull_eq
    {rules : ClosureDescription L}
    {A : RelStructure L U} {B : RelStructure L V} {f : U → V}
    (hf : IsClosedUHomomorphismEmbedding rules A B f)
    (hA : IsUClosed rules A) (hB : IsUClosed rules B)
    (S : Set U) (hS : (A.induce S).Irreducible) :
    f '' UClosureHull rules A S = UClosureHull rules B (f '' S) := by
  let T : Set U := UClosureHull rules A S
  obtain ⟨g, hg⟩ := hf.on_irreducibleSeed_hull hA S hS
  have hRange : Set.range g = f '' T := by
    ext y
    constructor
    · rintro ⟨x, rfl⟩
      exact ⟨x.1, x.2, (hg x).symm⟩
    · rintro ⟨x, hx, rfl⟩
      exact ⟨⟨x, hx⟩, hg ⟨x, hx⟩⟩
  have hClosed : IsUSubstructure rules B (f '' T) := by
    rw [← hRange]
    exact g.range_isUSubstructure (hA.induce_UClosureHull S) hB
  apply Set.Subset.antisymm
  · exact hf.1.image_UClosureHull_subset S
  · apply UClosureHull_minimal rules B hClosed
    rintro y ⟨x, hx, rfl⟩
    exact ⟨x, subset_UClosureHull rules A S hx, rfl⟩

/-- Every singleton is an ordinary irreducible seed, including a
vertex which is not itself closed under the closure rules. -/
theorem IsUClosed.singleton_hull_isUIrreducible
    {rules : ClosureDescription L} {A : RelStructure L U}
    (hA : IsUClosed rules A) (a : U) :
    IsUIrreducible rules (A.induce (UClosureHull rules A {a})) := by
  apply hA.irreducibleSeed_hull_isUIrreducible
  intro x y hxy
  apply False.elim
  apply hxy
  apply Subtype.ext
  exact (Set.mem_singleton_iff.mp x.2).trans
    (Set.mem_singleton_iff.mp y.2).symm

end StructuralRamsey.RelStructure
