import PartiteConstruction.Ramsey.ClosureRelativeMapGlue
import PartiteConstruction.Ramsey.ClosureProjectedGenerators
import PartiteConstruction.Ramsey.ClosureGeneratedHullRank

/-!
# Gluing two DIFFERENT small side projections over a generated K-boundary

The actual Hales--Jewett no-common-coordinate case cannot use one
global coordinate retraction into the old picture. Different source
pieces may nevertheless admit DIFFERENT protected maps into the same
old closed picture D. Their boundary images may be embedded into
different copies of one fixed closed K-boundary Q.

Here is the exact compatible-completion principle, independent of
any global side projection or rank of the boundary Q:

* Whole is a free amalgam of two exact weak sides, with relatively
  U-closed side ranges.
* Each side admits its OWN closed-test protected positive map to D.
* The shared source root factors through one map q : Root -> Q,
  then through two (possibly different) full embeddings Q -> D.
* Q belongs to K, is U-closed, and is generated by q[Root].
* Each side has AT MOST j vertices.
* Every closed induced substructure of D of U-size <= j has a
  corrected K-completion.

Take the ambient D-closures of the ENTIRE two side images. Since each
side has <=j vertices, both target hulls have U-size <=j. Because
q[Root] generates Q and both side images include the corresponding
root images, the two embedded copies of Q factor into their respective
target hulls. Complete those hulls independently and strongly
amalgamate over Q using the checked relative-source gluing theorem.

This can prove a genuinely mixed weak-cardinality step if actual
Picture histories supply the two separate side projections and their
boundary factorization. Those geometric claims are NOT axioms here
and have not yet been derived from every Hales--Jewett history.
-/

namespace StructuralRamsey.RelStructure

universe u v
variable {L : RelLanguage.{u}}
variable {H E F C V P : Type v}
variable {Root : RelStructure L H}
variable {Left : RelStructure L E}
variable {Right : RelStructure L F}
variable {Whole : RelStructure L C}
variable {D : RelStructure L V}
variable {Q : RelStructure L P}
variable {sL : Embedding Root Left} {sR : Embedding Root Right}
variable {iL : Embedding Left Whole} {iR : Embedding Right Whole}

/-- Completion using two DIFFERENT small protected side maps and a
shared generated closed K-boundary. Neither source root nor source
sides need be U-closed. The side size bounds are actual vertex
cardinal bounds, not assumed bounds on the (larger) target hulls. -/
theorem HasClosedUKCompletion.of_two_small_side_projections
    {K : StructureClass.{u,v} (L := L)}
    (rules : ClosureDescription L)
    (hK : HasFiniteStrongAmalgamation K)
    (hKIrr : ∀ {Z : Type v} (T : RelStructure L Z),
      K T → T.Irreducible)
    (hSrc : IsFreeAmalgam sL sR iL iR)
    (hRelL : IsUSubstructure rules Whole (Set.range iL))
    (hRelR : IsUSubstructure rules Whole (Set.range iR))
    [Fintype E] [Fintype F] [Finite V] [Finite P]
    (hDClosed : IsUClosed rules D)
    (hQK : K Q) (hQClosed : IsUClosed rules Q)
    (q : H → P)
    (hQGenerated : IsUGenerating rules Q (Set.range q))
    (pL : E → V) (pR : F → V)
    (hpL : IsClosedUHomomorphismEmbedding rules Left D pL)
    (hpR : IsClosedUHomomorphismEmbedding rules Right D pR)
    (aL aR : Embedding Q D)
    (hRootL : ∀ r : H, pL (sL r) = aL (q r))
    (hRootR : ∀ r : H, pR (sR r) = aR (q r))
    (j : ℕ)
    (hCardL : Fintype.card E ≤ j)
    (hCardR : Fintype.card F ≤ j)
    (hRank : ∀ (T : Set V) [Fintype T],
      IsUClosed rules (D.induce T) →
      USize rules (D.induce T) ≤ j →
      HasClosedUKCompletion K rules (D.induce T)) :
    HasClosedUKCompletion K rules Whole := by
  classical
  letI : Fintype V := Fintype.ofFinite V
  let GL : Finset V := Finset.univ.image pL
  let GR : Finset V := Finset.univ.image pR
  let TL : Set V := UClosureHull rules D (↑GL : Set V)
  let TR : Set V := UClosureHull rules D (↑GR : Set V)
  letI : Fintype TL := Fintype.ofFinite TL
  letI : Fintype TR := Fintype.ofFinite TR
  have hRangeL (x : E) : pL x ∈ TL :=
    subset_UClosureHull rules D (↑GL : Set V)
      (Finset.mem_image.mpr ⟨x, Finset.mem_univ x, rfl⟩)
  have hRangeR (x : F) : pR x ∈ TR :=
    subset_UClosureHull rules D (↑GR : Set V)
      (Finset.mem_image.mpr ⟨x, Finset.mem_univ x, rfl⟩)
  have hQRangeL (x : P) : aL x ∈ TL := by
    have hClosedTL : IsUSubstructure rules D TL :=
      UClosureHull_isUSubstructure rules D (↑GL : Set V)
    have hPre : IsUSubstructure rules Q (aL ⁻¹' TL) :=
      hClosedTL.preimage_embedding aL
    have hQSeeds : Set.range q ⊆ aL ⁻¹' TL := by
      rintro y ⟨r, rfl⟩
      rw [← hRootL r]
      exact hRangeL (sL r)
    have hx : x ∈ UClosureHull rules Q (Set.range q) := by
      rw [hQGenerated]
      trivial
    exact UClosureHull_minimal rules Q hPre hQSeeds hx
  have hQRangeR (x : P) : aR x ∈ TR := by
    have hClosedTR : IsUSubstructure rules D TR :=
      UClosureHull_isUSubstructure rules D (↑GR : Set V)
    have hPre : IsUSubstructure rules Q (aR ⁻¹' TR) :=
      hClosedTR.preimage_embedding aR
    have hQSeeds : Set.range q ⊆ aR ⁻¹' TR := by
      rintro y ⟨r, rfl⟩
      rw [← hRootR r]
      exact hRangeR (sR r)
    have hx : x ∈ UClosureHull rules Q (Set.range q) := by
      rw [hQGenerated]
      trivial
    exact UClosureHull_minimal rules Q hPre hQSeeds hx
  let aTL : Embedding Q (D.induce TL) := {
    toFun := fun x => ⟨aL x, hQRangeL x⟩
    injective := by
      intro x y hxy
      exact aL.injective (congrArg Subtype.val hxy)
    map_rel_iff := by
      intro R z
      exact aL.map_rel_iff R z
  }
  let aTR : Embedding Q (D.induce TR) := {
    toFun := fun x => ⟨aR x, hQRangeR x⟩
    injective := by
      intro x y hxy
      exact aR.injective (congrArg Subtype.val hxy)
    map_rel_iff := by
      intro R z
      exact aR.map_rel_iff R z
  }
  have hGL : GL.card ≤ j := by
    calc
      GL.card ≤ (Finset.univ : Finset E).card :=
        Finset.card_image_le
      _ = Fintype.card E := Finset.card_univ
      _ ≤ j := hCardL
  have hGR : GR.card ≤ j := by
    calc
      GR.card ≤ (Finset.univ : Finset F).card :=
        Finset.card_image_le
      _ = Fintype.card F := Finset.card_univ
      _ ≤ j := hCardR
  have hTLC : IsUClosed rules (D.induce TL) :=
    hDClosed.induce_UClosureHull (↑GL : Set V)
  have hTRC : IsUClosed rules (D.induce TR) :=
    hDClosed.induce_UClosureHull (↑GR : Set V)
  have hTLRank : USize rules (D.induce TL) ≤ j :=
    (USize_induce_UClosureHull_le rules D GL).trans hGL
  have hTRRank : USize rules (D.induce TR) ≤ j :=
    (USize_induce_UClosureHull_le rules D GR).trans hGR
  have hTLCpl : HasClosedUKCompletion K rules (D.induce TL) :=
    hRank TL hTLC hTLRank
  have hTRCpl : HasClosedUKCompletion K rules (D.induce TR) :=
    hRank TR hTRC hTRRank
  let gL : E → TL := fun x => ⟨pL x, hRangeL x⟩
  let gR : F → TR := fun x => ⟨pR x, hRangeR x⟩
  have hgL : IsClosedUHomomorphismEmbedding rules Left
      (D.induce TL) gL := hpL.codRestrict TL hRangeL
  have hgR : IsClosedUHomomorphismEmbedding rules Right
      (D.induce TR) gR := hpR.codRestrict TR hRangeR
  have hCompatL (r : H) : gL (sL r) = aTL (q r) := by
    apply Subtype.ext
    exact hRootL r
  have hCompatR (r : H) : gR (sR r) = aTR (q r) := by
    apply Subtype.ext
    exact hRootR r
  exact HasClosedUKCompletion.of_independent_projected_completions_relative
    rules hK hKIrr hSrc hRelL hRelR
    Q hQK hQClosed
    (D.induce TL) (D.induce TR)
    gL gR hgL hgR q aTL aTR hCompatL hCompatR
    hTLCpl hTRCpl

end StructuralRamsey.RelStructure
