#!/usr/bin/env python3
"""Finite relational obstruction to extending a weak-generator completion.

G is the complete simple graph on each nonempty structure, P marks function
roots, R is a partial binary relation encoding a total no-fixed-point unary
map on P. The designated U-root is the one-vertex structure with P and no R.
K consists of finite U-closed G-complete structures with Bad empty.
The finite checks concern the explicit source and target, not a computer
verification of general hereditary/strong amalgamation axioms for K.
"""
from itertools import product

def complete_graph(vertices):
    return {(x,y) for x in vertices for y in vertices if x != y}

def closed(vertices, P, Bad, R, G):
    if G != complete_graph(vertices): return False
    if any(x not in P or x == y or x not in vertices or y not in vertices for x,y in R): return False
    return all(sum(x == p for x,_ in R) == 1 for p in P)

def in_K(vertices, P, Bad, R, G):
    return not Bad and closed(vertices, P, Bad, R, G)

source={"a", "b"}; P={"a"}; Bad={"b"}; R={("a","b")}; G=complete_graph(source)
seed={"a"}; seed_R={(x,y) for x,y in R if x in seed and y in seed}
target={"u", "v"}; tP={"u"}; tBad=set(); tR={("u","v")}; tG=complete_graph(target)
assert closed(source,P,Bad,R,G)
assert not in_K(source,P,Bad,R,G)
assert in_K(target,tP,tBad,tR,tG)
assert not seed_R
# Full embedding of the EXACT weak singleton: a -> u.
assert ("a" in P) == ("u" in tP)
assert "a" not in Bad and "u" not in tBad
assert {x for x,y in R if x in seed}.issubset(seed)
# Any positive homomorphism from the full source must send Bad(b)
# to a Bad target vertex, and all K-targets are Bad-free.
assert "b" in Bad and not tBad
print("PASS: full U-closed source generated by weak singleton {a}")
print("PASS: weak singleton has full embedding into K member {u,v}")
print("PASS: source cannot positively map into any Bad-free K member")
print("K may be chosen strongly amalgamating and closed-hereditary;")
print("the mathematical class proof is in the companion note.")
